<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlowActions/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'المنشطات' ,
   'LBL_MODULE_TITLE' => 'منشطات سير العمل: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في منشطات سير العمل' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة المنشطات' ,
   'LBL_NEW_FORM_TITLE' => 'إنشئ منشط' ,
   'LBL_LIST_NAME' => 'اسم المنشط:' ,
   'LBL_LIST_TRIGGER_TYPE' => 'النوع:' ,
   'LBL_LIST_LEFT_FIELD' => 'حقل:' ,
   'LBL_LIST_OPERATOR' => 'مشغل:' ,
   'LBL_LIST_RIGHT_VALUE' => 'القيمة:' ,
   'LBL_NAME' => 'اسم المنشط:' ,
   'LBL_LEFT_FIELD' => 'حقل:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_BASE_MODULE' => 'الوحدة الأساسية:' ,
   'LNK_NEW_TRIGGER' => 'إنشئ منشط' ,
   'LNK_TRIGGER' => 'منشطات سير العمل' ,
   'LBL_TIME_INT' => 'على الأقل ' ,
   'LNK_LIST_REPORTMAKER' => 'قائمة التقرير' ,
   'LNK_NEW_REPORTMAKER' => 'إنشئ تقرير جديد' ,
   'LNK_LIST_DATASET' => 'قائمة مجموعة بيانات' ,
   'LNK_NEW_DATASET' => 'إنشئ مجموعة بيانات' ,
   'LNK_NEW_QUERYBUILDER' => 'إنشئ إستعلام' ,
   'LNK_QUERYBUILDER' => 'باني الإستعلام' ,
   'LBL_ALL_REPORTS' => 'كل التقارير' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء المنتج' ,
   'LBL_ADD_COLUMN _BUTTON_TITLE' => 'أضف [Alt+C]' ,
   'LBL_ADD_COLUMN_BUTTON_KEY' => 'C' ,
   'LBL_ADD_COLUMN_BUTTON_LABEL' => 'أضف عمود' ,
   'LBL_ADD_GROUPBY_BUTTON_LABEL' => 'أضف مجموعة بـ' ,
   'LBL_ADD_GROUPBY _BUTTON_TITLE' => 'أضف [Alt+G]' ,
   'LBL_ADD_GROUPBY_BUTTON_KEY' => 'G' ,
   'LBL_NEW_BUTTON_TITLE' => 'أضف [Alt+N]' ,
   'LBL_NEW_BUTTON_KEY' => 'N' ,
   'LBL_NEW_BUTTON_LABEL' => 'إنشئ جديد' ,
   'LBL_DETAILS_BUTTON_TITLE' => 'تفاصيل تقرير [Alt+D]' ,
   'LBL_DETAILS_BUTTON_KEY' => 'D' ,
   'LBL_DETAILS_BUTTON_LABEL' => 'تفاصيل التقرير' ,
   'LBL_EDIT_BUTTON_TITLE' => 'تحرير تقرير [Alt+E]' ,
   'LBL_EDIT_BUTTON_KEY' => 'N' ,
   'LBL_EDIT_BUTTON_LABEL' => 'تحرير التقرير' ,
   'LBL_RUN_BUTTON_TITLE' => 'تشغيل تقرير [Alt+R]' ,
   'LBL_RUN_BUTTON_KEY' => 'R' ,
   'LBL_RUN_BUTTON_LABEL' => 'تشغيل التقرير' );

?>
