<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Import/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_IMPORT_MODULE_NO_DIRECTORY' => 'الدليل ' ,
   'LBL_IMPORT_MODULE_NO_DIRECTORY_END' => ' غير موجود أو غير قابل للكتابة' ,
   'LBL_IMPORT_MODULE_ERROR_NO_UPLOAD' => 'لم يرفع الملف بنجاح. ربما يكون الأمر أن إعداد \"upload_max_filesize\" في ملف \"php.ini\" خاصتك مضبوط على رقم صغير' ,
   'LBL_IMPORT_MODULE_ERROR_LARGE_FILE' => 'الملف كبير فوق الحد. حد أقصى:' ,
   'LBL_IMPORT_MODULE_ERROR_LARGE_FILE_END' => 'بايتات. غير $sugar_config[\'upload_maxsize\'] في ملف config.php' ,
   'LBL_MODULE_NAME' => 'إستيراد' ,
   'LBL_TRY_AGAIN' => 'حاول مرة أخرى' ,
   'LBL_ERROR' => 'خطأ:' ,
   'ERR_MULTIPLE' => 'الأعمدة المتعددة تم تعريفها بنفس اسم الحقل' ,
   'ERR_MISSING_REQUIRED_FIELDS' => 'حقول ضرورية مفقودة:' ,
   'ERR_SELECT_FULL_NAME' => 'لا يمكنك اختيار الاسم الكامل عندما يكون الاسم الأول والاسم الأخير قد اختيرا.' ,
   'ERR_SELECT_FILE' => 'اختر ملفا لرفعه.' ,
   'LBL_SELECT_FILE' => 'اختر ملفا:' ,
   'LBL_CUSTOM' => 'تهيئة' ,
   'LBL_CUSTOM_CSV' => 'ملف مخصوص مفصول بفاصلة' ,
   'LBL_CSV' => 'ملف مفصول بفاصلة' ,
   'LBL_TAB' => 'ملف مفصول بتاب' ,
   'LBL_CUSTOM_DELIMETED' => 'ملف مفصول بفواصل مخصوصة' ,
   'LBL_CUSTOM_DELIMETER' => 'فاصل مخصوص:' ,
   'LBL_CUSTOM_TAB' => 'ملف مخصوص مفصول بتاب' ,
   'LBL_DONT_MAP' => 'لا تحول هذا الحقل' ,
   'LBL_STEP_1_TITLE' => 'خطوة 1: اختر المصدر' ,
   'LBL_WHAT_IS' => 'ما هو مصدر البيانات؟' ,
   'LBL_MICROSOFT_OUTLOOK' => 'أوتلوك ميكروسوفت' ,
   'LBL_ACT' => 'أكت!' ,
   'LBL_ACT_2005' => 'أكت! 2005' ,
   'LBL_SALESFORCE' => 'salesforce.com' ,
   'LBL_MY_SAVED' => 'المصادر المحفوظة الخاصة بي:' ,
   'LBL_PUBLISH' => 'انشر' ,
   'LBL_DELETE' => 'احذف' ,
   'LBL_PUBLISHED_SOURCES' => 'المصادر المنشورة:' ,
   'LBL_UNPUBLISH' => 'لا تنشر' ,
   'LBL_NEXT' => 'التالي>' ,
   'LBL_BACK' => 'السابق <' ,
   'LBL_STEP_2_TITLE' => 'خطوة2: ارفع ملف التصدير' ,
   'LBL_HAS_HEADER' => 'له ترويسة:' ,
   'LBL_NUM_1' => '1.' ,
   'LBL_NUM_2' => '2.' ,
   'LBL_NUM_3' => '3.' ,
   'LBL_NUM_4' => '4.' ,
   'LBL_NUM_5' => '5.' ,
   'LBL_NUM_6' => '6.' ,
   'LBL_NUM_7' => '7.' ,
   'LBL_NUM_8' => '8.' ,
   'LBL_NUM_9' => '9.' ,
   'LBL_NUM_10' => '10.' ,
   'LBL_NUM_11' => '11.' ,
   'LBL_NUM_12' => '12.' ,
   'LBL_NOTES' => 'ملاحظات:' ,
   'LBL_NOW_CHOOSE' => 'اختر الآن الملف لاستيراده:' ,
   'LBL_IMPORT_OUTLOOK_TITLE' => 'أوتلوك ميكروسوفت 98 و2000 يمكنهما تصدير البيانات بصيغة القيم المفصولة بفاصلة التي يمكن استخدامها لاستيراد البيانات إلى النظام. لتصدير بياناتك من أوتلوك، اتبع الخطوات أدناه:' ,
   'LBL_OUTLOOK_NUM_1' => 'ابدأ أوتلوك' ,
   'LBL_OUTLOOK_NUM_2' => 'اختر قائمة الملفات، ثم استورد وصدر...خيارات القائمة' ,
   'LBL_OUTLOOK_NUM_3' => 'اختر صدر لملف واضغط \"التالي\"' ,
   'LBL_OUTLOOK_NUM_4' => 'اختر القيم المفصولة بفاصلة (وندوز) واضغط التالي.
ملاحظة: قد يتم تنبيهك لتثبيت مكوّن التصدير' ,
   'LBL_OUTLOOK_NUM_5' => 'اختر مجلد الاتصالات واضغط على التالي. يمكنك أن تختار مجلدات اتصالات مختلفة لو كانت اتصالاتك مخزنة في مجلدات متعددة' ,
   'LBL_OUTLOOK_NUM_6' => 'اختر اسم ملف واضغط على التالي' ,
   'LBL_OUTLOOK_NUM_7' => 'اضغط على إنهاء' ,
   'LBL_IMPORT_ACT_TITLE' => 'أكت! يمكنه أن يصدر البيانات بصيغة القيم المفصولة بفاصلة التي يمكن أن تستخدم لاستيراد البيانات إلى النظام. لتصدير بياناتك من أكت!، اتبع الخطوات أدناه:' ,
   'LBL_ACT_NUM_1' => 'شغل أكت !' ,
   'LBL_ACT_NUM_2' => 'اختر قائمة الملفات، خيار قائمة تبادل البيانات، ثم خيار قائمة صدر...' ,
   'LBL_ACT_NUM_3' => 'إختر نوع الملف Text-Delimited' ,
   'LBL_ACT_NUM_4' => 'اختر اسم ملف وموضع للبيانات المصدّرة واضغط التالي' ,
   'LBL_ACT_NUM_5' => 'اختر تسجيلات الاتصالات فقط' ,
   'LBL_ACT_NUM_6' => 'اختر زر خيارات...' ,
   'LBL_ACT_NUM_7' => 'اختر الفاصلة كعلامة فصل الحقول' ,
   'LBL_ACT_NUM_8' => 'أشر على صندوق نعم، صدّر أسماء الحقول واضغط موافقة' ,
   'LBL_ACT_NUM_9' => 'اضغط التالي' ,
   'LBL_ACT_NUM_10' => 'اختر كل التسجيلات ثم اضغط على إنهاء' ,
   'LBL_IMPORT_SF_TITLE' => 'موقع salesforce.com يمكنه تصدير البيانات بصيغة القيم المفصولة بفاصلة والتي يمكن استخدامها لاستيراد البيانات إلى النظام. لتصدير بياناتك من salesforce.com، اتبع الخطوات أدناه:' ,
   'LBL_SF_NUM_1' => 'افتح مستعرضك، اذهب إلى http://www.salesforce.com، وسجل الدخول بعنوان بريدك الإلكتروني وكلمة سرك' ,
   'LBL_SF_NUM_2' => 'اضغط على لسان تقارير على القائمة العليا' ,
   'LBL_SF_NUM_3' => 'لتصدير الحسابات: اضغط على وصلة الحسابات النشطة
لتصدير الاتصالات: اضغط على وصلة القائمة البريدية' ,
   'LBL_SF_NUM_4' => 'في الخطوة 1: اختر نوع التقرير الخاص بك، اختر تقرير على شكل جدول واضغط التالي' ,
   'LBL_SF_NUM_5' => 'في الخطوة 2: اختر أعمدة التقارير، اختر الأعمدة التي تريد تصديرها واضغط على التالي' ,
   'LBL_SF_NUM_6' => 'في الخطوة 3: اختر معلومات للاختصار، وفقط اضغط التالي' ,
   'LBL_SF_NUM_7' => 'في الخطوة 4: رتب أعمدة التقارير، وفقط اضغط التالي' ,
   'LBL_SF_NUM_8' => 'في الخطوة 5: اختر معايير التقرير الخاصة بك، تحت تاريخ البدء، اختر تاريخا بعيدا بما يكفي في الماضي ليشمل كل حساباتك. يمكنك أيضا تصدير مجموعة فرعية من الحسابات باستخدام المزيد من المعايير المتقدمة. عندما تنتهي، اضغط على شغل التقرير' ,
   'LBL_SF_NUM_9' => 'سيتم توليد تقرير، والمفروض أن تعرض الصفحة أن حالة توليد التقرير: اكتمل. الآن اضغط صدّر إلى إكسل' ,
   'LBL_SF_NUM_10' => 'من صدر تقارير:، لصيغة الملف المصدر:، إختر Comma Delimited .csv ثم انقر صدر' ,
   'LBL_SF_NUM_11' => 'ستقفز لك نافذة حوارية لحفظ ملف التصدير على حاسبك' ,
   'LBL_IMPORT_CUSTOM_TITLE' => 'الكثير من التطبيقات سوف تسمح لك بتصدير البيانات إلى نص مفصول بفاصلة file (.csv). عامة معظم التطبيقات تتبع هذه الخطوات العامة:' ,
   'LBL_CUSTOM_NUM_1' => 'أطلق التطبيق وافتح ملف البيانات' ,
   'LBL_CUSTOM_NUM_2' => 'اختر خيار القائمة حفظ باسم... أو صدر...' ,
   'LBL_CUSTOM_NUM_3' => 'احفظ الملف بصيغة \"CSV\" أو بصيغة القيم المفصولة بفاصلة' ,
   'LBL_IMPORT_TAB_TITLE' => 'الكثير من التطبيقات سوف تسمح لك بتصدير البيانات بصيغة القيم المفصولة بتاب (.tsv or .tab). عامة معظم التطبيقات تتبع هذه الخطوات العامة:' ,
   'LBL_TAB_NUM_1' => 'أطلق التطبيق وافتح ملف البيانات' ,
   'LBL_TAB_NUM_2' => 'اختر خيار القائمة حفظ باسم... أو صدر...' ,
   'LBL_TAB_NUM_3' => 'حفظ الملف بصيغة القيم المفصولة بتاب أو TSV' ,
   'LBL_STEP_3_TITLE' => 'خطوة 3: أكد على الحقول واستورد' ,
   'LBL_SELECT_FIELDS_TO_MAP' => 'في القائمة أدناه، اختر الحقول في ملف استيرادك التي يجب استيرادها في كل حقل بالنظام. عندما تنتهي، اضغط استورد الآن.:' ,
   'LBL_DATABASE_FIELD' => 'حقل قاعدة بيانات' ,
   'LBL_HEADER_ROW' => 'صف ترويسة' ,
   'LBL_ROW' => 'صف' ,
   'LBL_SAVE_AS_CUSTOM' => 'الحفظ كتحويل مخصوص:' ,
   'LBL_CONTACTS_NOTE_1' => 'يجب تحويل إما الإسم الأخير أو الإسم الكامل' ,
   'LBL_CONTACTS_NOTE_2' => 'لو تم تحويل الإسم الكامل. فسوف يتم تجاهل الإسم الأول و الأخير' ,
   'LBL_CONTACTS_NOTE_3' => 'لو تم تحويل الإسم الكامل، فسوف يتم فصل بيانات الإسم الكامل إلى إسم أول و إسم أخير عند إدراجها بقاعدة البيانات.' ,
   'LBL_CONTACTS_NOTE_4' => 'سوف يتم وصل إسم الشارع في العنوان الأول واسم الشارع في العنوان الثاني مع حقل اسم شارع العنوان الرئيسي عند إدراجها بقاعدة البيانات.' ,
   'LBL_ACCOUNTS_NOTE_1' => 'اسم الحساب لابد من تحويله' ,
   'LBL_ACCOUNTS_NOTE_2' => 'سوف يتم وصل إسم الشارع في العنوان الأول واسم الشارع في العنوان الثاني مع حقل اسم شارع العنوان الرئيسي عند إدراجها بقاعدة البيانات.' ,
   'LBL_OPPORTUNITIES_NOTE_1' => 'اسم الفرصة، اسم الحساب، تاريخ الإغلاق، و مرحلة البيع هي حقول مطلوبة' ,
   'LBL_IMPORT_NOW' => 'استورد الآن' ,
   'LBL_' => '' ,
   'LBL_CANNOT_OPEN' => 'لا يمكن فتح الملف المستورد للقراءة' ,
   'LBL_NOT_SAME_NUMBER' => 'لم يوجد نفس رقم الحقول للسطر في ملفك' ,
   'LBL_NO_LINES' => 'لم توجد سطور في ملف استيرادك' ,
   'LBL_FILE_ALREADY_BEEN_OR' => 'ملف الاستيراد تمت معالجته بالفعل أو غير موجود' ,
   'LBL_SUCCESS' => 'نجاح:' ,
   'LBL_SUCCESSFULLY' => 'تم استيراده بنجاح' ,
   'LBL_LAST_IMPORT_UNDONE' => 'استيرادك الأخيرتم التراجع عنه' ,
   'LBL_NO_IMPORT_TO_UNDO' => 'لم يوجد استيراد للتراجع عنه' ,
   'LBL_FAIL' => 'فشل:' ,
   'LBL_RECORDS_SKIPPED' => 'تم تجاوز السجلات بسبب وجود نقص في أحد أو بعض الحقول المطلوبة' ,
   'LBL_IDS_EXISTED_OR_LONGER' => 'تم تجاوز السجلات لأن أرقام الفهرسة الرئيسية غير موجودة أو أطول من 36 رمز' ,
   'LBL_RESULTS' => 'النتائج' ,
   'LBL_IMPORT_MORE' => 'استورد المزيد' ,
   'LBL_FINISHED' => 'انتهى' ,
   'LBL_UNDO_LAST_IMPORT' => 'تراجع عن الاستيراد الأخير' ,
   'LBL_LAST_IMPORTED' => 'آخر ما تم استيراده' ,
   'ERR_MULTIPLE_PARENTS' => 'يمكنك فقط الحصول على هوية رئيسية واحدة معرّفة' ,
   'LBL_DUPLICATES' => 'عثر على تكرارات' ,
   'LBL_DUPLICATE_LIST' => 'نزل قائمة المتكررات' ,
   'LBL_UNIQUE_INDEX' => 'اختر فهرسا لمقارنة المتكررات' ,
   'LBL_VERIFY_DUPS' => 'تأكد من المدخلات المكررة في الفهارس المختارة' ,
   'LBL_INDEX_USED' => 'الفهرس/الفهارس مستخدمة' ,
   'LBL_INDEX_NOT_USED' => 'الفهرس/الفهارس غير مستخدمة' ,
   'LBL_IMPORT_MODULE_ERROR_NO_MOVE' => 'لم يتم رفع الملف بنجاح. تفقد صلاحيات الملف في مسار الذاكرة الوسيطة للتبيت الخاص بك' );

?>
