<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlowAlerts/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'قائمة إنذار المستلمين' ,
   'LBL_MODULE_TITLE' => 'المستلمين: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في سير عمل المستلمين' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة المستلمين' ,
   'LBL_NEW_FORM_TITLE' => 'إنشئ مستلم سير العمل' ,
   'LBL_LIST_USER_TYPE' => 'تصنيف المستخدم' ,
   'LBL_LIST_ARRAY_TYPE' => 'نوع الإجراء' ,
   'LBL_LIST_RELATE_TYPE' => 'نوع المتعلق' ,
   'LBL_LIST_ADDRESS_TYPE' => 'نوع العنوان' ,
   'LBL_LIST_FIELD_VALUE' => 'مستخدم' ,
   'LBL_LIST_REL_MODULE1' => 'الوحدة المتعلقة' ,
   'LBL_LIST_REL_MODULE2' => 'وحدة متعلقة ذات علاقة' ,
   'LBL_LIST_WHERE_FILTER' => 'الحالة' ,
   'LBL_USER_TYPE' => 'تصنيف المستخدم:' ,
   'LBL_ARRAY_TYPE' => 'نوع الإجراء:' ,
   'LBL_RELATE_TYPE' => 'نوع العلاقة:' ,
   'LBL_WHERE_FILTER' => 'الحالة:' ,
   'LBL_FIELD_VALUE' => 'المستخدم المختار:' ,
   'LBL_REL_MODULE1' => 'الوحدة المتعلقة:' ,
   'LBL_REL_MODULE2' => 'وحدة متعلقة ذات علاقة:' ,
   'LBL_CUSTOM_USER' => 'مستخدم مخصوص:' ,
   'LNK_NEW_WORKFLOW' => 'إنشئ عملية سير عمل' ,
   'LNK_WORKFLOW' => 'عناصر سير العمل' ,
   'LBL_LIST_STATEMENT' => 'نبه المستلمين:' ,
   'LBL_LIST_STATEMENT_CONTENT' => 'إرسال إنذارات للمستلم الآتي: ' ,
   'LBL_ALERT_CURRENT_USER' => 'مستخدم مرتبط بالهدف ' ,
   'LBL_ALERT_CURRENT_USER_TITLE' => 'مستخدم مرتبط بالوحدة المستهدفة' ,
   'LBL_ALERT_REL_USER' => 'مستخدم مرتبط بمتعلق ' ,
   'LBL_ALERT_REL_USER_TITLE' => 'مستخدم مرتبط بوحدة متعلقة' ,
   'LBL_ALERT_REL_USER_CUSTOM' => 'المرسل إليه مرتبط بمتعلق ' ,
   'LBL_ALERT_REL_USER_CUSTOM_TITLE' => 'المرسل إليه مرتبط بوحدة متعلقة' ,
   'LBL_ALERT_TRIG_USER_CUSTOM' => 'المرسل إليه مرتبط بوحدة مستهدفة ' ,
   'LBL_ALERT_TRIG_USER_CUSTOM_TITLE' => 'المرسل إليه مرتبط بوحدة مستهدفة' ,
   'LBL_ALERT_SPECIFIC_USER' => 'محدد ' ,
   'LBL_ALERT_SPECIFIC_USER_TITLE' => 'مستخدم محدد' ,
   'LBL_ALERT_SPECIFIC_TEAM' => 'كل المستخدمين محدد ' ,
   'LBL_ALERT_SPECIFIC_TEAM_TITLE' => 'كل المستخدمين في الفريق المحدد' ,
   'LBL_ALERT_SPECIFIC_ROLE' => 'كل المستخدمين محدد ' ,
   'LBL_ALERT_SPECIFIC_ROLE_TITLE' => 'كل المستخدمين في وظيفة محددة' ,
   'LBL_ALERT_LOGIN_USER_TITLE' => 'المستخدم المسجل دخول في وقت التنفيذ' ,
   'LBL_RECORD' => 'وحدة' ,
   'LBL_TEAM' => 'فريق' ,
   'LBL_USER' => 'مستخدم' ,
   'LBL_USER_MANAGER' => 'مدير المستخدم' ,
   'LBL_ROLE' => 'وظيفة' ,
   'LBL_SEND_EMAIL' => 'إرسال رسالة بريد إلكتروني إلى: ' ,
   'LBL_USER1' => ' الذي أنشأ السجل' ,
   'LBL_USER2' => ' آخر من من قام بتغيير هذا السجل' ,
   'LBL_USER3' => 'الحالي ' ,
   'LBL_USER3b' => ' من النظام' ,
   'LBL_USER4' => ' من يكلف السجل؟' ,
   'LBL_USER5' => ' من كلف السجل؟' ,
   'LBL_ADDRESS_TO' => 'إلى:' ,
   'LBL_ADDRESS_CC' => 'نسخة:' ,
   'LBL_ADDRESS_BCC' => 'نسخة مخفية:' ,
   'LBL_ADDRESS_TYPE' => 'العنوان المستخدم ' ,
   'LBL_ADDRESS_TYPE_TARGET' => 'نوع' ,
   'LBL_ALERT_REL1' => 'الوحدة المتعلقة: ' ,
   'LBL_ALERT_REL2' => 'وحدة متعلقة ذات علاقة: ' ,
   'LBL_NEXT_BUTTON' => 'التالي' ,
   'LBL_PREVIOUS_BUTTON' => 'السابق' ,
   'LBL_BLANK' => '' ,
   'NTC_REMOVE_ALERT_USER' => 'هل أنت متأكد أنك تريد إلغاء مستلم الإنذار هذا؟' ,
   'LBL_REL_CUSTOM_STRING' => 'إختر بريد الإلكتروني و أسم للحقول مخصوص' ,
   'LBL_REL_CUSTOM' => 'إختر حقل بريد الإلكتروني مخصوص: ' ,
   'LBL_REL_CUSTOM2' => 'حقل ' ,
   'LBL_AND' => 'و أسم الحقل:' ,
   'LBL_REL_CUSTOM3' => 'حقل' ,
   'LBL_FILTER_CUSTOM' => '(منقيات إضافية) نقي وحدة متعلقة بتحديد ' ,
   'LBL_FIELD' => 'حقل' ,
   'LBL_SPECIFIC_FIELD' => 'حقل' ,
   'LBL_FILTER_BY' => '(منقيات إضافية) نقي وحدة متعلقة ' ,
   'LBL_MODULE_NAME_INVITE' => 'قائمة المدعويين' ,
   'LBL_LIST_STATEMENT_INVITE' => 'المدعوون اجتماع/إتصال :' ,
   'LBL_SELECT_VALUE' => 'يجب أن تختار قيمة صحيحة' );

?>
