<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Dropdown/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_KEY' => 'مفتاح' ,
   'LBL_VALUE' => 'القيمة' ,
   'LBL_ADD' => 'إضافة' ,
   'LBL_MOVE' => 'حرك' ,
   'LBL_INSERT' => 'إدرج' ,
   'LBL_EDIT' => 'تحرير' ,
   'LBL_DELETE' => 'حذف' ,
   'LBL_DROPDOWN' => 'قائمة منسدلة:' ,
   'LBL_LANGUAGE' => 'لغة:' ,
   'LBL_MODULE_NAME' => 'قائمة منسدلة' ,
   'LBL_MODULE_TITLE' => 'قائمة منسدلة: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'قائمة إختيار منسدلة' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة منسدلة' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LNK_NEW_DROPDOWN' => 'إنشاء قائمة منسدلة' ,
   'LNK_DROPDOWNS' => 'قوائم منسدلة' ,
   'LNK_UP' => 'أعلى' ,
   'LNK_DOWN' => 'أسفل' ,
   'LNK_INSERT' => 'إدرج' ,
   'LNK_EDIT' => 'تحرير' ,
   'LNK_DELETE' => 'حذف' );

?>
