<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/DocumentRevisions/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'مراجعة المستند' ,
   'LNK_NEW_DOCUMENT' => 'إنشاء مستندا' ,
   'LNK_DOCUMENT_LIST' => 'قائمة المستندات' ,
   'LBL_REVISION_NAME' => 'رقم المراجعة' ,
   'LBL_FILENAME' => 'اسم الملف' ,
   'LBL_MIME' => 'نوع Mime' ,
   'LBL_REVISION' => 'مراجعة' ,
   'LBL_DOCUMENT' => 'مستند ذو علاقة' ,
   'LBL_LATEST_REVISION' => 'آخر مراجعة' ,
   'LBL_CHANGE_LOG' => 'غير السجل' ,
   'LBL_ACTIVE_DATE' => 'انشر التاريخ' ,
   'LBL_EXPIRATION_DATE' => 'تاريخ الانتهاء' ,
   'LBL_FILE_EXTENSION' => 'امتداد الملف' ,
   'LBL_DET_CREATED_BY' => 'أنشئ بواسطة:' ,
   'LBL_DET_DATE_CREATED' => 'التاريخ المنشأ فيه:' ,
   'LBL_DOC_NAME' => 'اسم المستند:' ,
   'LBL_DOC_VERSION' => 'مراجعة:' ,
   'LBL_REV_LIST_REVISION' => 'مراجعة' ,
   'LBL_REV_LIST_ENTERED' => 'التاريخ المنشأ فيه' ,
   'LBL_REV_LIST_CREATED' => 'أنشأه' ,
   'LBL_REV_LIST_LOG' => 'غير السجل' ,
   'LBL_REV_LIST_FILENAME' => 'اسم الملف' ,
   'LBL_CURRENT_DOC_VERSION' => 'آخر مراجعة:' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث عن المستند' ,
   'ERR_FILENAME' => 'اسم الملف' ,
   'ERR_DOC_VERSION' => 'نسخة المستند' ,
   'ERR_DELETE_CONFIRM' => 'هل تريد حذف مراجعة المستند هذه؟' ,
   'ERR_DELETE_LATEST_VERSION' => 'ليس مسموحا لك بحذف آخر مراجعة لمستند.' );

?>
