<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ForecastSchedule/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'توقعات' ,
   'LNK_NEW_OPPORTUNITY' => 'إنشاء فرصة' ,
   'LBL_MODULE_TITLE' => 'توقعات' ,
   'LBL_LIST_FORM_TITLE' => 'التوقعات المنفذه' ,
   'LNK_UPD_FORECAST' => 'توقع ورقة العمل' ,
   'LNK_QUOTA' => 'حصص' ,
   'LNK_FORECAST_LIST' => 'توقع المحفوظات' ,
   'LBL_FORECAST_HISTORY' => 'التوقعات: المحفوظات' ,
   'LBL_FORECAST_HISTORY_TITLE' => 'التوقعات: المحفوظات' ,
   'LBL_TIMEPERIOD_NAME' => 'فترة زمنية' ,
   'LBL_USER_NAME' => 'اسم المستخدم' ,
   'LBL_REPORTS_TO_USER_NAME' => 'تقارير لـ' ,
   'LBL_FORECAST_ID' => 'ID' ,
   'LBL_FORECAST_TIME_ID' => 'هوية الفترة الزمنية' ,
   'LBL_FORECAST_TYPE' => 'نوع التوقع' ,
   'LBL_FORECAST_OPP_COUNT' => 'فرص بيع' ,
   'LBL_FORECAST_OPP_WEIGH' => 'الكمية المرجحة' ,
   'LBL_FORECAST_OPP_COMMIT' => 'الحالة المحتملة' ,
   'LBL_FORECAST_OPP_BEST_CASE' => 'الحالة الأفضل' ,
   'LBL_FORECAST_OPP_WORST' => 'الحالة الأسوأ' ,
   'LBL_FORECAST_USER' => 'مستخدم' ,
   'LBL_DATE_COMMITTED' => 'تاريخ إتمام التنفيذ' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_CREATED_BY' => 'أنشأه' ,
   'LBL_DELETED' => 'تم الحذف' ,
   'LBL_QC_TIME_PERIOD' => 'فترة زمنية:' ,
   'LBL_QC_OPPORTUNITY_COUNT' => 'عدد فرص البيع:' ,
   'LBL_QC_WEIGHT_VALUE' => 'الكمية المرجحة:' ,
   'LBL_QC_COMMIT_VALUE' => 'تنفيذ الكمية:' ,
   'LBL_QC_COMMIT_BUTTON' => 'نفذ' ,
   'LBL_QC_WORKSHEET_BUTTON' => 'ورقة عمل' ,
   'LBL_QC_ROLL_COMMIT_VALUE' => 'جاهز لتنفيذ الكمية:' ,
   'LBL_QC_DIRECT_FORECAST' => 'توقعي المباشر:' ,
   'LBL_QC_ROLLUP_FORECAST' => 'توقع المجموعة:' ,
   'LBL_QC_UPCOMING_FORECASTS' => 'التوقعات' ,
   'LBL_QC_LAST_DATE_COMMITTED' => 'تاريخ آخر تنفيذ:' ,
   'LBL_QC_LAST_COMMIT_VALUE' => 'مبلغ آخر تنفيذ:' ,
   'LBL_QC_HEADER_DELIM' => 'إلى' ,
   'LBL_OW_OPPORTUNITIES' => 'فرصة' ,
   'LBL_OW_ACCOUNTNAME' => 'حساب' ,
   'LBL_OW_REVENUE' => 'كمية' ,
   'LBL_OW_WEIGHTED' => 'الكمية المرجحة' ,
   'LBL_OW_MODULE_TITLE' => 'ورقة عمل فرصة العمل' ,
   'LBL_OW_PROBABILITY' => 'إحتمالية' ,
   'LBL_OW_NEXT_STEP' => 'الخطوة التالية' ,
   'LBL_OW_DESCRIPTION' => 'وصف' ,
   'LBL_OW_TYPE' => 'النوع' ,
   'LNK_NEW_TIMEPERIOD' => 'إنشئ فترة زمنية' ,
   'LNK_TIMEPERIOD_LIST' => 'فترات زمنية' ,
   'LBL_SVFS_FORECASTDATE' => 'تاريخ بداية الجدول الزمني' ,
   'LBL_SVFS_STATUS' => 'الحالة' ,
   'LBL_SVFS_USER' => 'لـ' ,
   'LBL_SVFS_CASCADE' => 'متاح لإستلام التقارير؟' ,
   'LBL_SVFS_HEADER' => 'توقع المجدول:' ,
   'LB_FS_KEY' => 'ID' ,
   'LBL_FS_TIMEPERIOD_ID' => 'هوية الفترة الزمنية' ,
   'LBL_FS_USER_ID' => 'هوية المستخدم' ,
   'LBL_FS_TIMEPERIOD' => 'فترة زمنية' ,
   'LBL_FS_START_DATE' => 'تاريخ البدء' ,
   'LBL_FS_END_DATE' => 'تاريخ الانتهاء' ,
   'LBL_FS_FORECAST_START_DATE' => 'تاريخ بدء التوقع' ,
   'LBL_FS_STATUS' => 'الحالة' ,
   'LBL_FS_FORECAST_FOR' => 'الجدول الزمني لـ:' ,
   'LBL_FS_CASCADE' => 'متاح لإستلام تقارير المستخدمين؟' ,
   'LBL_FS_MODULE_NAME' => 'توقع المجدول' ,
   'LBL_FS_CREATED_BY' => 'أنشأه' ,
   'LBL_FS_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_FS_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_FS_DELETED' => 'تم الحذف' ,
   'LBL_FDR_USER_NAME' => 'تقرير مباشر' ,
   'LBL_FDR_OPPORTUNITIES' => 'فرص الدخل في التوقع:' ,
   'LBL_FDR_WEIGH' => 'الكمية المرجح الفرص البيع:' ,
   'LBL_FDR_COMMIT' => 'الكمية المنفذ' ,
   'LBL_FDR_DATE_COMMIT' => 'تاريخ التنفيذ' ,
   'LBL_DV_HEADER' => 'التوقعات: ورقة العمل' ,
   'LBL_DV_MY_FORECASTS' => 'التوقعات' ,
   'LBL_DV_MY_TEAM' => 'توقعات الفريق' ,
   'LBL_DV_TIMEPERIODS' => 'فترات زمنية:' ,
   'LBL_DV_FORECAST_PERIOD' => 'الفترة الزمنية للتوقع' ,
   'LBL_DV_FORECAST_OPPORTUNITY' => 'توقعات فرص الدخل' ,
   'LBL_SEARCH' => 'إختيار' ,
   'LBL_SEARCH_LABEL' => 'إختيار' ,
   'LBL_COMMIT_HEADER' => 'تنفيذ التوقع' ,
   'LBL_DV_LAST_COMMIT_DATE' => 'تاريخ آخر تنفيذ:' ,
   'LBL_DV_LAST_COMMIT_AMOUNT' => 'أخر كمية تم تنفيذه:' ,
   'LBL_DV_FORECAST_ROLLUP' => 'جاهز لتنفيذ التوقع' ,
   'LBL_DV_TIMEPERIOD' => 'فترة زمنية:' ,
   'LBL_DV_TIMPERIOD_DATES' => 'مدى التاريخ:' ,
   'LBL_LV_TIMPERIOD' => 'مدة زمنية' ,
   'LBL_LV_TIMPERIOD_START_DATE' => 'تاريخ البدء' ,
   'LBL_LV_TIMPERIOD_END_DATE' => 'تاريخ الانتهاء' ,
   'LBL_LV_TYPE' => 'نوع التوقع' ,
   'LBL_LV_COMMIT_DATE' => 'تاريخ إتمام التنفيذ' ,
   'LBL_LV_OPPORTUNITIES' => 'فرص بيع' ,
   'LBL_LV_WEIGH' => 'الكمية المرجحة' ,
   'LBL_LV_COMMIT' => 'الكمية المنفذ' ,
   'LBL_COMMIT_NOTE' => 'أدخل المبالغ التي تريد تنفيذها للمدد لزمنية المختارة:' ,
   'LBL_COMMIT_MESSAGE' => 'هل تريد تنفيذ هذه الكميات؟' ,
   'ERR_FORECAST_AMOUNT' => 'تنفيذ الكمية مطلوب و يجب أن يكون رقم' ,
   'LBL_FC_START_DATE' => 'تاريخ البدء' ,
   'LBL_FC_USER' => 'الجدول الزمني لـ' ,
   'LBL_NO_ACTIVE_TIMEPERIOD' => 'لا يوجد فترات زمنية منشطة للتوقع' ,
   'LBL_FDR_ADJ_AMOUNT' => 'الكمية المعدلة' ,
   'LBL_SAVE_WOKSHEET' => 'أحفظ ورقة العمل' ,
   'LBL_RESET_WOKSHEET' => 'أعد الوضع الإبتدائي لورقة العمل' ,
   'LBL_RESET_CHECK' => 'كل بيانات ورقة العمل للفترة الزمنية المختارة و المستخدمين المسجلين دخول سيتم إزالتهم، هل نكمل؟' ,
   'LB_FS_LIKELY_CASE' => 'الحالة المحتملة' ,
   'LB_FS_WORST_CASE' => 'الحالة الأسوأ' ,
   'LB_FS_BEST_CASE' => 'الحالة الأفضل' ,
   'LBL_FDR_WK_LIKELY_CASE' => 'الحالة الأكثر إحتمالا المقدرة' ,
   'LBL_FDR_WK_BEST_CASE' => 'أفضل حالة مقدرة' ,
   'LBL_FDR_WK_WORST_CASE' => 'أسوأ حالة مقدرة' ,
   'LBL_BEST_CASE' => 'الحالة الأفضل:' ,
   'LBL_LIKELY_CASE' => 'الحالة المحتملة:' ,
   'LBL_WORST_CASE' => 'الحالة الأسوأ:' ,
   'LBL_FDR_C_BEST_CASE' => 'الحالة الأفضل' ,
   'LBL_FDR_C_WORST_CASE' => 'الحالة الأسوأ' ,
   'LBL_FDR_C_LIKELY_CASE' => 'الحالة المحتملة' ,
   'LBL_QC_LAST_BEST_CASE' => 'آخر كمية منفذه ( أفضل حالة) :' ,
   'LBL_QC_LAST_LIKELY_CASE' => 'آخر كمية منفذه( الحالة المحتملة):' ,
   'LBL_QC_LAST_WORST_CASE' => 'آخر كمية منفذه( أسوأ حالة):' ,
   'LBL_QC_ROLL_BEST_VALUE' => 'الكمية المجهز ااتنفيذ( أفضل حالة):' ,
   'LBL_QC_ROLL_LIKELY_VALUE' => ' الكمية المجهز للتنفيذ( الحالة المحتملة):' ,
   'LBL_QC_ROLL_WORST_VALUE' => 'الكمية المحهز للتنفيذ( أسوأ حالة):' ,
   'LBL_QC_COMMIT_BEST_CASE' => 'نفذ الكمية( أفضل حالة):' ,
   'LBL_QC_COMMIT_LIKELY_CASE' => 'نفذ الكمية ( الحالة المحتملة):' ,
   'LBL_QC_COMMIT_WORST_CASE' => 'نفذ الكمية(أسوأ حالة):' );

?>
