<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlowAlertShells/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'الإنذارات' ,
   'LBL_MODULE_TITLE' => 'الإنذارات: الرئيسية' ,
   'LBL_MODULE_SECTION_TITLE' => 'سيتم تنفيذ هذه العمليات' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في إنذار سير العمل' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الإنذارات' ,
   'LBL_NEW_FORM_TITLE' => 'إنشاء إنذار سير العمل' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_ALERT_TYPE' => 'نوع الإنذار' ,
   'LBL_LIST_ALERT_TEXT' => 'رسالة الإنذار' ,
   'LBL_CUSTOM_TEMPLATE_NAME' => 'نموذج مخصوص' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_ALERT_TEXT' => 'نص الإنذار:' ,
   'LBL_ALERT_TYPE' => 'نوع الإنذار:' ,
   'LBL_SOURCE_TYPE' => 'نوع المصدر:' ,
   'LBL_LIST_TYPE' => 'النوع:' ,
   'LNK_NEW_WORKFLOW' => 'إنشاء تعريف سير العمل' ,
   'LNK_WORKFLOW' => 'قائمة تعريفات سير العمل' ,
   'LBL_PARENT_WORKFLOW' => 'العنصر الرئيسي في سير العمل:' ,
   'LBL_RETURN_TO_WORKFLOW' => 'الرجوع إلى تعريف سير العمل' ,
   'NTC_REMOVE_ALERT' => 'هل أنت متأكد أنك تريد حذف هذا الإنذار و كل مستلمينه؟' ,
   'LBL_LIST_STATEMENT' => 'وصف الحدث:' ,
   'STATEMENT_PART1' => 'إرسال' ,
   'STATEMENT_PART2' => 'بأستخدام' ,
   'LNK_LIST_REPORTMAKER' => 'قائمة التقرير' ,
   'LNK_NEW_REPORTMAKER' => 'إنشئ تقرير جديد' ,
   'LNK_LIST_DATASET' => 'قائمة مجموعة بيانات' ,
   'LNK_NEW_DATASET' => 'إنشئ مجموعة بيانات' ,
   'LNK_NEW_QUERYBUILDER' => 'إنشئ إستعلام' ,
   'LNK_QUERYBUILDER' => 'باني الإستعلام' ,
   'LBL_ALL_REPORTS' => 'كل التقارير' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء المنتج' ,
   'LBL_NEW_BUTTON_LABEL_ALERT' => 'إنشئ إنذار' ,
   'LBL_NEW_BUTTON_KEY_ALERT' => 'A' ,
   'LBL_NEW_BUTTON_TITLE_ALERT' => 'إنشئ إنذار [Alt+A]' ,
   'LBL_NEW_BUTTON_LABEL_ACTION' => 'إنشئ إجراء' ,
   'LBL_NEW_BUTTON_KEY_ACTION' => 'C' ,
   'LBL_NEW_BUTTON_TITLE_ACTION' => 'إنشئ إجراء [Alt+C]' ,
   'LBL_MODULE_NAME_COMBO' => 'الإنذارات' ,
   'LNK_ALERT_TEMPLATES' => 'نماذج الإخطار' ,
   'LNK_PROCESS_VIEW' => 'ترتيب تنفيذ مسار العمل' ,
   'LBL_LIST_COMPONENTS' => 'مكونات' ,
   'LBL_RECIPIENTS' => 'المرسل إليهم' ,
   'LBL_MODULE_TITLE_INVITE' => 'إدعو' );

?>
