<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Documents/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'مستندات' ,
   'LBL_MODULE_TITLE' => 'المستندات: رئيسية' ,
   'LNK_NEW_DOCUMENT' => 'إنشاء مستندا' ,
   'LNK_DOCUMENT_LIST' => 'قائمة المستندات' ,
   'LBL_DOC_REV_HEADER' => 'مراجعات المستند' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث عن المستند' ,
   'LBL_DOCUMENT_ID' => 'هوية المستند' ,
   'LBL_NAME' => 'اسم المستند' ,
   'LBL_DESCRIPTION' => 'وصف' ,
   'LBL_CATEGORY' => 'فئة' ,
   'LBL_SUBCATEGORY' => 'فئة فرعية' ,
   'LBL_STATUS' => 'الحالة' ,
   'LBL_CREATED_BY' => 'أنشأه' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_DELETED' => 'تم الحذف' ,
   'LBL_MODIFIED' => 'عدّله' ,
   'LBL_MODIFIED_USER' => 'عدّله' ,
   'LBL_CREATED' => 'أنشأه' ,
   'LBL_RELATED_DOCUMENT_ID' => 'هوية مستند ذات علاقة' ,
   'LBL_RELATED_DOCUMENT_REVISION_ID' => 'هوية مراجعة مستند ذات علاقة' ,
   'LBL_IS_TEMPLATE' => 'قالب' ,
   'LBL_TEMPLATE_TYPE' => 'نوع المستند' ,
   'LBL_REVISION_NAME' => 'رقم المراجعة' ,
   'LBL_MIME' => 'نوع Mime' ,
   'LBL_REVISION' => 'مراجعة' ,
   'LBL_DOCUMENT' => 'مستند ذو علاقة' ,
   'LBL_LATEST_REVISION' => 'آخر مراجعة' ,
   'LBL_CHANGE_LOG' => 'غير السجل' ,
   'LBL_ACTIVE_DATE' => 'انشر التاريخ' ,
   'LBL_EXPIRATION_DATE' => 'تاريخ الانتهاء' ,
   'LBL_FILE_EXTENSION' => 'امتداد الملف' ,
   'LBL_CAT_OR_SUBCAT_UNSPEC' => 'غير محدد' ,
   'LBL_DOC_NAME' => 'اسم المستند:' ,
   'LBL_FILENAME' => 'اسم الملف:' ,
   'LBL_DOC_VERSION' => 'مراجعة:' ,
   'LBL_CATEGORY_VALUE' => 'فئة:' ,
   'LBL_SUBCATEGORY_VALUE' => 'فئة فرعية:' ,
   'LBL_DOC_STATUS' => 'الحالة:' ,
   'LBL_LAST_REV_CREATOR' => 'المراجعة أنشئت بواسطة:' ,
   'LBL_LAST_REV_DATE' => 'تاريخ المراجعة:' ,
   'LBL_DOWNNLOAD_FILE' => 'ملف التحميل:' ,
   'LBL_DET_RELATED_DOCUMENT' => 'مستند ذو علاقة:' ,
   'LBL_DET_RELATED_DOCUMENT_VERSION' => 'مراجعة مستند ذي علاقة:' ,
   'LBL_DET_IS_TEMPLATE' => 'قالب؟:' ,
   'LBL_DET_TEMPLATE_TYPE' => 'نوع المستند:' ,
   'LBL_TEAM' => 'فريق:' ,
   'LBL_DOC_DESCRIPTION' => 'وصف:' ,
   'LBL_DOC_ACTIVE_DATE' => 'انشر التاريخ:' ,
   'LBL_DOC_EXP_DATE' => 'تاريخ الانتهاء:' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة مستندات؟' ,
   'LBL_LIST_DOCUMENT' => 'مستند' ,
   'LBL_LIST_CATEGORY' => 'فئة' ,
   'LBL_LIST_SUBCATEGORY' => 'فئة فرعية' ,
   'LBL_LIST_REVISION' => 'مراجعة' ,
   'LBL_LIST_LAST_REV_CREATOR' => 'نشر بواسطة' ,
   'LBL_LIST_LAST_REV_DATE' => 'تاريخ المراجعة' ,
   'LBL_LIST_VIEW_DOCUMENT' => 'إظهار' ,
   'LBL_LIST_DOWNLOAD' => 'تحميل' ,
   'LBL_LIST_ACTIVE_DATE' => 'انشر التاريخ' ,
   'LBL_LIST_EXP_DATE' => 'تاريخ الانتهاء' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_SF_DOCUMENT' => 'اسم المستند:' ,
   'LBL_SF_CATEGORY' => 'فئة:' ,
   'LBL_SF_SUBCATEGORY' => 'فئة فرعية:' ,
   'LBL_SF_ACTIVE_DATE' => 'انشر التاريخ:' ,
   'LBL_SF_EXP_DATE' => 'تاريخ الانتهاء:' ,
   'DEF_CREATE_LOG' => 'تم إنشاء المستند' ,
   'ERR_DOC_NAME' => 'اسم المستند' ,
   'ERR_DOC_ACTIVE_DATE' => 'انشر التاريخ' ,
   'ERR_DOC_EXP_DATE' => 'تاريخ الانتهاء' ,
   'ERR_FILENAME' => 'اسم الملف' ,
   'ERR_DOC_VERSION' => 'نسخة المستند' ,
   'ERR_DELETE_CONFIRM' => 'هل تريد حذف مراجعة المستند هذه؟' ,
   'ERR_DELETE_LATEST_VERSION' => 'ليس مسموحا لك بحذف آخر مراجعة لمستند.' ,
   'LNK_NEW_MAIL_MERGE' => 'دمج بريد' ,
   'LBL_MAIL_MERGE_DOCUMENT' => 'قالب دمج البريد:' ,
   'LBL_TREE_TITLE' => 'مستندات' ,
   'LBL_LIST_DOCUMENT_NAME' => 'اسم المستند' ,
   'LBL_CONTRACT_NAME' => 'اسم العقد:' ,
   'LBL_LIST_IS_TEMPLATE' => 'قالب؟' ,
   'LBL_LIST_TEMPLATE_TYPE' => 'نوع المستند' ,
   'LBL_LIST_SELECTED_REVISION' => 'المراجعة المختارة' ,
   'LBL_LIST_LATEST_REVISION' => 'آخر مراجعة' ,
   'LBL_CONTRACTS_SUBPANEL_TITLE' => 'العقود ذات العلاقة' ,
   'LBL_LAST_REV_CREATE_DATE' => 'تاريخ إنشاء آخر مراجعة' );

?>
