<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlowActionShells/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'إجراءات' ,
   'LBL_MODULE_TITLE' => 'منشطات سير العمل: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في منشطات سير العمل' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الإجراءات' ,
   'LBL_NEW_FORM_TITLE' => 'إنشئ منشط' ,
   'LBL_LIST_NAME' => 'اسم المنشط:' ,
   'LBL_LIST_TYPE' => 'النوع:' ,
   'LBL_LIST_EVAL' => 'Eval:' ,
   'LBL_LIST_FIELD' => 'حقل:' ,
   'LBL_NAME' => 'اسم المنشط:' ,
   'LBL_FIELD' => 'حقل:' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_EVAL' => 'تقييم المنشط:' ,
   'LBL_SHOW_PAST' => 'تحرير القيمة السابقة:' ,
   'LNK_NEW_TRIGGER' => 'إنشئ منشط' ,
   'LNK_TRIGGER' => 'منشطات سير العمل' ,
   'NTC_REMOVE_ACTION' => 'هل أنت متأكد أنك تريد إلغاء هذا التقرير؟' ,
   'LBL_ACTION_UPDATE_TITLE' => 'حدث الحقول في الوحدة المستهدفة' ,
   'LBL_ACTION_UPDATE_REL_TITLE' => 'حدث الحقول في الوحدة لبمتعلقة' ,
   'LBL_ACTION_NEW_TITLE' => 'إنشئ سجل في وحدة مرتبط بوحدة مستهدفة' ,
   'LBL_LIST_STATEMENT' => 'وصف الحدث:' ,
   'LBL_ACTION_UPDATE' => 'حدث الحقول في الهدف ' ,
   'LBL_ACTION_UPDATE_REL' => 'حدث الحقول في المتعلق' ,
   'LBL_ACTION_UPDATE_REL_PART2' => 'الكل' ,
   'LBL_ACTION_UPDATE_REL_PART3' => 'متعلق' ,
   'LBL_ACTION_NEW' => 'إنشئ جديد' ,
   'LBL_RECORD' => 'سجل' ,
   'LBL_ACTION_NEW_REL' => 'إنشئ جديد' ,
   'LBL_ACTION_NEW_REL_TITLE' => 'إنشئ سجل مرتبط بوحدة متعلقة بالوحدة المستهدفة' ,
   'LBL_RELATED_RECORD' => 'سجل' ,
   'LBL_NEXT_BUTTON' => 'التالي' ,
   'LBL_PREVIOUS_BUTTON' => 'السابق' ,
   'LBL_LIST_ACTION_DESCRIPTION' => 'إجراءات للتنفيذ:' ,
   'LBL_INVITEES' => 'المدعوون' ,
   'LBL_DETAILS' => 'تفاصيل' ,
   'LBL_SELECT_VALUE' => 'يجب أن تختار قيمة صحيحة' ,
   'LBL_SELECT_MODULE' => 'يجب إختيار وحدة' ,
   'LBL_SELECT_RELATED_MODULE' => 'يجب إختيار وحدة متعلقة' );

?>
