<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Feeds/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'تلقيمات الأخبار' ,
   'LBL_MODULE_ID' => 'مزودات' ,
   'LBL_MODULE_TITLE' => 'تلقيمات الخلاصات: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في تلقيمات خلاصات الأخبار' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة تلقيمات خلاصات الأخبار' ,
   'LBL_MY_LIST_FORM_TITLE' => 'تلقيمات خلاصات الأخبار الخاصة بي' ,
   'LBL_NEW_FORM_TITLE' => 'تلقيمة خلاصة أخبار جديدة' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'من الضروري تحديد رقم سجل لإلغاء اتصال ' ,
   'LNK_NEW_FEED' => 'تلقيمة خلاصة أخبار جديدة' ,
   'LNK_FEED_LIST' => 'كل تلقيمات خلاصات الأخبار' ,
   'LNK_MY_FEED_LIST' => 'تلقيمات خلاصات الأخبار الخاصة بي' ,
   'LBL_TITLE' => 'اللقب' ,
   'LBL_RSS_URL' => 'رابط تلقيمات خلاصات' ,
   'LBL_ONLY_MY' => 'المفضلة الخاصة بي فقط' ,
   'LBL_VISIT_WEBSITE' => 'زر الموقع' ,
   'LBL_LAST_UPDATED' => 'تم تحديثه آخر مرة في' ,
   'LBL_DELETE_FAVORITES' => 'احذف من المفضلة' ,
   'LBL_DELETE_FAV_BUTTON_TITLE' => 'احذف من المفضلة [Alt+D]' ,
   'LBL_DELETE_FAV_BUTTON_KEY' => '[Alt+D]' ,
   'LBL_DELETE_FAV_BUTTON_LABEL' => 'احذف من المفضلة' ,
   'LBL_ADD_FAV_BUTTON_TITLE' => 'أضف للمفضلة [Alt+A]' ,
   'LBL_ADD_FAV_BUTTON_KEY' => '[Alt+A]' ,
   'LBL_ADD_FAV_BUTTON_LABEL' => 'أضف للمفضلة' ,
   'LBL_MOVE_UP' => 'حرك لأعلى' ,
   'LBL_MOVE_DOWN' => 'حرك لأسفل' ,
   'LBL_FEED_NOT_AVAILABLE' => 'التلقيمة غير متاحة' ,
   'LBL_REFRESH_CACHE' => 'اضغط هنا لتحديث الذاكرة الوسيطة' ,
   'LBL_TILE' => 'اللقب' ,
   'LBL_URL' => 'وصلة' ,
   'LBL_DESCRIPTION' => 'وصف' );

?>
