<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProductCategories/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'فئات النتج' ,
   'LBL_MODULE_TITLE' => 'فئات المنتج: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في نوع المنتج' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة فئات المنتج' ,
   'LBL_PRODUCTCATEGORY' => 'فئة المنتج:' ,
   'LBL_LIST_NAME' => 'فئة المنتج' ,
   'LBL_LIST_DESCRIPTION' => 'وصف' ,
   'LBL_NAME' => 'فئة المنتج:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_LIST_LIST_ORDER' => 'ترتيب' ,
   'LBL_LIST_ORDER' => 'ترتيب:' ,
   'LNK_PRODUCT_LIST' => 'كتالوج المنتج' ,
   'LNK_NEW_PRODUCT' => 'إنشئ عنصر في دليل المنتج' ,
   'LNK_NEW_MANUFACTURER' => 'المصنعين' ,
   'LNK_NEW_SHIPPER' => 'مقدم خدمات الشحن' ,
   'LNK_NEW_PRODUCT_CATEGORY' => 'فئات النتج' ,
   'LNK_NEW_PRODUCT_TYPE' => 'أنواع المنتج' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء نوع المنتج' ,
   'NTC_LIST_ORDER' => 'أعد ترتيب ظهور هذه الفئة في القوائم المنسدلة لفئة المنتج' ,
   'LNK_IMPORT_PRODUCT_CATEGORIES' => 'إستورد فئات منتج' ,
   'LBL_DISABLE_ALERT' => 'الفئة الأم هذه غير صحيحة' ,
   'NTC_DELETE_PRUNE_CONFIRMATION' => 'ها أنت متأكد أنك تريد مسح هذه الفئة و كل فئاتها الفرعية و منتجاتها؟' ,
   'NTC_DELETE_GRAFT_CONFIRMATION' => 'هل أنت متأكد أنك تريد مسح هذا المنتج؟ كل الفئات الفرعية و المنتجات ستبقى' ,
   'LBL_PARENT_NAME' => 'الفئة الأم:' ,
   'LBL_CATEGORIES' => 'فئات' );

?>
