<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Bugs/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'متتبع المشكلات' ,
   'LBL_MODULE_TITLE' => 'متتبع المشكلات: رئيسية' ,
   'LBL_MODULE_ID' => 'مشكلات' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث عن مشكلات' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة المشكلات' ,
   'LBL_NEW_FORM_TITLE' => 'مشكلة جديدة' ,
   'LBL_CONTACT_BUG_TITLE' => 'مشكلة اتصال:' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LBL_BUG' => 'مشكلة:' ,
   'LBL_BUG_NUMBER' => 'رقم المشكلة:' ,
   'LBL_NUMBER' => 'رقم:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_PRIORITY' => 'أولوية:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال:' ,
   'LBL_BUG_SUBJECT' => 'موضوع المشكلة:' ,
   'LBL_CONTACT_ROLE' => 'صلاحية:' ,
   'LBL_LIST_NUMBER' => 'رقم' ,
   'LBL_LIST_SUBJECT' => 'الموضوع' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_PRIORITY' => 'أولوية' ,
   'LBL_LIST_RELEASE' => 'إصدار' ,
   'LBL_LIST_RESOLUTION' => 'حل المشكلة' ,
   'LBL_LIST_LAST_MODIFIED' => 'آخر مرة تعديل' ,
   'LBL_INVITEE' => 'جهات إتصال' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_LIST_TYPE' => 'النوع' ,
   'LBL_RESOLUTION' => 'حل المشكلة:' ,
   'LBL_RELEASE' => 'إصدار:' ,
   'LNK_NEW_BUG' => 'إخطار بالمشكلة' ,
   'LNK_BUG_LIST' => 'مشكلات' ,
   'NTC_REMOVE_INVITEE' => 'هل أنت متأكد أنك تريد إزالة هذا الاتصال من المشكلة؟' ,
   'NTC_REMOVE_ACCOUNT_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذه المشكلة من هذا الحساب؟' ,
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم تسجيل لإلغاء المشكلة' ,
   'LBL_LIST_MY_BUGS' => 'المشكلات المكلف بها' ,
   'LBL_FOUND_IN_RELEASE' => 'عثر عليها في الإصدار:' ,
   'LBL_FIXED_IN_RELEASE' => 'تم إصلاحها في الإصدار:' ,
   'LBL_LIST_FIXED_IN_RELEASE' => 'تم إصلاحها في الإصدار' ,
   'LBL_WORK_LOG' => 'سجل عمل:' ,
   'LBL_SOURCE' => 'مصدر:' ,
   'LBL_PRODUCT_CATEGORY' => 'فئة:' ,
   'LBL_CREATED_BY' => 'أنشأه:' ,
   'LBL_DATE_CREATED' => 'إنشاء تاريخا:' ,
   'LBL_MODIFIED_BY' => 'تم تعديله آخر مرة بواسطة:' ,
   'LBL_DATE_LAST_MODIFIED' => 'تاريخ التعديل:' ,
   'LBL_LIST_EMAIL_ADDRESS' => 'عنوان البريد الإلكتروني' ,
   'LBL_LIST_CONTACT_NAME' => 'اسم جهة الإتصال' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_PHONE' => 'تليفون' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذا الاتصال من هذا المشكلة؟' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'متتبع المشكلات' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_ACCOUNTS_SUBPANEL_TITLE' => 'حسابات' ,
   'LBL_CASES_SUBPANEL_TITLE' => 'حالات' ,
   'LBL_SYSTEM_ID' => 'هوية النظام' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'LNK_BUG_REPORTS' => 'تقارير المشكلات' );

?>
