<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/TimePeriods/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_NAME' => 'ID' ,
   'LBL_TP_NAME' => 'فترة زمنية' ,
   'LBL_TP_START_DATE' => 'تاريخ البدء' ,
   'LBL_TP_END_DATE' => 'تاريخ الانتهاء' ,
   'LBL_TP_FISCAL_YEAR' => 'السنة المالية' ,
   'LBL_MODULE_NAME' => 'فترات زمنية' ,
   'LBL_MODULE_TITLE' => 'الفترة الزمنية: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في الفترة الزمنية' ,
   'LBL_LIST_FORM_TITLE' => 'فترات زمنية' ,
   'LBL_NEW_FORM_TITLE' => 'فترة زمنية جديدة' ,
   'LNK_NEW_TIMEPERIOD' => 'إنشئ فترة زمنية' ,
   'LNK_TIMEPERIOD_LIST' => 'فترات زمنية' ,
   'LBL_TP_IS_FISCAL_YEAR' => 'هل هي سنة مالية؟' ,
   'LBL_PARENT_ID' => 'الهوية الرئيسية' ,
   'LBL_CREATED_BY' => 'أنشأه' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_DELETED' => 'تم الحذف' ,
   'LBL_SEARCH_TP_NAME' => 'فترة زمنية' ,
   'LBL_SEARCH_TP_START_DATE' => 'تاريخ البدء' ,
   'LBL_SEARCH_TP_END_DATE' => 'تاريخ الانتهاء' ,
   'ERR_TIME_PERIOD_DATE_RANGE' => 'تاريخ الإنتهاء للفترة الزمنية يجب أن يكون متأخر عن تاريخ البدء' );

?>
