<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProspectLists/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'القوائم المستهدفة' ,
   'LBL_MODULE_ID' => 'قائمة العملاء المتوقعين' ,
   'LBL_MODULE_TITLE' => 'قوائم العناصر المستهدفة: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في قوائم العناصر المستهدفة' ,
   'LBL_LIST_FORM_TITLE' => 'القوائم المستهدفة' ,
   'LBL_PROSPECT_LIST_NAME' => 'اسم:' ,
   'LBL_NAME' => 'اسم: ' ,
   'LBL_ENTRIES' => 'المدخلات الكلية: ' ,
   'LBL_LIST_PROSPECT_LIST_NAME' => 'القائمة المستهدفة' ,
   'LBL_LIST_ENTRIES' => 'الأهداف في القائمة' ,
   'LBL_LIST_DESCRIPTION' => 'وصف' ,
   'LBL_LIST_TYPE_NO' => 'النوع' ,
   'LBL_LIST_END_DATE' => 'تاريخ الانتهاء' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_MODIFIED' => 'عدّله: ' ,
   'LBL_CREATED' => 'أنشأه: ' ,
   'LBL_TEAM' => 'فريق: ' ,
   'LBL_ASSIGNED_TO' => 'مكلف به: ' ,
   'LBL_DESCRIPTION' => 'وصف: ' ,
   'LNK_NEW_CAMPAIGN' => 'إنشاء حملة' ,
   'LNK_CAMPAIGN_LIST' => 'حملات' ,
   'LNK_NEW_PROSPECT_LIST' => 'إنشاء القائمة المستهدفة' ,
   'LNK_PROSPECT_LIST_LIST' => 'القوائم المستهدفة' ,
   'LBL_MODIFIED_BY' => 'عدّله: ' ,
   'LBL_CREATED_BY' => 'أنشأه: ' ,
   'LBL_DATE_CREATED' => 'تاريخ الإنشاء: ' ,
   'LBL_DATE_LAST_MODIFIED' => 'تاريخ التعديل: ' ,
   'LNK_NEW_PROSPECT' => 'إنشاء هدفا' ,
   'LNK_PROSPECT_LIST' => 'أهداف' ,
   'LBL_PROSPECT_LISTS_SUBPANEL_TITLE' => 'القوائم المستهدفة' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_LEADS_SUBPANEL_TITLE' => 'عملاء متوقعين' ,
   'LBL_PROSPECTS_SUBPANEL_TITLE' => 'أهداف' ,
   'LBL_COPY_PREFIX' => 'نسخة من' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'المستخدمين' ,
   'LBL_TYPE' => 'النوع' ,
   'LBL_LIST_TYPE' => 'النوع:' ,
   'LBL_LIST_TYPE_LIST_NAME' => 'النوع' ,
   'LBL_NEW_FORM_TITLE' => 'قائمة عناصر مستهدفة جديدة' ,
   'LBL_MARKETING_MESSAGE' => 'رسالة تسويق بريدية' ,
   'LBL_DOMAIN_NAME' => 'اسم نطاق' ,
   'LBL_DOMAIN' => 'لا توجد رسائل بريد إلكتروني على النطاق:' ,
   'LBL_LIST_PROSPECTLIST_NAME' => 'اسم' );

?>
