<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Accounts/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'حسابات' ,
   'LBL_MODULE_TITLE' => 'الحسابات: الرئيسية' ,
   'LBL_HOMEPAGE_TITLE' => 'الحسابات' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في الحسابات' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الحسابات' ,
   'LBL_VIEW_FORM_TITLE' => 'مطالعة الحساب' ,
   'LBL_NEW_FORM_TITLE' => 'حساب جديد' ,
   'LBL_MEMBER_ORG_FORM_TITLE' => 'المنظمات الأعضاء' ,
   'LBL_BUG_FORM_TITLE' => 'حسابات' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_CITY' => 'مدينة' ,
   'LBL_LIST_WEBSITE' => 'موقع إنترنت' ,
   'LBL_LIST_STATE' => 'محافظة' ,
   'LBL_LIST_PHONE' => 'تليفون' ,
   'LBL_LIST_EMAIL_ADDRESS' => 'عنوان البريد الإلكتروني' ,
   'LBL_LIST_CONTACT_NAME' => 'اسم جهة الإتصال' ,
   'LBL_BILLING_ADDRESS_STREET_2' => 'عنوان التحصيل 1' ,
   'LBL_BILLING_ADDRESS_STREET_3' => 'عنوان التحصيل 2' ,
   'LBL_BILLING_ADDRESS_STREET_4' => 'عنوان التحصيل 3' ,
   'LBL_SHIPPING_ADDRESS_STREET_2' => 'عنوان الشحن 1' ,
   'LBL_SHIPPING_ADDRESS_STREET_3' => 'عنوان الشحن 2' ,
   'LBL_SHIPPING_ADDRESS_STREET_4' => 'عنوان الشحن 3' ,
   'LBL_PARENT_ACCOUNT_ID' => 'إسم الحساب المحتوي' ,
   'LBL_CAMPAIGN_ID' => 'هوية الحملة' ,
   'db_name' => 'LBL_LIST_ACCOUNT_NAME' ,
   'db_website' => 'LBL_LIST_WEBSITE' ,
   'db_billing_address_city' => 'LBL_LIST_CITY' ,
   'LBL_ACCOUNT_INFORMATION' => 'معلومات الحساب' ,
   'LBL_ACCOUNT' => 'حساب:' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_PHONE' => 'تليفون:' ,
   'LBL_PHONE_ALT' => 'التليفون البديل:' ,
   'LBL_WEBSITE' => 'موقع إنترنت:' ,
   'LBL_FAX' => 'فاكس:' ,
   'LBL_TICKER_SYMBOL' => 'رمز المؤشر:' ,
   'LBL_OTHER_PHONE' => 'تليفون آخر:' ,
   'LBL_ANY_PHONE' => 'أي تليفون:' ,
   'LBL_MEMBER_OF' => 'عضو من:' ,
   'LBL_PHONE_OFFICE' => 'تليفون المكتب:' ,
   'LBL_PHONE_FAX' => 'التليفون الفاكس:' ,
   'LBL_EMAIL' => 'بريد الكتروني:' ,
   'LBL_EMPLOYEES' => 'موظفون:' ,
   'LBL_OTHER_EMAIL_ADDRESS' => 'بريد إلكتروني آخر:' ,
   'LBL_ANY_EMAIL' => 'أي بريد إلكتروني:' ,
   'LBL_OWNERSHIP' => 'ملكية:' ,
   'LBL_RATING' => 'تقييم:' ,
   'LBL_INDUSTRY' => 'صناعة:' ,
   'LBL_SIC_CODE' => 'كود التصنيف الصناعي الموحد:' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_ANNUAL_REVENUE' => 'عائد سنوي:' ,
   'LBL_ADDRESS_INFORMATION' => 'بيانات العنوان' ,
   'LBL_BILLING_ADDRESS' => 'عنوان التحصيل:' ,
   'LBL_BILLING_ADDRESS_STREET' => 'إسم الشارع في عنوان التحصيل:' ,
   'LBL_BILLING_ADDRESS_CITY' => 'إسم المدينة في عنوان التحصيل:' ,
   'LBL_BILLING_ADDRESS_STATE' => 'إسم المحافظة في عنوان التحصيل:' ,
   'LBL_BILLING_ADDRESS_POSTALCODE' => 'الرمز البريدي في عنوان التحصيل:' ,
   'LBL_BILLING_ADDRESS_COUNTRY' => 'إسم البلد في عنوان التحصيل:' ,
   'LBL_SHIPPING_ADDRESS_STREET' => 'إسم الشارع في عنوان الشحن:' ,
   'LBL_SHIPPING_ADDRESS_CITY' => 'إسم المدينة في عنوان الشحن:' ,
   'LBL_SHIPPING_ADDRESS_STATE' => 'إسم المحافظة في عنوان الشحن:' ,
   'LBL_SHIPPING_ADDRESS_POSTALCODE' => 'الرمز البريدي في عنوان الشحن:' ,
   'LBL_SHIPPING_ADDRESS_COUNTRY' => 'إسم البلد في عنوان الشحن:' ,
   'LBL_SHIPPING_ADDRESS' => 'عنوان الشحن:' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل:' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل:' ,
   'LBL_ANY_ADDRESS' => 'أي عنوان:' ,
   'LBL_CITY' => 'مدينة:' ,
   'LBL_STATE' => 'محافظة:' ,
   'LBL_POSTAL_CODE' => 'الرمز البريدي:' ,
   'LBL_COUNTRY' => 'بلد:' ,
   'LBL_PUSH_CONTACTS_BUTTON_TITLE' => 'نسخ...' ,
   'LBL_PUSH_CONTACTS_BUTTON_LABEL' => 'نسخ إلى جهات الإتصال' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'NTC_COPY_BILLING_ADDRESS' => 'نسخ عنوان التحصيل إلى عنوان الشحن' ,
   'NTC_COPY_SHIPPING_ADDRESS' => 'نسخ عنوان الشحن إلى عنوان اتحصيل' ,
   'NTC_REMOVE_MEMBER_ORG_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذا السجل كمنظمة عضو؟' ,
   'NTC_REMOVE_ACCOUNT_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذا السجل؟' ,
   'LBL_DUPLICATE' => 'إحتمالية حساب متكرر' ,
   'MSG_SHOW_DUPLICATES' => 'إنشاء هذا الحساب من الممكن أن يكون تكرارا جزئيا للحساب. من الممكن إما أن نتقر على أنشئ حسابا لكي تستكمل إنشاء هذا الحساب الجديد بالبيانات المدخلة مسبقا أو يمكنك أن تنقر إلغي' ,
   'MSG_DUPLICATE' => 'إنشاء هذا الحساب من الممكن أن يكون تكرارا جزئيا للحساب. من الممكن إما أن تختار حسابا من المدرجة بأسفل أو يمكنك نقر أنشئ حسابا  لكي تستكمل إنشاء هذا الحساب الجديد بالبيانات المدخلة مسبقا' ,
   'LNK_NEW_ACCOUNT' => 'إنشاء حساب' ,
   'LNK_ACCOUNT_REPORTS' => 'تقارير الحساب' ,
   'LNK_ACCOUNT_LIST' => 'حسابات' ,
   'LBL_INVITEE' => 'جهات إتصال' ,
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم السجل للتمكن من حذف الحساب' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'LBL_SAVE_ACCOUNT' => 'حفظ الحساب' ,
   'ACCOUNT_REMOVE_PROJECT_CONFIRM' => 'هل أن متأظكد من أنك تريد حذف هذا الحساب من المشروع' ,
   'LBL_USERS_ASSIGNED_LINK' => 'المستخدمين المعينين' ,
   'LBL_USERS_MODIFIED_LINK' => 'المستخدمين المكلفبن' ,
   'LBL_USERS_CREATED_LINK' => 'منشأة بواسطة المستخدمين' ,
   'LBL_TEAMS_LINK' => 'فرق' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'حسابات' ,
   'LBL_PRODUCTS_TITLE' => 'منتجات' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_MEMBER_ORG_SUBPANEL_TITLE' => 'المنظمات الأعضاء' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_OPPORTUNITIES_SUBPANEL_TITLE' => 'فرص بيع' ,
   'LBL_LEADS_SUBPANEL_TITLE' => 'عملاء متوقعين' ,
   'LBL_CASES_SUBPANEL_TITLE' => 'حالات' ,
   'LBL_PRODUCTS_SUBPANEL_TITLE' => 'منتجات' ,
   'LBL_QUOTES_SUBPANEL_TITLE' => 'إقتباسات' ,
   'LBL_CONTRACTS' => 'العقود' ,
   'LBL_CONTRACTS_SUBPANEL_TITLE' => 'العقود' ,
   'LBL_BUGS_SUBPANEL_TITLE' => 'مشكلات' ,
   'LBL_PROJECTS_SUBPANEL_TITLE' => 'مشروعات' ,
   'LBL_ASSIGNED_TO_NAME' => 'إسم المستخدم المكلفبن:' ,
   'LBL_DEFAULT' => 'أشكال الإضطلاع' ,
   'LBL_CHARTS' => 'رسومات بيانية' ,
   'LBL_UTILS' => 'إمكانيات مساعدة' ,
   'LBL_MISC' => 'متنوع' );

?>
