<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/UpgradeWizard/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'DESC_MODULES_INSTALLED' => 'الوحدات التالية نم تثبيتها:' ,
   'DESC_MODULES_QUEUED' => 'الوحدات التالية جاهزة للتثبيت:' ,
   'ERR_UW_CANNOT_DETERMINE_GROUP' => 'لا يمكن تحديد مجموعة' ,
   'ERR_UW_CANNOT_DETERMINE_USER' => 'لا يمكن تحديد مالك' ,
   'ERR_UW_CONFIG_WRITE' => 'خطأ في تحديث \"config.php\" بمعلومات النسخة الجديدة.' ,
   'ERR_UW_CONFIG' => 'من فضلك اجعل ملف \"config.php\" قابلا للكتابة وأعد تحميل هذه الصفحة.' ,
   'ERR_UW_DIR_NOT_WRITABLE' => 'الدليل غير قابل للكتابة' ,
   'ERR_UW_FILE_NOT_COPIED' => 'الملف غير منسوخ' ,
   'ERR_UW_FILE_NOT_DELETED' => 'مشكلة في إزالة الحزمة ' ,
   'ERR_UW_FILE_NOT_READABLE' => 'لا يمكن قراءة الملف' ,
   'ERR_UW_FILE_NOT_WRITABLE' => 'لا يمكن إزالة الملف أو الكتابة له' ,
   'ERR_UW_FLAVOR_2' => 'تحديث الطابع: ' ,
   'ERR_UW_FLAVOR' => 'طابع شوجر سي آر إم: ' ,
   'ERR_UW_LOG_FILE_UNWRITABLE' => 'لا يمكن إنشاء \"upgradeWizard.log\" أو الكتابة إليه. من فضلك أصلح التصريحات في دليل شوجار سي آر إم خاصتك.' ,
   'ERR_UW_MYSQL_VERSION' => 'شوجار سي آر إم يتطلب نسخة ماي سكويل 4.1.2 أو أحدث. عثر عليها.: ' ,
   'ERR_UW_NO_FILE_UPLOADED' => 'من فضلك حدد ملفا وحاول مرة أخرى' ,
   'ERR_UW_NO_FILES' => 'وقع خطأ، لم يعثر على ملفات لتفقدها.' ,
   'ERR_UW_NO_MANIFEST' => 'الملف المضغوط يفتقد إلى ملف manifest.php. لا يمكن إستكمال العملية' ,
   'ERR_UW_NO_VIEW' => 'تم تحديد مطالعة سليمة.' ,
   'ERR_UW_NO_VIEW2' => 'الرؤية لم يتم تعريفها. من فضلك اذهب لرئيسية الإدارة للإبحار إلى هذه الصفحة.
' ,
   'ERR_UW_NOT_VALID_UPLOAD' => 'الملف المرفوع غير صالح' ,
   'ERR_UW_NO_CREATE_TMP_DIR' => 'لم يمكن إنشاء المسار الإحتياطي. تأكد من سماحيات الملف' ,
   'ERR_UW_ONLY_PATCHES' => 'يمكنك فقط رفع ملفات تصحيح الأخطاء من خلال هذه الصفحة' ,
   'ERR_UW_PREFLIGHT_ERRORS' => 'عثر على مشكلات أثناء فحص ما قبل الإقلاع' ,
   'ERR_UW_UPLOAD_ERR' => 'وجد خطأ عند رفع الملف، من فضلك حاول مرة أخرى!' ,
   'ERR_UW_VERSION' => 'نسخة نظام شوجار سي آر إم: ' ,
   'ERR_UW_WRONG_TYPE' => 'هذه الصفحة ليست للتشغيل ' ,
   'LBL_BUTTON_BACK' => 'رجوع' ,
   'LBL_BUTTON_CANCEL' => 'إلغاء' ,
   'LBL_BUTTON_DELETE' => 'إلغِ الحزمة' ,
   'LBL_BUTTON_DONE' => 'تم' ,
   'LBL_BUTTON_INSTALL' => 'ترقية ما قبل الإقلاع' ,
   'LBL_BUTTON_NEXT' => 'التالي' ,
   'LBL_BUTTON_RECHECK' => 'أعد التحقق' ,
   'LBL_UPLOAD_UPGRADE' => 'الرفع والتحديث: ' ,
   'LBL_UW_BACKUP_FILES_EXIST_TITLE' => 'النسخة الإحتياطية من الملف' ,
   'LBL_UW_BACKUP_FILES_EXIST' => 'الملفات التي لها احتياطي من هذه الترقية يمكن العثور عليها في' ,
   'LBL_UW_BACKUP' => 'احتياطي الملف' ,
   'LBL_UW_CANCEL_DESC' => 'تم التراجع عن مرشد الترقية. كل الملفات المؤقتة والملف المضغوط المرفوع تم إلغاؤها.<BR>
اضغط \"التالي\" لإعادة تشغيل مرشد الترقية.' ,
   'LBL_UW_CHARSET_SCHEMA_CHANGE' => 'تغييرات في تفريعة ترميز الحروف' ,
   'LBL_UW_CHECK_ALL' => 'النشر على الكل' ,
   'LBL_UW_CHECKLIST' => 'خطوات الترقية' ,
   'LBL_UW_COMMIT_ADD_TASK_DESC_1' => 'النسخ الاحتياطية من الملفات التي حلت محلها ملفات في الدليل الآتي' ,
   'LBL_UW_COMMIT_ADD_TASK_DESC_2' => 'ادمج الملفات الآتية آليا' ,
   'LBL_UW_COMMIT_ADD_TASK_NAME' => 'عملية الدمج: ادمج الملفات يدويا' ,
   'LBL_UW_COMMIT_ADD_TASK_OVERVIEW' => 'رجاء إستعمل أيّ طريقة مألوفة جدا إليك مهما كانت لدمج هذه الملفات. وحتى يكتمل هذا، تثبيت شوجر سي آر إم سوف يكون غير مؤكد، والتحديث ليس كاملا' ,
   'LBL_UW_COMPLETE' => 'إكتمال' ,
   'LBL_UW_COMPLIANCE_ALL_OK' => 'تمت تلبية كل متطلبات إعدادات النظام' ,
   'LBL_UW_COMPLIANCE_CALLTIME' => '\'PHP Setting: Call Time Pass By Reference\'' ,
   'LBL_UW_COMPLIANCE_CURL' => 'وحدة cURL' ,
   'LBL_UW_COMPLIANCE_IMAP' => 'وحدة IMAP' ,
   'LBL_UW_COMPLIANCE_MBSTRING' => 'وحدة MBStrings' ,
   'LBL_UW_COMPLIANCE_MEMORY' => 'ضبط بي إتش بي: حد ذاكرة' ,
   'LBL_UW_COMPLIANCE_MSSQL_MAGIC_QUOTES' => '\'MS SQL Server & PHP Magic Quotes GPC\'' ,
   'LBL_UW_COMPLIANCE_MYSQL' => 'أقل نسخة MySQL' ,
   'LBL_UW_COMPLIANCE_PHP_INI' => 'موضع/تحديد موضع \"php.ini\"' ,
   'LBL_UW_COMPLIANCE_PHP_VERSION' => 'أقل نسخة بي إتش بي' ,
   'LBL_UW_COMPLIANCE_SAFEMODE' => 'ضبط بي إتش بي: نمط تشغيل آمن' ,
   'LBL_UW_COMPLIANCE_TITLE' => 'فحص إعدادات الجهاز الخادم' ,
   'LBL_UW_COMPLIANCE_TITLE2' => 'الإعدادات المكتشفة' ,
   'LBL_UW_COMPLIANCE_XML' => 'معالجة XML ' ,
   'LBL_UW_COPIED_FILES_TITLE' => 'نسخت الملفات بنجاح' ,
   'LBL_UW_CUSTOM_TABLE_SCHEMA_CHANGE' => 'تغييرات مخصوصة في تفريعة الجداول' ,
   'LBL_UW_DB_CHOICE1' => 'مرشد التحديث يشغل SQL' ,
   'LBL_UW_DB_CHOICE2' => 'إستعلامات SQLيدوية' ,
   'LBL_UW_DB_INSERT_FAILED' => '\'INSERT failed - compared results differ\'' ,
   'LBL_UW_DB_ISSUES_PERMS' => 'صلاحيات قاعدة البيانات' ,
   'LBL_UW_DB_ISSUES' => 'مشكلات قاعدة البيانات' ,
   'LBL_UW_DB_METHOD' => 'طريقة تحديث قاعدة البيانات' ,
   'LBL_UW_DB_NO_ADD_COLUMN' => '\'ALTER TABLE [table] ADD COLUMN [column]\'' ,
   'LBL_UW_DB_NO_CHANGE_COLUMN' => '\'ALTER TABLE [table] CHANGE COLUMN [column]\'' ,
   'LBL_UW_DB_NO_CREATE' => '\'CREATE TABLE [table]\'' ,
   'LBL_UW_DB_NO_DELETE' => '\'DELETE FROM [table]\'' ,
   'LBL_UW_DB_NO_DROP_COLUMN' => '\'ALTER TABLE [table] DROP COLUMN [column]\'' ,
   'LBL_UW_DB_NO_DROP_TABLE' => '\'DROP TABLE [table]\'' ,
   'LBL_UW_DB_NO_ERRORS' => 'كل الصلاحيات متاحة' ,
   'LBL_UW_DB_NO_INSERT' => '\'INSERT INTO [table]\'' ,
   'LBL_UW_DB_NO_SELECT' => '\'SELECT [x] FROM [table]\'' ,
   'LBL_UW_DB_NO_UPDATE' => '\'UPDATE [table]\'' ,
   'LBL_UW_DB_PERMS' => 'صلاحية ضرورية' ,
   'LBL_UW_DESC_MODULES_INSTALLED' => 'تم تسجيل التحديثات الآتية:' ,
   'LBL_UW_END_DESC' => 'تهانينا، تحديث نظامك الآن.' ,
   'LBL_UW_END_DESC2' => 'لو كنت قد اخترت أن تُجري يدويا أي خطوات مثل عمليات دمج ملفات أو عمليات بحث سكويل، من فضلك افعل هذا الآن. سيكون نظامك في حالة غير مستقرة حتى تكتمل تلك الخطوات.
' ,
   'LBL_UW_END_LOGOUT' => 'الرجاء تسجيل الخروج من الحساب الخاص بك إذا كنت تنوي تحديث أعلى من مستوى تحديث التصليحات' ,
   'LBL_UW_END_LOGOUT2' => 'تسجيل الخروج' ,
   'LBL_UW_REPAIR_INDEX' => 'لتحسينات أداء قاعدة البيانات، من فضلك شغل نص فهرس الإصلاح.
' ,
   'LBL_UW_FILE_DELETED' => ' تم حذفه.' ,
   'LBL_UW_FILE_GROUP' => 'مجموعة' ,
   'LBL_UW_FILE_ISSUES_PERMS' => 'تصريحات الملف' ,
   'LBL_UW_FILE_ISSUES' => 'مشكلات الملف' ,
   'LBL_UW_FILE_NEEDS_DIFF' => 'الملف يحتاج عمل الإختلافات يدويا' ,
   'LBL_UW_FILE_NO_ERRORS' => 'كل الملفات قابلة للكتابة' ,
   'LBL_UW_FILE_OWNER' => 'المالك' ,
   'LBL_UW_FILE_PERMS' => 'سماحيات' ,
   'LBL_UW_FILE_UPLOADED' => ' تم رفعه' ,
   'LBL_UW_FILE' => 'اسم الملف' ,
   'LBL_UW_FILES_QUEUED' => 'الترقيات التالية جاهزة لتثبيتها:' ,
   'LBL_UW_FILES_REMOVED' => 'الملفات التالية ستتم إزالتها من النظام:' ,
   'LBL_UW_FROZEN' => 'الخطوات المطلوبة لابد أن تكتمل قبل الاستمرار.' ,
   'LBL_UW_HIDE_DETAILS' => 'أخف التفاصيل' ,
   'LBL_UW_IN_PROGRESS' => 'جاري التنفيذ' ,
   'LBL_UW_INCLUDING' => 'تحتوي على' ,
   'LBL_UW_INCOMPLETE' => 'غير مكتمل' ,
   'LBL_UW_INSTALL' => 'تثبيت الملف' ,
   'LBL_UW_MANUAL_MERGE' => 'دمج الملف' ,
   'LBL_UW_MODULE_READY_UNINSTALL' => 'الوحدة جاهزة لإلغاء تثبيتها أضغط \"نفذ\" لإستكمال الإلغاء' ,
   'LBL_UW_MODULE_READY' => 'الوحدة جاهزة لتثبيتها أضغط \"نفذ\" لإستكمال التثبيت' ,
   'LBL_UW_NO_INSTALLED_UPGRADES' => 'لا توجد ترقيات مسجلة تم الكشف عنها.' ,
   'LBL_UW_NONE' => 'لاشئ' ,
   'LBL_UW_NOT_AVAILABLE' => 'غير متاح' ,
   'LBL_UW_OVERWRITE_DESC' => 'سوف يتم الكتابة على جميع الملفات الموجودة - متضمنة كل تخصيصات الكود وتغييرات القوالب التي قمت بها. هل تريد الإستكمال بالفعل؟' ,
   'LBL_UW_OVERWRITE_FILES_CHOICE1' => 'إحلال على كل الملفات' ,
   'LBL_UW_OVERWRITE_FILES_CHOICE2' => 'دمج يدوي - احتفاظ بالكل' ,
   'LBL_UW_OVERWRITE_FILES' => 'طريقة الدمج' ,
   'LBL_UW_PATCH_READY' => 'االتصليح جاهز للإستكمال. انقر \"نفذ\" بأسفل لإستكمال عملية التحديث' ,
   'LBL_UW_PATCH_READY2' => '<h1>ملحوظة: تم إيجاد تخصيص لتخطيط الشكل</h1>
<br><br>
الملفات التالية لها حقول جديدة أو تخطيط شكل معدل تم تكبيقها من خلال الاستوديو. الإصلاح الذي أنت بصدد إستخدامه يحتوي أيضا على تعديل للملفات. لكل ملف يمكنك:
<br>
<ul>
<li>(إفتراضي) يمكنك الإحتفاظ بإصدارك بعدم تأشير هذا العنصر. سوف يتم تجاهل تأثير هذا الإصلاح.</li>

<li>قبول تحديث الملفات من خلال إختيار العنصر. تخطيط الشكل خاصتك ربما يحتاج إلى إعادة بناء من خلال الإستوديو</li>
</ul>' ,
   'LBL_UW_PREFLIGHT_ADD_TASK' => 'إنشاء عنصر خاص بمهمة للدمج اليدوي؟' ,
   'LBL_UW_PREFLIGHT_COMPLETE' => 'فحص قبل الإقلاع' ,
   'LBL_UW_PREFLIGHT_DIFF' => 'متميز ' ,
   'LBL_UW_PREFLIGHT_EMAIL_REMINDER' => 'أرسل لنفسك بالبريد الإلكتروني تذكيرا بدمج يدوي؟' ,
   'LBL_UW_PREFLIGHT_FILES_DESC' => 'الملفات المدرجة بأسفل تم تعديلها. أزل التأشير العناصر التي تتطلب دمج يدوي. أي عناصر لتغيير الشكل الخارجي غير مؤشر عليها أوتوماتيكيا، قم بالتأشير على أي من المفترض الكتابة عليه' ,
   'LBL_UW_PREFLIGHT_NO_DIFFS' => 'غير مطلوب عمليات دمج يدوية لملفات' ,
   'LBL_UW_PREFLIGHT_NOT_NEEDED' => 'لا توجد حاجة إليه' ,
   'LBL_UW_PREFLIGHT_PRESERVE_FILES' => 'ملفات محتفظ بها آليا:' ,
   'LBL_UW_PREFLIGHT_TESTS_PASSED' => 'كل اختبارات ما قبل الإقلاع مرت. اضغط على \"التالي\" لتنفيذ هذه التغييرات.' ,
   'LBL_UW_PREFLIGHT_TOGGLE_ALL' => 'تثبيت كل الملفات' ,
   'LBL_UW_REBUILD_TITLE' => 'إعادة بناء النتيجة' ,
   'LBL_UW_SCHEMA_CHANGE' => 'تغييرات التفريعة' ,
   'LBL_UW_SHOW_COMPLIANCE' => 'اعرض الإعدادات المكشوف عنها' ,
   'LBL_UW_SHOW_DB_PERMS' => 'اعرض تصريحات قاعدة البيانات المفتقدة' ,
   'LBL_UW_SHOW_DETAILS' => 'اعرض التفاصيل' ,
   'LBL_UW_SHOW_DIFFS' => 'اعرض الملفات التي تتطلب دمجا يدويا' ,
   'LBL_UW_SHOW_NW_FILES' => 'أظهر الملفات ذات السماحيات السيئة' ,
   'LBL_UW_SHOW_SCHEMA' => 'أظهر تغييرات التفريعة في الكود' ,
   'LBL_UW_SHOW_SQL_ERRORS' => 'أظهر الإستعلامات السيئة' ,
   'LBL_UW_SHOW' => 'إظهار' ,
   'LBL_UW_SKIPPED_FILES_TITLE' => 'الملافات المتجاوزة' ,
   'LBL_UW_SKIPPING_FILE_OVERWRITE' => 'تفقد عندنا يكون سكويل تم تشغيله يدويا' ,
   'LBL_UW_SQL_RUN' => 'تأكد حينما يتم التشغيل اليدوي ل SQL' ,
   'LBL_UW_START_DESC' => 'مرحبا بك في مرشد تحديث شوجر سي آر إم. لقد تم تصميمه لمساعدة الإدارة لتحديث نماذجهم من شوجر سي آر إم. من فضلك أتبع التعليمات المعطاة بحذر' ,
   'LBL_UW_START_DESC2' => 'يوصى بشدة بإجراء التحديث على خادم عليه نسخة من النظام العامل. من فضلك خذ نسخة إحتياطية من قاعدة البيانات وملفات النظام (كل الملفات حافظة شوجر) قبل القيام بهذه العملية - الوقاية دائما خير من العلاج' ,
   'LBL_UW_START_UPGRADED_UW_DESC' => 'مرشد الترقية الجديدة سيتابع عملية الترقية. من فضلك واصل ترقيتك.
' ,
   'LBL_UW_START_UPGRADED_UW_TITLE' => 'أهلا في مرشد الترقية الجديدة' ,
   'LBL_UW_SYSTEM_CHECK_CHECKING' => 'جاري التأشير الآن، من فضلك انتظر. ربما يأخذ هذا ما يصل إلى 30 ثانية.' ,
   'LBL_UW_SYSTEM_CHECK_FILE_CHECK_START' => 'جاري إيجاد كل الملفات وثيقة الصلة لتفقدها.' ,
   'LBL_UW_SYSTEM_CHECK_FILES' => 'ملفات' ,
   'LBL_UW_SYSTEM_CHECK_FOUND' => 'وجدت' ,
   'LBL_UW_TITLE_CANCEL' => 'إلغاء' ,
   'LBL_UW_TITLE_COMMIT' => 'إحذف التحديث' ,
   'LBL_UW_TITLE_END' => 'إستجواب' ,
   'LBL_UW_TITLE_PREFLIGHT' => 'فحص قبل الإقلاع' ,
   'LBL_UW_TITLE_START' => 'الأول' ,
   'LBL_UW_TITLE_SYSTEM_CHECK' => 'إختبار النظام' ,
   'LBL_UW_TITLE_UPLOAD' => 'أرفع التحديث' ,
   'LBL_UW_TITLE' => 'حوار التحديث' ,
   'LBL_UW_UNINSTALL' => 'تراجع عن التركيب' ,
   'ERR_UW_PHP_FILE_ERRORS' => array (
      '1' => 'الملف المرفوع يتعدى التوجيه  upload_max_filesize الموجود في  php.ini' ,
      '2' => 'الملف المرفوع يتعدى التوجيه MAX_FILE_SIZE   المحدد في استمارة  HTML' ,
      '3' => 'الملف المرفوع تم رفع جزء منه فقط' ,
      '4' => 'لم يتم رفع أي ملفات' ,
      '5' => 'خطأ غير معروف' ,
      '6' => 'المجلد الإحتياطي مفقود' ,
      '7' => 'فشل في كتابة الملف على القرص' ,
      '8' => 'توقف رفع الملف بسبب الامتداد'   ));

?>
