<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Quotas/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'حصص' ,
   'LBL_MODULE_TITLE' => 'الحصص: الرئيسية' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الحصص' ,
   'LBL_QUOTA' => 'حصه:' ,
   'LBL_DIRECT_REPORT' => 'تقرير مباشر' ,
   'LBL_QUOTA_AMOUNT' => 'كمية الحصة' ,
   'LBL_LAST_MODIFIED' => 'آخر مرة تعديل' ,
   'LBL_COMMIT_STATUS' => 'نفذ الحالة' ,
   'LBL_COMMITTED' => 'كُلف به' ,
   'LBL_NOT_COMMITTED' => 'مؤجلة' ,
   'LNK_FORECAST_LIST' => 'توقع' ,
   'LNK_FORECAST_HISTORY' => 'توقع المحفوظات' ,
   'LNK_UPD_FORECAST' => 'توقع ورقة العمل' ,
   'LNK_QUOTA' => 'حصص' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_TIME_PERIOD' => 'فترة زمنية:' ,
   'LBL_SELECT_TIME_PERIOD' => 'أختر فترة زمنية....' ,
   'LBL_AMOUNT' => 'كمية:' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LBL_COMMIT' => 'نفذ:' ,
   'LBL_SELECT_USER' => 'أختر مستخدم.....' ,
   'LBL_NO_QUOTAS_TIMEPERIOD' => 'لم يتم إدخال أي حصص لتقاريرك المباشرة في هذه الفترة الزمنية' ,
   'LBL_CURRENT_USER_QUOTA' => 'الحصة المخصصة لك في هذه الفترة الزمنية  هي: ' ,
   'LBL_CURRENT_USER_NO_QUOTA' => 'لم يتم تخصيص حصه لك في هذه الفترة الزمنية' ,
   'LBL_USER_ID' => 'هوية المستخدم' );

?>
