<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/MailMerge/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_STEP_1' => 'خطوة 1: أختر الوحدة والقالب' ,
   'LBL_MAILMERGE_MODULE' => 'أختر وحدة: ' ,
   'LBL_MAILMERGE_SELECTED_MODULE' => 'الوحدة المختارة: ' ,
   'LBL_MAILMERGE_TEMPLATES' => 'اختر قالبا: ' ,
   'LBL_STEP_2' => 'خطوة 2: اختر عناصر لدمجها' ,
   'LBL_MAILMERGE_OBJECTS' => 'اختر عناصر: ' ,
   'LBL_STEP_3' => 'حدد إصحاب جهة الإتصال' ,
   'LBL_STEP_4' => 'راجع وأكمل' ,
   'LBL_SELECTED_MODULE' => 'الوحدة المختارة: ' ,
   'LBL_SELECTED_TEMPLATE' => 'القالب المختار: ' ,
   'LBL_SELECTED_ITEMS' => 'العناصر المختارة: ' ,
   'LBL_STEP_5' => 'دمج البريد اكتمل' ,
   'LBL_MERGED_FILE' => 'الملف المدمج: ' ,
   'LNK_NEW_MAILMERGE' => 'ابدأ دمج البريد' ,
   'LNK_UPLOAD_TEMPLATE' => 'ارفع القالب' ,
   'LBL_DOC_NAME' => 'اسم المستند:' ,
   'LBL_FILENAME' => 'اسم الملف:' ,
   'LBL_DOC_VERSION' => 'مراجعة:' ,
   'LBL_DOC_DESCRIPTION' => 'وصف:' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_RELATIONSHIP' => 'حدد علاقة جهة الإتصال' ,
   'LBL_FINISH' => 'ابدأ الدمج' ,
   'LBL_NEXT' => 'التالي>' ,
   'LBL_BACK' => 'السابق <' ,
   'LBL_START' => 'ابدأ من جديد' ,
   'LBL_TEMPLATE_NOTICE' => 'القوالب هي وثائق مايكروسوفت ورد تحتوي على حقول مدمجة قد تم رفعها وحفظها في وحدة الوثائق' ,
   'LBL_CONTAINS_CONTACT_INFO' => 'القالب المختار يحتوي على متعلقات ' ,
   'LBL_ADDIN_NOTICE' => 'هذا يتطلب تثبيت Sugar Mail Merge add-in to Microsoft Word' ,
   'LBL_BROWSER_NOTICE' => 'لابد أن تكون مشغلا لمتصفح إنترنت إكسبلورر 6.0 أو أعلى للقيام بالدمج الفعلي' );

?>
