<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Charts/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_NO_OPPS' => 'رجاء أنشئ بعض الفرص لكي تشاهد رسوم الفرص البيانية' ,
   'LBL_ALL_OPPORTUNITIES' => 'الكمية الكلية للفرص ' ,
   'LBL_CREATED_ON' => 'تم تشغيله آخر مرة في ' ,
   'LBL_DATE_END' => 'تاريخ الانتهاء:' ,
   'LBL_DATE_RANGE_TO' => 'إلى' ,
   'LBL_DATE_RANGE' => 'حدود التاريخ هي' ,
   'LBL_DATE_START' => 'تاريخ البدأ:' ,
   'LBL_EDIT' => 'تحرير' ,
   'LBL_LEAD_SOURCE_BY_OUTCOME_DESC' => 'يظهر كمية الفرص المتراكمة من مصدر العملاء المتوقعين مقارنة بالنتيجة للمستخدمين المختارين. النتيجة مبنية على إما إنتهى بنجاح أو انتهى بفشل أو أي نتيجة أخرى.' ,
   'LBL_LEAD_SOURCE_BY_OUTCOME' => 'كل الفرص مقارنة بمصدر العملاء المتوقعين مقارنة بالنتيجة' ,
   'LBL_LEAD_SOURCE_FORM_DESC' => 'يظهر كمية الفرص المتراكمة من العميل المتوقع للمستخدمين المختارين' ,
   'LBL_LEAD_SOURCE_FORM_TITLE' => 'كل الفرص مقارنة ب العملاء المتوقعين' ,
   'LBL_LEAD_SOURCE_OTHER' => 'غيره' ,
   'LBL_LEAD_SOURCES' => 'العملاء المتوقعين:' ,
   'LBL_MODULE_NAME' => 'لوحة الإحصائيات' ,
   'LBL_MODULE_TITLE' => 'لوحة الإحصائيات: الرئيسية' ,
   'LBL_MONTH_BY_OUTCOME_DESC' => 'يظهر كمية الفرص المتراكمة  حسب الشهور مقارنة بالنتيجة للمستخدمين المختارين حيت أن تاريخ الإغلاق المتوقع ضمن مدى التاريخ المحدد. النتيجة مبنية على إما إنتهى بنجاح أو انتهى بفشل أو أي نتيجة أخرى.' ,
   'LBL_OPP_SIZE' => 'حجم الفرصة في' ,
   'LBL_OPP_THOUSANDS' => 'K' ,
   'LBL_OPPS_IN_LEAD_SOURCE' => 'الفرص حيث مصدر العملاء المتوقعين هو' ,
   'LBL_OPPS_IN_STAGE' => ' حيث مرحلة البع هي' ,
   'LBL_OPPS_OUTCOME' => ' حيث النتيجة هي' ,
   'LBL_OPPS_WORTH' => 'الفرص القيمة' ,
   'LBL_PIPELINE_FORM_TITLE_DESC' => 'يظهر الكميات المتراكمة يالمراحل المختلفة لفرصك حيث تاريخ الإغلاق المتوقع ضمن مدى التاريخ المحدد' ,
   'LBL_CAMPAIGN_ROI_TITLE_DESC' => 'أعرض تجاوب الحملة بترتيب العئد من الأستثمار' ,
   'LBL_REFRESH' => 'تحديث' ,
   'LBL_ROLLOVER_DETAILS' => 'قف على أي شريط لإظهار التفاصيل' ,
   'LBL_ROLLOVER_WEDGE_DETAILS' => 'ف على أي شريط لإظهار التفاصيل' ,
   'LBL_SALES_STAGE_FORM_DESC' => 'يعرض الكميات/الأسعار التراكمية حسب مراحل المبيعات المختارة الخاصة بالمستخدمين المختارين حيث أن تاريخ الإغلاق المتوقع يقع ضمن مدى التاريخ المحدد' ,
   'LBL_SALES_STAGE_FORM_TITLE' => 'رسم خطي لمراحل البيع' ,
   'LBL_SALES_STAGES' => 'مراحل البيع:' ,
   'LBL_TOTAL_PIPELINE' => 'إجمالي الرسم الخطي هو ' ,
   'LBL_USERS' => 'المستخدمين:' ,
   'LBL_YEAR_BY_OUTCOME' => 'الرسم الخطي حسب الشهر مقارنة بالنتيجة' ,
   'LBL_YEAR' => 'سنة:' ,
   'LNK_NEW_ACCOUNT' => 'إنشاء حساب' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_CASE' => 'إنشاء حالة' ,
   'LNK_NEW_CONTACT' => 'إنشاء جهة إتصال' ,
   'LNK_NEW_ISSUE' => 'إخطار بالمشكلة' ,
   'LNK_NEW_LEAD' => 'إدخال عميل متوقع' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_OPPORTUNITY' => 'إنشاء فرصة' ,
   'LNK_NEW_QUOTE' => 'إنشاء اقتباس' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'NTC_NO_LEGENDS' => 'لاشئ' );

?>
