<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SavedSearch/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_TITLE' => 'عمليات البحث المحفوظة' ,
   'LBL_SEARCH_FORM_TITLE' => 'عمليات البحث المحفوظة: بحث' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة عمليات البحث المحفوظة' ,
   'LBL_DELETE_CONFIRM' => 'هل أنت متأكد أنك تريد حذف البحث المحفوظ المختار؟' ,
   'LBL_DELETE_BUTTON_TITLE' => 'احذف هذا البحث المحفوظ' ,
   'LBL_SAVE_BUTTON_TITLE' => 'حفظ البحث الحالي' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_MODULE' => 'وحدة' ,
   'LBL_ORDER_BY_COLUMNS' => 'ترتيب حسب العمود:' ,
   'LBL_DIRECTION' => 'توجيه:' ,
   'LBL_SAVE_SEARCH_AS' => 'حفظ هذا البحث كـ:' ,
   'LBL_SAVE_SEARCH_AS_HELP' => 'يقوم هذا بحفظ إعدادات اطلاعك وأي منقيات في لسان البحث المتقدم.
' ,
   'LBL_PREVIOUS_SAVED_SEARCH' => 'عمليات البحث المحفوظة السابقة:' ,
   'LBL_PREVIOUS_SAVED_SEARCH_HELP' => 'تحرير أو حذف عملية بحث محفوظ حالية' ,
   'LBL_ASCENDING' => 'تصاعدي' ,
   'LBL_DESCENDING' => 'تنازلي' );

?>
