<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Schedulers/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_OOTB_WORKFLOW' => 'مهام سير العملية' ,
   'LBL_OOTB_REPORTS' => 'شغل المهام المجدولة لإنشاؤ التقارير' ,
   'LBL_OOTB_IE' => 'تفقد صندوق البريد  الوارد' ,
   'LBL_OOTB_BOUNCE' => 'شغل حملة البريد الإلكتروني ' ,
   'LBL_OOTB_CAMPAIGN' => 'شغل حملات البريد الجماعية الليلية' ,
   'LBL_OOTB_PRUNE' => 'تقليم قاعدة البيانات على اول الشهر' ,
   'LBL_LIST_JOB_INTERVAL' => 'فترة:' ,
   'LBL_LIST_LIST_ORDER' => 'المجدولات:' ,
   'LBL_LIST_NAME' => 'المجدوِل:' ,
   'LBL_LIST_RANGE' => 'نطاق:' ,
   'LBL_LIST_REMOVE' => 'أزِل:' ,
   'LBL_LIST_STATUS' => 'الحالة:' ,
   'LBL_LIST_TITLE' => 'قائمة الجداول الزمنية:' ,
   'LBL_LIST_EXECUTE_TIME' => 'سيشتغل في:' ,
   'LBL_SUN' => 'أحد' ,
   'LBL_MON' => 'اثنين' ,
   'LBL_TUE' => 'ثلاثاء' ,
   'LBL_WED' => 'أربعاء' ,
   'LBL_THU' => 'خميس' ,
   'LBL_FRI' => 'جمعة' ,
   'LBL_SAT' => 'سبت' ,
   'LBL_ALL' => 'كل يوم' ,
   'LBL_EVERY_DAY' => 'كل يوم ' ,
   'LBL_AT_THE' => 'في الـ ' ,
   'LBL_EVERY' => 'كل ' ,
   'LBL_FROM' => 'من ' ,
   'LBL_ON_THE' => 'في الـ ' ,
   'LBL_RANGE' => 'إلى ' ,
   'LBL_AT' => 'عند ' ,
   'LBL_IN' => 'في ' ,
   'LBL_AND' => 'و ' ,
   'LBL_MINUTES' => 'دقائق ' ,
   'LBL_HOUR' => ' ساعات' ,
   'LBL_HOUR_SING' => ' ساعة' ,
   'LBL_MONTH' => ' شهر' ,
   'LBL_OFTEN' => ' كلما أمكن' ,
   'LBL_MIN_MARK' => ' علامة الدقيقة' ,
   'LBL_MINS' => 'دق' ,
   'LBL_HOURS' => 'س' ,
   'LBL_DAY_OF_MONTH' => 'تاريخ' ,
   'LBL_MONTHS' => 'ش' ,
   'LBL_DAY_OF_WEEK' => 'ي' ,
   'LBL_CRONTAB_EXAMPLES' => 'الذي بعاليه يستخدم ترقيم crontab المتعارف عليه' ,
   'LBL_ALWAYS' => 'دائما' ,
   'LBL_CATCH_UP' => 'نفذ إذا كان ناقصا' ,
   'LBL_CATCH_UP_WARNING' => 'أزل التأشير إذا كانت هذه الوظيفة ستأخذ أكثر من لحظة واحدة لتشتغل.' ,
   'LBL_DATE_TIME_END' => 'نهاية التاريخ والتوقيت' ,
   'LBL_DATE_TIME_START' => 'بداية التاريخ والتوقيت' ,
   'LBL_INTERVAL' => 'فترة' ,
   'LBL_JOB' => 'وظيفة' ,
   'LBL_LAST_RUN' => 'آخر تشغيل ناجح' ,
   'LBL_MODULE_NAME' => 'مجدول شوجار' ,
   'LBL_MODULE_TITLE' => 'المجدولات' ,
   'LBL_NAME' => 'اسم الوظيفة' ,
   'LBL_NEVER' => 'أبدا' ,
   'LBL_NEW_FORM_TITLE' => 'جدول زمني جديد' ,
   'LBL_PERENNIAL' => 'دائم/ثابت' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في المجدوِل' ,
   'LBL_SCHEDULER' => 'المجدوِل:' ,
   'LBL_STATUS' => 'الحالة' ,
   'LBL_TIME_FROM' => 'ساري من' ,
   'LBL_TIME_TO' => 'ساري حتى' ,
   'LBL_WARN_CURL_TITLE' => 'تحذير cURL:' ,
   'LBL_WARN_CURL' => 'تحذير:' ,
   'LBL_WARN_NO_CURL' => 'النظام لا يحتوي على مكتبات cURL متاحة في وحدة بي إتش بي (--with-curl=/path/to/curl_library). من فضلك إتصل بمدير النظام لحل هذه المشكلة بدون إمكانية  cURL لا يستصيع المجدول تنظيم مهامه. ' ,
   'LBL_BASIC_OPTIONS' => 'تركيب بسيط' ,
   'LBL_ADV_OPTIONS' => 'خيارات متقدمة' ,
   'LBL_TOGGLE_ADV' => 'خيارات متقدمة' ,
   'LBL_TOGGLE_BASIC' => 'خيارات أساسية' ,
   'LNK_LIST_SCHEDULER' => 'المجدولات' ,
   'LNK_NEW_SCHEDULER' => 'إنشاء مجدولا' ,
   'LNK_LIST_SCHEDULED' => 'مهام مجدولة زمنيا' ,
   'SOCK_GREETING' => 'هذا هو واجهة استخدام خدمة مجدولات شوجر. [ Available daemon commands: start|restart|shutdown|status ] للخروج إكتب \'quit\' لإغلاق الخدمة اكتب \'shutdown' ,
   'ERR_DELETE_RECORD' => 'مهام مجدولة زمنيا' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'NTC_STATUS' => 'اضبط الحالة على غير نشط لإزالة هذا الجدول الزمني من قوائم المجدول الساقطة' ,
   'NTC_LIST_ORDER' => 'اضبط الترتيب الذي الذي سيظهر به هذا الجدول الزمني في قوائم المجدول الساقطة' ,
   'LBL_CRON_INSTRUCTIONS_WINDOWS' => 'لكي تثبت مجدول ويندوز' ,
   'LBL_CRON_INSTRUCTIONS_LINUX' => 'لتثبيت Crontab' ,
   'LBL_CRON_LINUX_DESC' => 'أضف هذا الشطر لأمر Crontab: ' ,
   'LBL_CRON_WINDOWS_DESC' => 'إنشاء ملف باتش به الأوامر التالية: ' ,
   'LBL_NO_PHP_CLI' => 'لو أن مضيفك لا يتيح PHP binary  يمكنك إستخدام wget أو curl لإطلاق المهام 

for wget: *    *    *    *    *    wget --quiet --non-verbose /cron.php > /dev/null 2>&1
for curl: *    *    *    *    *    curl --silent /cron.php > /dev/null 2>&1\'' ,
   'LBL_JOBS_SUBPANEL_TITLE' => 'تسجيلات الوظيفة' ,
   'LBL_EXECUTE_TIME' => 'نفذ الوقت' ,
   'scheduler_period_dom' => array (
      'min' => 'دقائق' ,
      'hour' => 'ساعات'   ),
   'scheduler_status_dom' => array (
      'Active' => 'نشط' ,
      'Inactive' => 'غير نشط'   ));

?>
