<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProjectTask/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'مهام المشروع' ,
   'LBL_MODULE_TITLE' => 'مهمة خاصة بمشروع: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في مهام المشاريع' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة مهام المشاريع' ,
   'LBL_ID' => 'هوية:' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل:' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل:' ,
   'LBL_ASSIGNED_USER_ID' => 'كلف بها:' ,
   'LBL_MODIFIED_USER_ID' => 'هوية المستخدم المعدّل:' ,
   'LBL_CREATED_BY' => 'أنشئ بواسطة:' ,
   'LBL_TEAM_ID' => 'فريق:' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_DATE_DUE' => 'مطلوب بتاريخ:' ,
   'LBL_TIME_DUE' => 'الوقت المطلوب فيه:' ,
   'LBL_DATE_START' => 'تاريخ البدء:' ,
   'LBL_TIME_START' => 'زمن البدء:' ,
   'LBL_PARENT_ID' => 'مشروع:' ,
   'LBL_PRIORITY' => 'أولوية:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_ORDER_NUMBER' => 'ترتيب:' ,
   'LBL_TASK_NUMBER' => 'رقم المهمة:' ,
   'LBL_DEPENDS_ON_ID' => 'يعتمد على:' ,
   'LBL_MILESTONE_FLAG' => 'حدث رئيسي:' ,
   'LBL_ESTIMATED_EFFORT' => 'الجهد المقدر (ساعات):' ,
   'LBL_ACTUAL_EFFORT' => 'الجهد الفعلي (ساعات):' ,
   'LBL_UTILIZATION' => 'استفادة (%):' ,
   'LBL_PERCENT_COMPLETE' => 'تقدم (%):' ,
   'LBL_DELETED' => 'تم الحذف:' ,
   'LBL_LIST_ORDER_NUMBER' => 'ترتيب' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_PARENT_NAME' => 'مشروع' ,
   'LBL_LIST_PERCENT_COMPLETE' => 'تقدم (%)' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_ASSIGNED_USER_ID' => 'كلف بها' ,
   'LBL_LIST_DATE_DUE' => 'التاريخ المطلوب فيه' ,
   'LBL_LIST_DATE_START' => 'تاريخ البدء' ,
   'LBL_LIST_PRIORITY' => 'أولوية' ,
   'LBL_LIST_CLOSE' => 'إغلاق' ,
   'LBL_PROJECT_NAME' => 'اسم المشروع' ,
   'LNK_NEW_PROJECT' => 'إنشاء مشروعا' ,
   'LNK_PROJECT_LIST' => 'قائمة المشاريع' ,
   'LNK_NEW_PROJECT_TASK' => 'إنشاء مهمة خاصة بمشروع' ,
   'LNK_PROJECT_TASK_LIST' => 'مهام المشروع' ,
   'LBL_LIST_MY_PROJECT_TASKS' => 'مهام المشاريع المفتوحة ' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'مهام المشروع' ,
   'LBL_NEW_FORM_TITLE' => 'مهمة جديدة خاصة بمشروع' ,
   'LBL_ACTIVITIES_TITLE' => 'أنشطة' ,
   'LBL_HISTORY_TITLE' => 'سيرة' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'DATE_JS_ERROR' => 'الرجاءإدخال تاريخا متوافقا مع الزمن الذي تم إدخاله' );

?>
