<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Shippers/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'الشاحنون' ,
   'LBL_MODULE_TITLE' => 'متعهد الشحن: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في متعهدي الشحن' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة متعهدي الشحن' ,
   'LBL_NEW_FORM_TITLE' => 'متعهد شحن جديد' ,
   'LBL_SHIPPER' => 'متعهد شحن:' ,
   'LBL_LIST_NAME' => 'متعهد شحن' ,
   'LBL_NAME' => 'متعهد شحن:' ,
   'LBL_LIST_LIST_ORDER' => 'ترتيب' ,
   'LBL_LIST_ORDER' => 'ترتيب:' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LNK_NEW_SHIPPER' => 'قائمة متعهدي الشحن' ,
   'LNK_NEW_TAXRATE' => 'قائمة معدل الضريبه' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء الشاحن' ,
   'NTC_STATUS' => 'أجعل الحالة غير نشط لإلغاء متعهد الشحن هذا من القوائم المنسدلة لمتعهدي الشحن' ,
   'NTC_LIST_ORDER' => 'أعد ترتيب متعهد الشحن هذا الذي سيظهر في القوائم المنسدلة لمتعهد الشحن' ,
   'shipper_status_dom' => array (
      'Active' => 'نشط' ,
      'Inactive' => 'غير نشط'   ));

?>
