<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Prospects/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'أهداف' ,
   'LBL_MODULE_ID' => 'العملاء المتوقعين' ,
   'LBL_INVITEE' => 'تقارير مباشرة' ,
   'LBL_MODULE_TITLE' => 'العناصر المستهدفة: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في العناصر المستهدفة' ,
   'LBL_LIST_FORM_TITLE' => 'القائمة المستهدفة' ,
   'LBL_NEW_FORM_TITLE' => 'عنصر مستهدف جديد' ,
   'LBL_PROSPECT' => 'الهدف:' ,
   'LBL_BUSINESSCARD' => 'بطاقة عمل' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_LAST_NAME' => 'اسم أخير' ,
   'LBL_LIST_PROSPECT_NAME' => 'اسم العنصر المستهدف' ,
   'LBL_LIST_TITLE' => 'اللقب' ,
   'LBL_LIST_EMAIL_ADDRESS' => 'بريد الكتروني' ,
   'LBL_LIST_OTHER_EMAIL_ADDRESS' => 'بريد إلكتروني آخر' ,
   'LBL_LIST_PHONE' => 'تليفون' ,
   'LBL_LIST_PROSPECT_ROLE' => 'صلاحية' ,
   'LBL_LIST_FIRST_NAME' => 'اسم أول' ,
   'LBL_ASSIGNED_TO_NAME' => 'مخصصة لإسم' ,
   'db_last_name' => 'LBL_LIST_LAST_NAME' ,
   'db_first_name' => 'LBL_LIST_FIRST_NAME' ,
   'db_title' => 'LBL_LIST_TITLE' ,
   'db_email1' => 'LBL_LIST_EMAIL_ADDRESS' ,
   'db_email2' => 'LBL_LIST_OTHER_EMAIL_ADDRESS' ,
   'LBL_CAMPAIGN_ID' => 'هوية الحملة' ,
   'LBL_EXISTING_PROSPECT' => 'إستخدم جهة إتصال قائمة' ,
   'LBL_CREATED_PROSPECT' => 'إنشأ اتصال جديد' ,
   'LBL_EXISTING_ACCOUNT' => 'استخدَم حسابا قائما' ,
   'LBL_CREATED_ACCOUNT' => 'أنشأ حساب جديد' ,
   'LBL_CREATED_CALL' => 'أنشأ مكالمة جديدة' ,
   'LBL_CREATED_MEETING' => 'أنشأ اجتماعا جديدا' ,
   'LBL_ADDMORE_BUSINESSCARD' => 'إدخال بطاقة عمل أخرى' ,
   'LBL_ADD_BUSINESSCARD' => 'إدخال بطاقة عمل' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_PROSPECT_NAME' => 'اسم العنصر المستهدف:' ,
   'LBL_PROSPECT_INFORMATION' => 'معلومات العنصر المستهدف' ,
   'LBL_FIRST_NAME' => 'اسم أول:' ,
   'LBL_OFFICE_PHONE' => 'تليفون المكتب:' ,
   'LBL_ANY_PHONE' => 'أي تليفون:' ,
   'LBL_PHONE' => 'تليفون:' ,
   'LBL_LAST_NAME' => 'اسم أخير:' ,
   'LBL_MOBILE_PHONE' => 'محمول:' ,
   'LBL_HOME_PHONE' => 'الرئيسية:' ,
   'LBL_OTHER_PHONE' => 'تليفون آخر:' ,
   'LBL_FAX_PHONE' => 'فاكس:' ,
   'LBL_PRIMARY_ADDRESS_STREET' => 'شارع العنوانِ الأساسيِ 2:' ,
   'LBL_PRIMARY_ADDRESS_CITY' => 'المدينة الرئيسية للعنوان:' ,
   'LBL_PRIMARY_ADDRESS_COUNTRY' => 'البلد الرئيسية للعنوان:' ,
   'LBL_PRIMARY_ADDRESS_STATE' => 'محافظة العنوان الرئيسي:' ,
   'LBL_PRIMARY_ADDRESS_POSTALCODE' => 'الرمز البريد الرئيسي للعنوان:' ,
   'LBL_ALT_ADDRESS_STREET' => 'شارع بديل للعنوان:' ,
   'LBL_ALT_ADDRESS_CITY' => 'مدينة بديلة للعنوان:' ,
   'LBL_ALT_ADDRESS_COUNTRY' => 'بلد بديل للعنوان:' ,
   'LBL_ALT_ADDRESS_STATE' => 'محافظة العنوان البديل:' ,
   'LBL_ALT_ADDRESS_POSTALCODE' => 'رمز بريدي بديل للعنوان:' ,
   'LBL_TITLE' => 'اللقب:' ,
   'LBL_DEPARTMENT' => 'قسم:' ,
   'LBL_BIRTHDATE' => 'تاريخ الميلاد:' ,
   'LBL_EMAIL_ADDRESS' => 'بريد الكتروني:' ,
   'LBL_OTHER_EMAIL_ADDRESS' => 'بريد إلكتروني آخر:' ,
   'LBL_ANY_EMAIL' => 'أي بريد إلكتروني:' ,
   'LBL_ASSISTANT' => 'مساعد:' ,
   'LBL_ASSISTANT_PHONE' => 'تليفون المساعد:' ,
   'LBL_DO_NOT_CALL' => 'لا تتصل:' ,
   'LBL_EMAIL_OPT_OUT' => 'البريد المختار:' ,
   'LBL_PRIMARY_ADDRESS' => 'العنوان الأساسي:' ,
   'LBL_ALTERNATE_ADDRESS' => 'عنوان آخر:' ,
   'LBL_ANY_ADDRESS' => 'أي عنوان:' ,
   'LBL_CITY' => 'مدينة:' ,
   'LBL_STATE' => 'محافظة:' ,
   'LBL_POSTAL_CODE' => 'الرمز البريدي:' ,
   'LBL_COUNTRY' => 'بلد:' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_ADDRESS_INFORMATION' => 'بيانات العنوان' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_PROSPECT_ROLE' => 'صلاحية:' ,
   'LBL_OPP_NAME' => 'فرصة بيع:' ,
   'LBL_IMPORT_VCARD' => 'إستيراد vCard' ,
   'LBL_IMPORT_VCARDTEXT' => 'إنشاء جهة إتصال جديدة أوتوماتيكيا عن طريق إستيراد vCard من ملف نظامك' ,
   'LBL_DUPLICATE' => 'عناصر مستهدفة متكررة محتملة' ,
   'MSG_SHOW_DUPLICATES' => 'إنشاء هذا الاتصال من المحتمل أن ينشئ اتصالا متكررا. يمكنك إما أن تضغط على \"أنشئ عنصرا مستهدفا\" للاستمرار في إنشاء هذا الاتصال الجديد بالبيانات المدخلة سابقا أو أن تضغط \"تراجع\".' ,
   'MSG_DUPLICATE' => 'إنشاء هذا الاتصال من المحتمل أن ينشئ اتصالا متكررا. يمكنك إما أن تختار اتصالا من القائمة أدناه أو أن تضغط على \"أنشئ عنصرا مستهدفا\" للاستمرار في إنشاء اتصال جديد بالبيانات المدخلة سابقا.' ,
   'LNK_IMPORT_VCARD' => 'إنشاء من vCard' ,
   'LNK_NEW_ACCOUNT' => 'إنشاء حساب' ,
   'LNK_NEW_OPPORTUNITY' => 'إنشاء فرصة' ,
   'LNK_NEW_CASE' => 'إنشاء حالة' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_EMAIL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_NEW_APPOINTMENT' => 'إنشاء موعد' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'NTC_REMOVE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إزالة جهة الإتصال من هذه الحالة؟' ,
   'NTC_REMOVE_DIRECT_REPORT_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذا التسجيل كتقرير مباشر؟' ,
   'ERR_DELETE_RECORD' => 'من الضروري تحديد رقم سجل لإلغاء اتصال ' ,
   'NTC_COPY_PRIMARY_ADDRESS' => 'انسخ العنوان الرئيسي للعنوان البديل ' ,
   'NTC_COPY_ALTERNATE_ADDRESS' => 'انسخ العنوان البديل للعنوان الرئيسي' ,
   'LBL_SALUTATION' => 'تحية' ,
   'LBL_SAVE_PROSPECT' => 'حفظ العنصر المستهدف' ,
   'LBL_CREATED_OPPORTUNITY' => 'إنشاء فرصة جديدة' ,
   'NTC_OPPORTUNITY_REQUIRES_ACCOUNT' => 'إنشاء فرصة يتطلب وجود حساب. من فضلك إما أن تنشئ واحدا أو أن تختار حساب موجودا.' ,
   'LNK_SELECT_ACCOUNT' => 'اختر حساب' ,
   'LNK_NEW_PROSPECT' => 'إنشاء هدفا' ,
   'LNK_PROSPECT_LIST' => 'أهداف' ,
   'LNK_NEW_CAMPAIGN' => 'إنشاء حملة' ,
   'LNK_CAMPAIGN_LIST' => 'حملات' ,
   'LNK_NEW_PROSPECT_LIST' => 'إنشاء القائمة المستهدفة' ,
   'LNK_PROSPECT_LIST_LIST' => 'القوائم المستهدفة' ,
   'LNK_IMPORT_PROSPECT' => 'إستيراد العناصر المستهدفة' ,
   'LBL_SELECT_CHECKED_BUTTON_LABEL' => 'اختر العناصر المستهدفة المؤشر عليها' ,
   'LBL_SELECT_CHECKED_BUTTON_TITLE' => 'اختر العناصر المستهدفة المؤشر عليها' ,
   'LBL_INVALID_EMAIL' => 'بريد إلكتروني غير صحيح:' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'أهداف' ,
   'LBL_CONVERT_BUTTON_KEY' => 'V' ,
   'LBL_CONVERT_BUTTON_TITLE' => 'تحويل الهدف' ,
   'LBL_CONVERT_BUTTON_LABEL' => 'تحويل الهدف' ,
   'LBL_CONVERTPROSPECT' => 'تحويل الهدف' ,
   'LNK_NEW_CONTACT' => 'جهة إتصال جديدة' ,
   'LBL_CREATED_CONTACT' => 'إنشأ اتصال جديد' ,
   'LBL_BACKTO_PROSPECTS' => 'الرجوع للأهداف' ,
   'LBL_CAMPAIGNS' => 'حملات' ,
   'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE' => 'تسجيل الحملات ' ,
   'LBL_TRACKER_KEY' => 'مفتاح المتتبع' ,
   'LBL_LEAD_ID' => 'هوية العميل المتوقع' ,
   'LBL_CONVERTED_LEAD' => 'عملاء متوقعين' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_EDIT_ACCOUNT_NAME' => 'اسم الحساب:' );

?>
