<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Contacts/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'db_last_name' => 'LBL_LIST_LAST_NAME' ,
   'db_first_name' => 'LBL_LIST_FIRST_NAME' ,
   'db_title' => 'LBL_LIST_TITLE' ,
   'db_email1' => 'LBL_LIST_EMAIL_ADDRESS' ,
   'db_email2' => 'LBL_LIST_OTHER_EMAIL_ADDRESS' ,
   'LNK_CONTACT_REPORTS' => 'تقارير جهة إتصال' ,
   'ERR_DELETE_RECORD' => 'من الضروري تحديد رقم سجل لإلغاء اتصال ' ,
   'LBL_ACCOUNT_ID' => 'هوية الحساب:' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_CAMPAIGN' => 'حملة:' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_ADD_BUSINESSCARD' => 'إدخال بطاقة عمل' ,
   'LBL_ADDMORE_BUSINESSCARD' => 'إدخال بطاقة عمل أخرى' ,
   'LBL_ADDRESS_INFORMATION' => 'بيانات العنوان' ,
   'LBL_ALT_ADDRESS_CITY' => 'مدينة بديلة للعنوان:' ,
   'LBL_ALT_ADDRESS_COUNTRY' => 'بلد بديل للعنوان:' ,
   'LBL_ALT_ADDRESS_POSTALCODE' => 'رمز بريدي بديل للعنوان:' ,
   'LBL_ALT_ADDRESS_STATE' => 'محافظة العنوان البديل:' ,
   'LBL_ALT_ADDRESS_STREET_2' => 'شارع ثاني بديل للعنوان:' ,
   'LBL_ALT_ADDRESS_STREET_3' => 'شارع ثالث بديل للعنوان:' ,
   'LBL_ALT_ADDRESS_STREET' => 'شارع بديل للعنوان:' ,
   'LBL_ALTERNATE_ADDRESS' => 'عنوان آخر:' ,
   'LBL_ANY_ADDRESS' => 'أي عنوان:' ,
   'LBL_ANY_EMAIL' => 'أي بريد إلكتروني:' ,
   'LBL_ANY_PHONE' => 'أي تليفون:' ,
   'LBL_ASSIGNED_TO_NAME' => 'إسم المستخدم المكلفبن:' ,
   'LBL_ASSISTANT_PHONE' => 'تليفون المساعد:' ,
   'LBL_ASSISTANT' => 'مساعد:' ,
   'LBL_BIRTHDATE' => 'تاريخ الميلاد:' ,
   'LBL_BUSINESSCARD' => 'بطاقة عمل' ,
   'LBL_CITY' => 'مدينة:' ,
   'LBL_CAMPAIGN_ID' => 'هوية الحملة' ,
   'LBL_CONTACT_INFORMATION' => 'معلومات الاتصال' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال:' ,
   'LBL_CONTACT_OPP_FORM_TITLE' => 'فرص جهة الإتصال:' ,
   'LBL_CONTACT_ROLE' => 'صلاحية:' ,
   'LBL_CONTACT' => 'جهة إتصال:' ,
   'LBL_COUNTRY' => 'بلد:' ,
   'LBL_CREATED_ACCOUNT' => 'تم إنشاء حساب جديد' ,
   'LBL_CREATED_CALL' => 'أنشأ مكالمة جديدة' ,
   'LBL_CREATED_CONTACT' => 'تم إنشاء اتصال جديد' ,
   'LBL_CREATED_MEETING' => 'أنشأ اجتماعا جديدا' ,
   'LBL_CREATED_OPPORTUNITY' => 'أنشأ فرصة جديدة' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل:' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_DEPARTMENT' => 'قسم:' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_DIRECT_REPORTS_SUBPANEL_TITLE' => 'تقارير مباشرة' ,
   'LBL_DO_NOT_CALL' => 'لا تتصل:' ,
   'LBL_DUPLICATE' => 'اتصالات مزدوجة محتملة' ,
   'LBL_EMAIL_ADDRESS' => 'بريد الكتروني:' ,
   'LBL_EMAIL_OPT_OUT' => 'البريد المختار:' ,
   'LBL_EXISTING_ACCOUNT' => 'استخدَم حسابا قائما' ,
   'LBL_EXISTING_CONTACT' => 'إستخدم جهة إتصال قائمة' ,
   'LBL_EXISTING_OPPORTUNITY' => 'استخدَم فرصة قائمة' ,
   'LBL_FAX_PHONE' => 'فاكس:' ,
   'LBL_FIRST_NAME' => 'اسم أول:' ,
   'LBL_FULL_NAME' => 'اسم بالكامل:' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_HOME_PHONE' => 'الرئيسية:' ,
   'LBL_ID' => 'ID:' ,
   'LBL_IMPORT_VCARD' => 'إستيراد vCard' ,
   'LBL_IMPORT_VCARDTEXT' => 'إنشاء جهة إتصال جديدة أوتوماتيكيا عن طريق إستيراد vCard من ملف نظامك' ,
   'LBL_INVALID_EMAIL' => 'بريد إلكتروني غير صحيح:' ,
   'LBL_INVITEE' => 'تقارير مباشرة' ,
   'LBL_LAST_NAME' => 'اسم أخير:' ,
   'LBL_LEAD_SOURCE' => 'مصدر عميل متوقع:' ,
   'LBL_LIST_ACCEPT_STATUS' => 'اقبل الحالة' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_CONTACT_NAME' => 'اسم جهة الإتصال' ,
   'LBL_LIST_CONTACT_ROLE' => 'صلاحية' ,
   'LBL_LIST_EMAIL_ADDRESS' => 'بريد الكتروني' ,
   'LBL_LIST_FIRST_NAME' => 'اسم أول' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة اتصال' ,
   'LBL_VIEW_FORM_TITLE' => 'مطالعة جهة الإتصال' ,
   'LBL_LIST_LAST_NAME' => 'اسم أخير' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_OTHER_EMAIL_ADDRESS' => 'بريد إلكتروني آخر' ,
   'LBL_LIST_PHONE' => 'تليفون المكتب' ,
   'LBL_LIST_TITLE' => 'اللقب' ,
   'LBL_MOBILE_PHONE' => 'محمول:' ,
   'LBL_MODIFIED' => 'تم تعديله بواسطة هوية المستخدم:' ,
   'LBL_MODULE_NAME' => 'جهات إتصال' ,
   'LBL_MODULE_TITLE' => 'جهات الإتصال: رئيسية' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_NEW_FORM_TITLE' => 'جهة إتصال جديدة' ,
   'LBL_NEW_PORTAL_PASSWORD' => 'كلمة سر جديدة للبوابة الإلكترونية' ,
   'LBL_NOTE_SUBJECT' => 'موضوع الملاحظة' ,
   'LBL_OFFICE_PHONE' => 'تليفون المكتب:' ,
   'LBL_OPP_NAME' => 'فرصة بيع:' ,
   'LBL_OPPORTUNITY_ROLE_ID' => 'هوية ترتيب الفرصة:' ,
   'LBL_OPPORTUNITY_ROLE' => 'ترتيب الفرصة' ,
   'LBL_OTHER_EMAIL_ADDRESS' => 'بريد إلكتروني آخر:' ,
   'LBL_OTHER_PHONE' => 'تليفون آخر:' ,
   'LBL_PHONE' => 'تليفون:' ,
   'LBL_PORTAL_ACTIVE' => 'البوابة نشطة:' ,
   'LBL_PORTAL_APP' => 'تطبيق البوابة:' ,
   'LBL_PORTAL_INFORMATION' => 'معلومات البوابة' ,
   'LBL_PORTAL_NAME' => 'اسم البوابة:' ,
   'LBL_PORTAL_PASSWORD_ISSET' => 'تم ضبط كلمة سر البوابة:' ,
   'LBL_POSTAL_CODE' => 'الرمز البريدي:' ,
   'LBL_PRIMARY_ADDRESS_CITY' => 'المدينة الرئيسية للعنوان:' ,
   'LBL_PRIMARY_ADDRESS_COUNTRY' => 'البلد الرئيسية للعنوان:' ,
   'LBL_PRIMARY_ADDRESS_POSTALCODE' => 'الرمز البريد الرئيسي للعنوان:' ,
   'LBL_PRIMARY_ADDRESS_STATE' => 'محافظة العنوان الرئيسي:' ,
   'LBL_PRIMARY_ADDRESS_STREET_2' => 'شارع العنوانِ الأساسيِ 2:' ,
   'LBL_PRIMARY_ADDRESS_STREET_3' => 'شارع العنوانِ الأساسيِ 3:' ,
   'LBL_PRIMARY_ADDRESS_STREET' => 'شارع العنوانِ الأساسيِ 2:' ,
   'LBL_PRIMARY_ADDRESS' => 'العنوان الأساسي:' ,
   'LBL_PRODUCTS_TITLE' => 'منتجات' ,
   'LBL_RELATED_CONTACTS_TITLE' => 'جهات الإتصال المتعلقة' ,
   'LBL_REPORTS_TO_ID' => 'تقارير للهوية:' ,
   'LBL_REPORTS_TO' => 'تقارير لـ:' ,
   'LBL_SALUTATION' => 'تحية:' ,
   'LBL_SAVE_CONTACT' => 'حفظ جهة الاتصال' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث عن جهة إتصال' ,
   'LBL_SELECT_CHECKED_BUTTON_LABEL' => 'اختر جهات الإتصال المؤشر عليها' ,
   'LBL_SELECT_CHECKED_BUTTON_TITLE' => 'اختر جهات الإتصال المؤشر عليها' ,
   'LBL_STATE' => 'محافظة:' ,
   'LBL_SYNC_CONTACT' => 'زامن مع أوتلوك:' ,
   'LBL_TEAM_ID' => 'هوية الفريق:' ,
   'LBL_TITLE' => 'اللقب:' ,
   'LNK_CONTACT_LIST' => 'جهات إتصال' ,
   'LNK_IMPORT_VCARD' => 'إنشاء من vCard' ,
   'LNK_NEW_ACCOUNT' => 'إنشاء حساب' ,
   'LNK_NEW_APPOINTMENT' => 'إنشاء موعد' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_CASE' => 'إنشاء حالة' ,
   'LNK_NEW_CONTACT' => 'إنشاء جهة إتصال' ,
   'LNK_NEW_EMAIL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة' ,
   'LNK_NEW_OPPORTUNITY' => 'إنشاء فرصة' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_SELECT_ACCOUNT' => 'اختر حساب' ,
   'MSG_DUPLICATE' => 'إنشاء هذا الاتصال من المحتمل أن ينشئ اتصالا متكررا. يمكنك إما أن تختار اتصالا من القائمة أدناه أو أن تضغط على \"أنشئ عنصرا مستهدفا\" للاستمرار في إنشاء اتصال جديد بالبيانات المدخلة سابقا.' ,
   'MSG_SHOW_DUPLICATES' => 'إنشاء هذا الاتصال من المحتمل أن ينشئ اتصالا متكررا. يمكنك إما أن تضغط على \"أنشئ عنصرا مستهدفا\" للاستمرار في إنشاء هذا الاتصال الجديد بالبيانات المدخلة سابقا أو أن تضغط \"تراجع\".' ,
   'NTC_COPY_ALTERNATE_ADDRESS' => 'انسخ العنوان البديل للعنوان الرئيسي' ,
   'NTC_COPY_PRIMARY_ADDRESS' => 'انسخ العنوان الرئيسي للعنوان البديل ' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'NTC_OPPORTUNITY_REQUIRES_ACCOUNT' => 'إنشاء فرصة يتطلب وجود حساب. من فضلك إما أن تنشئ واحدا أو أن تختار حساب موجودا.' ,
   'NTC_REMOVE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إزالة جهة الإتصال من هذه الحالة؟' ,
   'NTC_REMOVE_DIRECT_REPORT_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذا التسجيل كتقرير مباشر؟' ,
   'LBL_USER_PASSWORD' => 'كمة سر:' ,
   'LBL_LEADS_SUBPANEL_TITLE' => 'عملاء متوقعين' ,
   'LBL_OPPORTUNITIES_SUBPANEL_TITLE' => 'فرص بيع' ,
   'LBL_QUOTES_SUBPANEL_TITLE' => 'إقتباسات' ,
   'LBL_PRODUCTS_SUBPANEL_TITLE' => 'منتجات' ,
   'LBL_CASES_SUBPANEL_TITLE' => 'حالات' ,
   'LBL_BUGS_SUBPANEL_TITLE' => 'مشكلات' ,
   'LBL_PROJECTS_SUBPANEL_TITLE' => 'مشروعات' ,
   'LBL_COPY_ADDRESS_CHECKED' => 'انسخ العنوان للاتصالات المؤشر عليها' ,
   'LBL_TARGET_OF_CAMPAIGNS' => 'حملات (المستهدفة من):' ,
   'LBL_CAMPAIGNS' => 'حملات' ,
   'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE' => 'تسجيل الحملات ' ,
   'LBL_LIST_CITY' => 'مدينة' ,
   'LBL_LIST_STATE' => 'محافظة' ,
   'LBL_HOMEPAGE_TITLE' => 'جهات الإتصال الخاصة بي' ,
   'LBL_PORTAL_PASSWORD' => 'كلمة سر البوابة' ,
   'LBL_CONFIRM_PORTAL_PASSWORD' => 'التاكيد عى كلمة سر البوابة الإلكترونية' );

?>
