<?php 
 //WARNING: The contents of this file are auto-generated
$beanList['HWLA_HARASAWAITINGLISTACTIVE'] = 'HWLA_HARASAWAITINGLISTACTIVE';
$beanFiles['HWLA_HARASAWAITINGLISTACTIVE'] = 'modules/HWLA_HARASAWAITINGLISTACTIVE/HWLA_HARASAWAITINGLISTACTIVE.php';
$moduleList[] = 'HWLA_HARASAWAITINGLISTACTIVE';

?>