<?php 
 //WARNING: The contents of this file are auto-generated
$beanList['WLMCA_WAITINGLISTMSDCLINICACTIVE'] = 'WLMCA_WAITINGLISTMSDCLINICACTIVE';
$beanFiles['WLMCA_WAITINGLISTMSDCLINICACTIVE'] = 'modules/WLMCA_WAITINGLISTMSDCLINICACTIVE/WLMCA_WAITINGLISTMSDCLINICACTIVE.php';
$moduleList[] = 'WLMCA_WAITINGLISTMSDCLINICACTIVE';

?>