<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/CampaignLog/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_LIST_ID' => 'هوية قائمة العملاء المحتملين' ,
   'LBL_ID' => 'ID' ,
   'LBL_TARGET_TRACKER_KEY' => 'مفتاح متتبع الهدف' ,
   'LBL_TARGET_ID' => 'هوية الهدف' ,
   'LBL_TARGET_TYPE' => 'نوع الهدف' ,
   'LBL_ACTIVITY_TYPE' => 'نوع النشاط' ,
   'LBL_ACTIVITY_DATE' => 'تاريخ النشاط' ,
   'LBL_RELATED_ID' => 'الهوية المتعلقة' ,
   'LBL_RELATED_TYPE' => 'النوع المتعلق' ,
   'LBL_DELETED' => 'تم الحذف' ,
   'LBL_MODULE_NAME' => 'تسجيل الحملات ' ,
   'LBL_LIST_RECIPIENT_EMAIL' => 'البريد المرسل إليه' ,
   'LBL_LIST_RECIPIENT_NAME' => 'الإسم المرسل إليه' ,
   'LBL_ARCHIVED' => 'محول للأرشيف' ,
   'LBL_HITS' => 'الزيارات' ,
   'LBL_CAMPAIGN_NAME' => 'اسم:' ,
   'LBL_CAMPAIGN' => 'حملة:' ,
   'LBL_NAME' => 'اسم: ' ,
   'LBL_INVITEE' => 'جهات إتصال' ,
   'LBL_LIST_CAMPAIGN_NAME' => 'حملة' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_TYPE' => 'النوع' ,
   'LBL_LIST_END_DATE' => 'تاريخ الانتهاء' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_MODIFIED' => 'عدّله: ' ,
   'LBL_CREATED' => 'أنشأه: ' ,
   'LBL_TEAM' => 'فريق: ' ,
   'LBL_ASSIGNED_TO' => 'مكلف به: ' ,
   'LBL_CAMPAIGN_START_DATE' => 'تاريخ البدء: ' ,
   'LBL_CAMPAIGN_END_DATE' => 'تاريخ الانتهاء: ' ,
   'LBL_CAMPAIGN_STATUS' => 'الحالة: ' ,
   'LBL_CAMPAIGN_BUDGET' => 'ميزانية: ' ,
   'LBL_CAMPAIGN_EXPECTED_COST' => 'التكلفة المتوقعة: ' ,
   'LBL_CAMPAIGN_ACTUAL_COST' => 'التكلفة الحقيقية: ' ,
   'LBL_CAMPAIGN_EXPECTED_REVENUE' => 'العائد المتوقع: ' ,
   'LBL_CAMPAIGN_TYPE' => 'النوع: ' ,
   'LBL_CAMPAIGN_OBJECTIVE' => 'الهدف: ' ,
   'LBL_CAMPAIGN_CONTENT' => 'وصف: ' ,
   'LBL_LIST_FORM_TITLE' => 'الحملات الموجهة' ,
   'LBL_LIST_ACTIVITY_DATE' => 'تاريخ النشاط' ,
   'LBL_LIST_CAMPAIGN_OBJECTIVE' => 'هدف الحملة' ,
   'LBL_RELATED' => 'متعلق' ,
   'LBL_CLICKED_URL_KEY' => 'مفتاح الرابط المضغوط عليه' ,
   'LBL_URL_CLICKED' => 'الرابط المضغوط عليه' ,
   'LBL_MORE_INFO' => 'مزيد من المعلومات' );

?>
