<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Configurator/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ADMIN_EXPORT_ONLY' => 'التصدير من خلال الإدارة فقط' ,
   'ADVANCED' => 'متقدم' ,
   'CURRENT_LOGO' => 'الشعار الحالي مستخدم' ,
   'DEFAULT_CURRENCY_ISO4217' => 'شفرة عملة بنظام أيزو 4217' ,
   'DEFAULT_CURRENCY_NAME' => 'اسم العملة' ,
   'DEFAULT_CURRENCY_SYMBOL' => 'رمز العملة' ,
   'DEFAULT_CURRENCY' => 'العملة الإفتراضية' ,
   'DEFAULT_DATE_FORMAT' => 'صيغة التاريخ التلقائية' ,
   'DEFAULT_DECIMAL_SEP' => 'الرمز العشري' ,
   'DEFAULT_LANGUAGE' => 'اللغة التلقائية' ,
   'DEFAULT_NUMBER_GROUPING_SEP' => 'فاصلة خانات الآلاف' ,
   'DEFAULT_SYSTEM_SETTINGS' => 'واجهة المستخدم' ,
   'DEFAULT_THEME' => 'شكل العرض الإفتراضي' ,
   'DEFAULT_TIME_FORMAT' => 'صيغة الووقت الإفتراضية' ,
   'DISABLE_EXPORT' => 'حظر التصدير' ,
   'DISPLAY_LOGIN_NAV' => 'اعرض عناصر القائمة الرئيسية على شاشة تسجيل الدخول' ,
   'DISPLAY_RESPONSE_TIME' => 'اعرض أوقات استجابة الجهاز الخادم' ,
   'EXPORT' => 'تصديّر' ,
   'EXPORT_CHARSET' => 'الترميز التلقائي المستخدم في التصدير' ,
   'EXPORT_DELIMITER' => 'الفاصل المستخدم في التصدير' ,
   'IMAGES' => 'شعارات' ,
   'LBL_CONFIGURE_SETTINGS_TITLE' => 'إعدادات النظام' ,
   'LBL_ENABLE_MAILMERGE' => 'إتاحة دمج البريد؟' ,
   'LBL_LOGVIEW' => 'تحكم إعداد التسجيل' ,
   'LBL_MAIL_SMTPAUTH_REQ' => 'استخدم تحقيق صلاحية  \"SMTP\"؟' ,
   'LBL_MAIL_SMTPPASS' => 'كلمة سر  \"SMTP\":' ,
   'LBL_MAIL_SMTPPORT' => 'منفذ  \"SMTP\":' ,
   'LBL_MAIL_SMTPSERVER' => 'خادم \"SMTP\":' ,
   'LBL_MAIL_SMTPUSER' => 'إسم مستخدم \"SMTP\":' ,
   'LBL_MAILMERGE_DESC' => 'لابد من التأشير فقط لو أن لديك مزود شوجر سي آر إم لMicrosoft® Word®' ,
   'LBL_MAILMERGE' => 'دمج البريد' ,
   'LBL_MODULE_NAME' => 'إعدادات النظام' ,
   'LBL_MODULE_ID' => 'وحدة الإعداد' ,
   'LBL_MODULE_TITLE' => 'واجهة المستخدم' ,
   'LBL_NOTIFY_FROMADDRESS' => 'من عنوان:' ,
   'LBL_NOTIFY_SUBJECT' => 'موضوع البريد:' ,
   'LBL_PORTAL_ON_DESC' => 'تتيح الوصول إلى الحالة والملاحظة بواسطة عميل بوابة الخدمة الإلكترونية الذاتية للعميل' ,
   'LBL_PORTAL_ON' => 'إتاحة التكامل مع البوابة الإلكترونية ذاتية الخدمة للعميل؟' ,
   'LBL_PORTAL_TITLE' => ' البوابة الإلكترونية ذاتية الخدمة للعميل' ,
   'LBL_PROXY_AUTH' => 'تحقيق الصلاحية' ,
   'LBL_PROXY_HOST' => 'مضيف بروكسي' ,
   'LBL_PROXY_ON_DESC' => 'إعداد العنوان و خصائص تحقيق الهوية الخاصة بخادم بروكسي؟' ,
   'LBL_PROXY_ON' => 'إستخدام خادم بروكسي؟' ,
   'LBL_PROXY_PASSWORD' => 'كمة سر' ,
   'LBL_PROXY_PORT' => 'بورت' ,
   'LBL_PROXY_TITLE' => 'إعدادات البروكسي' ,
   'LBL_PROXY_USERNAME' => 'اسم المستخدم' ,
   'LBL_RESTORE_BUTTON_LABEL' => 'إسترجاع' ,
   'LBL_SKYPEOUT_ON_DESC' => 'يسمح للمستخدمين بالضغط على أرقام التليفون للاتصال باستخدام \"SkypeOut®\". لابد من صياغة الأرقام بشكل مناسب للاستفادة من هذه الخاصية. أي أنها لابد أن تكون \"+\" \"كود البلد\" \"الرقم\" مثل  +1 (555) 555-1234.  لمزيد من المعلومات، انظر الأسئلة المتكررة في \"  أسئلة متكررة لـ skype®\"
' ,
   'LBL_SKYPEOUT_ON' => 'إتاحة التكامل مع SkypeOut®؟' ,
   'LBL_SKYPEOUT_TITLE' => 'SkypeOut®' ,
   'LBL_USE_REAL_NAMES' => 'اعرض الاسم الكامل (ليس تسجيل الدخول)' ,
   'LIST_ENTRIES_PER_LISTVIEW' => 'طريقة عرض القائمة للعناصر في كل صفحة' ,
   'LIST_ENTRIES_PER_SUBPANEL' => 'عناوين اللوحة الفرعية للصفحة' ,
   'LOG_MEMORY_USAGE' => 'سجل استخدام الذاكرة' ,
   'LOG_SLOW_QUERIES' => 'سجل  الإستعلامات البطيئة' ,
   'NEW_LOGO' => 'ارفع الشعار الجديد (212x40)' ,
   'NEW_QUOTE_LOGO' => 'ارفع الشعار الجديد للإقتباس (867x74)' ,
   'QUOTES_CURRENT_LOGO' => 'الشعر المستخدم في الإقتباسات ' ,
   'SLOW_QUERY_TIME_MSEC' => 'الحد الزمني للإستعلامات البطيئة بالملي ثانية' ,
   'STACK_TRACE_ERRORS' => 'غظهار قائمة تتبع المشكلات' ,
   'UPLOAD_MAX_SIZE' => 'الحد الأقصى للرفع' ,
   'VERIFY_CLIENT_IP' => 'تحقق من عنوان الشبكة الخاص بالمستخدم' ,
   'LOCK_HOMEPAGE' => 'منع المستخدم من تخصيص الشكل الخارجي للصفحة الرئيسية' ,
   'LOCK_SUBPANELS' => 'منع المستخدم من تخصيص الشكل الخارجي للقائمة الفرعية' ,
   'MAX_DASHLETS' => 'الحد الأقصى للمدونات الملصقة على الصفحة الرئيسية' ,
   'SYSTEM_NAME' => 'أسم النظام' ,
   'LBL_OC_STATUS' => 'حالة المستفيد دون إتصال التلقائي' ,
   'DEFAULT_OC_STATUS' => 'إتاحة المستفيد دون إتصال تلقائيا' ,
   'LBL_OC_STATUS_DESC' => 'أشر هنا إذا كنت تريد أي مستخدم يكون له صلاحية للمستفيد دون إتصال. و إلا يمكنك إعداد الصلاحيات على مستوى المستخدمين' ,
   'SESSION_TIMEOUT' => 'نم الخروج من جلسة الموقع' ,
   'SESSION_TIMEOUT_UNITS' => 'ثواني' ,
   'LBL_LDAP_TITLE' => 'دعم تحقيق الهوية باستخدام LDAP' ,
   'LBL_LDAP_ENABLE' => 'إتاحة LDAP' ,
   'LBL_LDAP_SERVER_HOSTNAME' => 'خادم:' ,
   'LBL_LDAP_SERVER_PORT' => 'رقم البورت:' ,
   'LBL_LDAP_ADMIN_USER' => 'مستخدم أصلي:' ,
   'LBL_LDAP_ADMIN_USER_DESC' => 'تستخدم للبحث عن مستخدم شوجر. \"أحيانا لابد أن يكون تام التفصيل\"  سوف يكون مجهول إن لم يتم تحديده' ,
   'LBL_LDAP_ADMIN_PASSWORD' => 'كلمة سر أصلية:' ,
   'LBL_LDAP_AUTO_CREATE_USERS' => 'إنشاء المستخدمين تلقائيا:' ,
   'LBL_LDAP_BASE_DN' => 'قاعدة DN:' ,
   'LBL_LDAP_LOGIN_ATTRIBUTE' => 'خاصية الدخول:' ,
   'LBL_LDAP_BIND_ATTRIBUTE' => 'الربط بخاصية :' ,
   'LBL_LDAP_BIND_ATTRIBUTE_DESC' => 'للربط بأمثلة المستخدم عن طريق بروتوكول LDAP :[AD: userPrincipalName] [openLDAP: userPrincipalName] [Mac OS X: uid]' ,
   'LBL_LDAP_LOGIN_ATTRIBUTE_DESC' => 'للبحث عن أمثلة المستخدم عن طريق بروتوكول LDAP :[AD: userPrincipalName] [openLDAP: userPrincipalName] [Mac OS X: uid]' ,
   'LBL_LDAP_SERVER_HOSTNAME_DESC' => 'مثال:  ldap.example.com' ,
   'LBL_LDAP_SERVER_PORT_DESC' => 'مثال: 389' ,
   'LBL_LDAP_BASE_DN_DESC' => 'مثال:  DC=SugarCRM,DC=com' ,
   'LBL_LDAP_AUTO_CREATE_USERS_DESC' => 'إذا لم يوجد مستخدم أصلي سينشئ واحد في شوجار.' );

?>
