<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Opportunities/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'فرص بيع' ,
   'LBL_MODULE_TITLE' => 'فرص: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في الفرص' ,
   'LBL_VIEW_FORM_TITLE' => 'مطالعة الفرصة' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الفرص' ,
   'LBL_OPPORTUNITY_NAME' => 'فرصة بيع:' ,
   'LBL_OPPORTUNITY' => 'فرصة:' ,
   'LBL_NAME' => 'فرصة بيع' ,
   'LBL_INVITEE' => 'جهات إتصال' ,
   'LBL_LIST_OPPORTUNITY_NAME' => 'فرصة' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_AMOUNT' => 'كمية' ,
   'LBL_LIST_DATE_CLOSED' => 'إغلاق' ,
   'LBL_LIST_SALES_STAGE' => 'مرحلة البيع' ,
   'LBL_ACCOUNT_ID' => 'هوية الحساب' ,
   'LBL_CURRENCY_ID' => 'هوية العملة' ,
   'LBL_TEAM_ID' => 'هوية الفريق' ,
   'db_sales_stage' => 'LBL_LIST_SALES_STAGE' ,
   'db_name' => 'LBL_NAME' ,
   'db_amount' => 'LBL_LIST_AMOUNT' ,
   'db_date_closed' => 'LBL_LIST_DATE_CLOSED' ,
   'UPDATE' => 'فرصة - تحديث عملة' ,
   'UPDATE_DOLLARAMOUNTS' => 'حدث أسعار الدولار الأمريكي' ,
   'UPDATE_VERIFY' => 'وافق على الأسعار' ,
   'UPDATE_VERIFY_TXT' => 'يوافق على أن قيم الأسعار في الفرص هي أعداد عشرية سليمة ذات علامات عددية فقط (0-9) وعلامات عشرية (.)' ,
   'UPDATE_FIX' => 'أصلح الأسعار' ,
   'UPDATE_FIX_TXT' => 'يحاول إصلاح أي أسعار غير صحيحة بإنشاء علامة عشرية صحيحة من السعر الحالي. سيقوم هذا بعمل نسخ احتياطية لأي أسعار يعدلها في حقل قاعدة البيانات \"amount_backup\". إذا شغلت هذا ولاحظت مشكلات، لا تعيد تشغيل هذا بدون الاستعادة من الاحتياطي حيث ربما أحل محل الاحتياطي ببيانات جديدة غير سليمة.' ,
   'UPDATE_DOLLARAMOUNTS_TXT' => 'حدث أسعار الدولار الأمريكي للفرص بناء على أسعار العملات الموضوعة حاليا. تستخدم هذه القيمة لحساب الأشكال البيانية وأسعار العملات الخاصة بقائمة المطالعة.' ,
   'UPDATE_CREATE_CURRENCY' => 'إنشاء عملة جديدة:' ,
   'UPDATE_VERIFY_FAIL' => 'لم ينجح تحقيق الحقل:' ,
   'UPDATE_VERIFY_CURAMOUNT' => 'السعر الحالي:' ,
   'UPDATE_VERIFY_FIX' => 'تشغيل الإصلاح سوف ينتج' ,
   'UPDATE_INCLUDE_CLOSE' => 'يحتوي على تسجيلات مغلقة' ,
   'UPDATE_VERIFY_NEWAMOUNT' => 'سعر جديد:' ,
   'UPDATE_VERIFY_NEWCURRENCY' => 'عملة جديدة:' ,
   'UPDATE_DONE' => 'تم' ,
   'UPDATE_BUG_COUNT' => 'عثر على مشكلات وتمت محاولة الحل:' ,
   'UPDATE_BUGFOUND_COUNT' => 'عثر على مشكلات' ,
   'UPDATE_COUNT' => 'تم تحديث التسجيلات:' ,
   'UPDATE_RESTORE_COUNT' => 'تمت استعادة أسعار التسجيلات:' ,
   'UPDATE_RESTORE' => 'استعد الأسعار' ,
   'UPDATE_RESTORE_TXT' => 'يستعيد قيم الأسعار من النسخ الاحتياطية المنشأة أثناء الإصلاح.' ,
   'UPDATE_FAIL' => 'لا يمكن التحديث ' ,
   'UPDATE_NULL_VALUE' => 'السعر معدوم، ضبطه على الصفر' ,
   'UPDATE_MERGE' => 'ادمج العملات' ,
   'UPDATE_MERGE_TXT' => 'ادمج العملات المتعددة في عملة واحدة. إذا لاحظت وجود تسجيلات عملات متعددة لنفس العملة، يمكنك اختيار دمجها معا. سيدمج هذا أيضا العملات لكل الوحدات.' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_AMOUNT' => 'كمية:' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LBL_DATE_CLOSED' => 'تاريخ الإغلاق المتوقع:' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_CAMPAIGN' => 'حملة:' ,
   'LBL_NEXT_STEP' => 'الخطوة التالية:' ,
   'LBL_LEAD_SOURCE' => 'مصدر عميل متوقع:' ,
   'LBL_SALES_STAGE' => 'مرحلة البيع:' ,
   'LBL_PROBABILITY' => 'الاحتمالية (%):' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_DUPLICATE' => 'فرصة متكررة محتملة' ,
   'MSG_DUPLICATE' => 'إنشاء هذه الفرصة يحتمل أن ينشئ فرصة متكررة. يمكنك إما أن تختار فرصة من القائمة أدناه أو أن تضغط على \"اضغط فرصة جديدة\" للاستمرار في إنشاء فرصة جديدة بالبيانات المدخلة سابقا.' ,
   'LBL_NEW_FORM_TITLE' => 'إنشاء فرصة' ,
   'LNK_NEW_OPPORTUNITY' => 'إنشاء فرصة' ,
   'LNK_OPPORTUNITY_REPORTS' => 'تقارير فرصة بيع' ,
   'LNK_OPPORTUNITY_LIST' => 'فرص بيع' ,
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم سجل لإلغاء الفرصة.' ,
   'LBL_TOP_OPPORTUNITIES' => 'الفرص المفتوحة عالية الأهمية' ,
   'NTC_REMOVE_OPP_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذا الاتصال من هذه الفرصة؟' ,
   'OPPORTUNITY_REMOVE_PROJECT_CONFIRM' => 'هل أنت متأكد أنك تريد إزالة هذه الفرصة من هذا المشروع؟' ,
   'LBL_AMOUNT_BACKUP' => 'النسخة الاحتياطية للسعر' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'فرص بيع' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_RAW_AMOUNT' => 'صف أسعار' ,
   'LBL_LEADS_SUBPANEL_TITLE' => 'عملاء متوقعين' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_QUOTES_SUBPANEL_TITLE' => 'إقتباسات' ,
   'LBL_PROJECTS_SUBPANEL_TITLE' => 'مشروعات' ,
   'LBL_ASSIGNED_TO_NAME' => 'إسم المستخدم المكلفبن:' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'LBL_CONTRACTS' => 'العقود' ,
   'LBL_CONTRACTS_SUBPANEL_TITLE' => 'العقود' );

?>
