<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlow/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'تعربفات سير العمل:' ,
   'LBL_MODULE_ID' => 'سير العمل' ,
   'LBL_MODULE_TITLE' => 'سير العمل: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في سير العمل' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة سير العمل' ,
   'LBL_NEW_FORM_TITLE' => 'إنشاء تعريف سير العمل' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_TYPE' => 'التنفيذ يحدث:' ,
   'LBL_LIST_BASE_MODULE' => 'الوحدة المستهدفة:' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_TYPE' => 'التنفيذ يحدث:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_BASE_MODULE' => 'الوحدة المستهدفة:' ,
   'LBL_LIST_ORDER' => 'ترتيب العملية:' ,
   'LBL_FROM_NAME' => 'من إسم:' ,
   'LBL_FROM_ADDRESS' => 'من العناوين:' ,
   'LNK_NEW_WORKFLOW' => 'إنشاء تعريف سير العمل' ,
   'LNK_WORKFLOW' => 'قائمة تعريفات سير العمل' ,
   'LBL_ALERT_TEMPLATES' => 'نماذج الإخطار' ,
   'LBL_CREATE_ALERT_TEMPLATE' => 'إنشئ نموذج تحذير:' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LBL_RECORD_TYPE' => 'ينطبق على:' ,
   'LBL_RELATED_MODULE' => 'الوحدة المتعلقة:' ,
   'LBL_PROCESS_LIST' => ' تسلسل سير العمل' ,
   'LNK_ALERT_TEMPLATES' => 'نماذج إنذار رسائل البريد الإلكتروني' ,
   'LNK_PROCESS_VIEW' => ' تسلسل سير العمل' ,
   'LBL_PROCESS_SELECT' => 'الرجاء إختيار وحدة:' ,
   'LBL_LACK_OF_TRIGGER_ALERT' => 'ملاحظة: يجب إنشاء منشط لعنصر سير العمل هذا كي يعمل.' ,
   'LBL_LACK_OF_NOTIFICATIONS_ON' => 'ملاحظة: يجب تفعيل الإبلاغات في الإدارة> إعدادات البريد الإلكتروني من أجل إرسال  الإنذارات' ,
   'LBL_FIRE_ORDER' => 'ترتيب المعالجة:' ,
   'LBL_RECIPIENTS' => 'المرسل إليهم' ,
   'LBL_INVITEES' => 'المدعوون' ,
   'LBL_INVITEE_NOTICE' => 'تنبيه، يجب إختيار على الأقل دعوة واحدة لإنشاء هذا ' ,
   'NTC_REMOVE_ALERT' => 'هل أنت متأكد أنك تريد إلغاء سير العمل هذا؟' ,
   'LBL_EDIT_ALT_TEXT' => 'أستخدم النص البسيط' ,
   'LBL_INSERT' => 'إدرج' ,
   'LBL_SELECT_OPTION' => 'الرجاء أختر أحد الإختيارات' ,
   'LBL_SELECT_VALUE' => 'يجب إختيار قيمة' ,
   'LBL_SELECT_MODULE' => 'الرجاء إختيار وحدة متعلقة' ,
   'LBL_SELECT_FILTER' => 'يجب إختيار حقل لتقوم بتنقية الوحدة المتعلقة بأستخدامه' );

?>
