<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Calendar/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_list_strings = array ( 
   'dom_cal_month' => array (
      '0' => '' ,
      '1' => 'يناير' ,
      '2' => 'فبراير' ,
      '3' => 'مارس' ,
      '4' => 'أبريل' ,
      '5' => 'مايو' ,
      '6' => 'يونيو' ,
      '7' => 'يوليو' ,
      '8' => 'أغسطس' ,
      '9' => 'سبتمبر' ,
      '10' => 'أكتوبر' ,
      '11' => 'نوفمبر' ,
      '12' => 'ديسمبر'   ),
   'dom_cal_month_long' => array (
      '0' => '' ,
      '1' => 'يناير' ,
      '2' => 'فبراير' ,
      '3' => 'مارس' ,
      '4' => 'أبريل' ,
      '5' => 'مايو' ,
      '6' => 'يونيه' ,
      '7' => 'يوليه' ,
      '8' => 'أغسطس' ,
      '9' => 'سبتمبر' ,
      '10' => 'أكتوبر' ,
      '11' => 'نوفمبر' ,
      '12' => 'ديسمبر'   ),
   'dom_cal_weekdays' => array (
      '0' => 'أحد' ,
      '1' => 'اثنين' ,
      '2' => 'ثلاثاء' ,
      '3' => 'أربعاء' ,
      '4' => 'خميس' ,
      '5' => 'جمعة' ,
      '6' => 'سبت'   ),
   'dom_cal_weekdays_long' => array (
      '0' => 'أحد' ,
      '1' => 'اثنين' ,
      '2' => 'ثلاثاء' ,
      '3' => 'أربعاء' ,
      '4' => 'خميس' ,
      '5' => 'جمعة' ,
      '6' => 'سبت'   ));
$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'الأجندة' ,
   'LBL_MODULE_TITLE' => 'الأجندة' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_APPOINTMENT' => 'إنشاء موعد' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_CALL_LIST' => 'مكالمات' ,
   'LNK_MEETING_LIST' => 'اجتماعات' ,
   'LNK_TASK_LIST' => 'مهام' ,
   'LNK_VIEW_CALENDAR' => 'اليوم' ,
   'LBL_MONTH' => 'شهر' ,
   'LBL_DAY' => 'يوم' ,
   'LBL_YEAR' => 'سنة' ,
   'LBL_WEEK' => 'أسبوع' ,
   'LBL_PREVIOUS_MONTH' => 'الشهر السابق' ,
   'LBL_PREVIOUS_DAY' => 'اليوم السابق' ,
   'LBL_PREVIOUS_YEAR' => 'السنة السابقة' ,
   'LBL_PREVIOUS_WEEK' => 'الأسبوع السابق' ,
   'LBL_NEXT_MONTH' => 'الشهر التالي' ,
   'LBL_NEXT_DAY' => 'اليوم التالي' ,
   'LBL_NEXT_YEAR' => 'السنة التالية' ,
   'LBL_NEXT_WEEK' => 'الأسبوع التالي' ,
   'LBL_AM' => 'AM' ,
   'LBL_PM' => 'PM' ,
   'LBL_SCHEDULED' => 'مجدول' ,
   'LBL_BUSY' => 'مشغول' ,
   'LBL_CONFLICT' => 'تعارض' ,
   'LBL_USER_CALENDARS' => 'تقاويم المستخدم الزمنية' ,
   'LBL_SHARED' => 'مشترك' ,
   'LBL_PREVIOUS_SHARED' => 'السابق' ,
   'LBL_NEXT_SHARED' => 'التالي' ,
   'LBL_SHARED_CAL_TITLE' => 'تقويم زمني مشترك' ,
   'LBL_USERS' => 'مستخدم' ,
   'LBL_REFRESH' => 'تحديث' ,
   'LBL_EDIT' => 'تحرير' ,
   'LBL_SELECT_USERS' => 'اختر مستخدمي التقويم الزمني' ,
   'LBL_FILTER_BY_TEAM' => 'قم بتنقية قائمة المستخدمين حسب الفريق:' );

?>
