<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/WorkFlowTriggerShells/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'شروط' ,
   'LBL_MODULE_TITLE' => 'منشطات سير العمل: الرئيسية' ,
   'LBL_MODULE_SECTION_TITLE' => 'عند تطبيق تلك الشروط' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في منشطات سير العمل' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة المنشطات' ,
   'LBL_NEW_FORM_TITLE' => 'إنشئ منشط' ,
   'LBL_LIST_NAME' => 'وصف:' ,
   'LBL_LIST_VALUE' => 'القيمة:' ,
   'LBL_LIST_TYPE' => 'النوع:' ,
   'LBL_LIST_EVAL' => 'Eval:' ,
   'LBL_LIST_FIELD' => 'حقل:' ,
   'LBL_NAME' => 'اسم المنشط:' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_EVAL' => 'تقييم المنشط:' ,
   'LBL_SHOW_PAST' => 'تحرير القيمة السابقة:' ,
   'LNK_NEW_TRIGGER' => 'إنشئ منشط' ,
   'LNK_TRIGGER' => 'منشطات سير العمل' ,
   'LBL_LIST_STATEMEMT' => 'نشط حدث على أساس الآتي: ' ,
   'LBL_FILTER_LIST_STATEMEMT' => 'نقي العناصر عل أساس الآتي: ' ,
   'NTC_REMOVE_TRIGGER' => 'هل أنت متأكد أنك نريد إلغاء هذا المنشط؟' ,
   'LNK_NEW_WORKFLOW' => 'إنشئ عملية سير عمل' ,
   'LNK_WORKFLOW' => 'عناصر سير العمل' ,
   'LBL_ALERT_TEMPLATES' => 'نماذج الإخطار' ,
   'LBL_TRIGGER' => 'متى' ,
   'LBL_FIELD' => 'حقل' ,
   'LBL_VALUE' => 'قيمة' ,
   'LBL_RECORD' => 'وحدة' ,
   'LBL_COMPARE_SPECIFIC_TITLE' => 'عند تغيير حقل في الوحدة المستهدفة  إلى أو من قيمة معينة' ,
   'LBL_COMPARE_SPECIFIC_PART' => 'تغير إلى أو من قيمة معينة' ,
   'LBL_COMPARE_CHANGE_TITLE' => 'عند تغيير حقل في الوحدة المستهدفة' ,
   'LBL_COMPARE_CHANGE_PART' => 'تغيرات' ,
   'LBL_COMPARE_COUNT_TITLE' => 'نشط عند عد معين' ,
   'LBL_COMPARE_ANY_TIME_TITLE' => 'لا يتغير الحقل في فترة زمنية معينة' ,
   'LBL_COMPARE_ANY_TIME_PART2' => 'لا يغير لأجل ' ,
   'LBL_COMPARE_ANY_TIME_PART3' => 'مدة معينة من الوقت' ,
   'LBL_FILTER_FIELD_TITLE' => 'عندما يحتووي حقل في الوحدت المستهدفة على قيمة محددة' ,
   'LBL_FILTER_FIELD_PART1' => 'نقي بأستخدام ' ,
   'LBL_FILTER_REL_FIELD_TITLE' => 'عند تغير الوحدة المستهدفة و في وحدة آخرى متعلقة حقل يحتوي على قيمة معينة' ,
   'LBL_FILTER_REL_FIELD_PART1' => 'حدد المتعلقات' ,
   'LBL_TRIGGER_RECORD_CHANGE_TITLE' => 'عند تغير الوحدة المستهدفة ' ,
   'LBL_FUTURE_TRIGGER' => 'حدد جديد' ,
   'LBL_PAST_TRIGGER' => 'حدد قديم' ,
   'LBL_COUNT_TRIGGER1' => 'مجموع' ,
   'LBL_COUNT_TRIGGER1_2' => 'تقارن بهذه الكمية' ,
   'LBL_MODULE' => 'وحدة' ,
   'LBL_COUNT_TRIGGER2' => 'نقي على أساس المتعلقات' ,
   'LBL_COUNT_TRIGGER2_2' => 'فقط' ,
   'LBL_COUNT_TRIGGER3' => 'نقي نحديدا على أساس' ,
   'LBL_COUNT_TRIGGER4' => 'نقي بالثانية' ,
   'LBL_NEW_FILTER_BUTTON_KEY' => 'F' ,
   'LBL_NEW_FILTER_BUTTON_TITLE' => 'إنشئ منقي [Alt+F]' ,
   'LBL_NEW_FILTER_BUTTON_LABEL' => 'إنشئ منقي' ,
   'LBL_NEW_TRIGGER_BUTTON_KEY' => 'T' ,
   'LBL_NEW_TRIGGER_BUTTON_TITLE' => 'إنشئ منشط [Alt+T]' ,
   'LBL_NEW_TRIGGER_BUTTON_LABEL' => 'إنشئ منشط' ,
   'LBL_LIST_FRAME_SEC' => 'منقي: ' ,
   'LBL_LIST_FRAME_PRI' => 'منشط: ' ,
   'LBL_TRIGGER_FILTER_TITLE' => 'منقيات المنشط' ,
   'LBL_TRIGGER_FORM_TITLE' => 'حدد شرط تنفيذ سير العمل' ,
   'LBL_FILTER_FORM_TITLE' => 'حدد شرط سير العمل' ,
   'LBL_SPECIFIC_FIELD' => 's حقل محدد' ,
   'LBL_APOSTROPHE_S' => 's ' ,
   'LBL_WHEN_VALUE1' => 'عندما تكون قيمة الحقل ' ,
   'LBL_WHEN_VALUE2' => 'عندما تكون قيمة ' ,
   'LBL_SELECT_OPTION' => 'الرجاء أختر أحد الإختيارات' ,
   'LBL_SELECT_TARGET_FIELD' => 'الرجاء أختر حقل مستهدف' ,
   'LBL_SELECT_TARGET_MOD' => 'الرجاء إختيار وحدة مستهدفة متعلقة' );

?>
