<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ReportMaker/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'تقارير المؤسسة' ,
   'LBL_MODULE_TITLE' => 'إنشئ تقرير:' ,
   'LBL_SEARCH_FORM_TITLE' => 'تقارير المؤسسة: البحث' ,
   'LBL_LIST_FORM_TITLE' => 'كل تقارير المؤسسة' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_QUERY_NAME' => 'إستعلام' ,
   'LBL_LIST_PUBLISHED' => 'تم النشر' ,
   'LBL_LIST_SCHEDULED' => 'مجدول' ,
   'LBL_LIST_TYPE' => 'النوع' ,
   'LBL_LIST_MODULE_TITLE' => 'وحدة' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_PARENT_DATASET' => 'مجموعة البيانات الرئيسية:' ,
   'LBL_QUERY_NAME' => 'أسم الإستعلام:' ,
   'LBL_TYPE' => 'نوع التقرير:' ,
   'LBL_SCHEDULED' => 'تقرير الجدول الزمني:' ,
   'LBL_PUBLISHED' => 'أنشر تقرير:' ,
   'LBL_NAME' => 'أسم التقرير:' ,
   'LBL_TITLE' => 'عنوان التقرير:' ,
   'LBL_TABLE_WIDTH' => 'عرض الجدول %:' ,
   'LBL_TABLE_HEIGHT' => 'أرتفاع الجدول %:' ,
   'LBL_FONT_SIZE' => 'حجم الخط:' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء المنتج' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LNK_LIST_REPORTMAKER' => 'قائمة تقارير المؤسسة' ,
   'LNK_NEW_REPORTMAKER' => 'إنشئ تقرير' ,
   'LNK_LIST_DATASET' => 'قائمة صيغ البيانات' ,
   'LNK_NEW_DATASET' => 'إنشئ صيغة بيانات' ,
   'LNK_NEW_CUSTOMQUERY' => 'إنشئ إستعلام مخصوص' ,
   'LNK_CUSTOMQUERIES' => 'إستعلامات مخصوصة' ,
   'LNK_NEW_QUERYBUILDER' => 'إنشئ إستعلام' ,
   'LNK_QUERYBUILDER' => 'باني الإستعلام' ,
   'LNK_ADVANCED_REPORTING' => 'تقديم  تقرير المؤسسة' ,
   'LBL_ALL_REPORTS' => 'كل التقارير' ,
   'LBL_ADD_DATA_SET' => 'أضف مجموعة بيانات جديدة' ,
   'LBL_EDIT_DATA_SET' => 'حدث مجموعة البيانات' ,
   'LBL_DATA_SET' => 'مجموعة بيانات:' ,
   'LBL_LIST_ORDER_Y' => 'تنسيب رأسي:' ,
   'LBL_LIST_ORDER_X' => 'تنسيب أفقي:' ,
   'LBL_REPORT_ALIGN' => 'ترتيب التقرير:' ,
   'LBL_ADD_BUTTON_TITLE' => 'أختر  [Alt+A]' ,
   'LBL_ADD_BUTTON_KEY' => 'A' ,
   'LBL_ADD_BUTTON_LABEL' => 'إختيار' ,
   'LBL_NEW_BUTTON_TITLE' => 'أضف [Alt+N]' ,
   'LBL_NEW_BUTTON_KEY' => 'N' ,
   'LBL_NEW_BUTTON_LABEL' => 'إنشئ جديد' ,
   'LBL_DETAILS_BUTTON_TITLE' => 'تفاصيل تقرير [Alt+D]' ,
   'LBL_DETAILS_BUTTON_KEY' => 'D' ,
   'LBL_DETAILS_BUTTON_LABEL' => 'تفاصيل التقرير' ,
   'LBL_EDIT_BUTTON_TITLE' => 'تحرير تقرير [Alt+E]' ,
   'LBL_EDIT_BUTTON_KEY' => 'N' ,
   'LBL_EDIT_BUTTON_LABEL' => 'تحرير التقرير' ,
   'LBL_RUN_BUTTON_TITLE' => 'تشغيل تقرير [Alt+R]' ,
   'LBL_RUN_BUTTON_KEY' => 'R' ,
   'LBL_RUN_BUTTON_LABEL' => 'تشغيل التقرير' ,
   'LNK_UP' => 'أعلى' ,
   'LNK_DOWN' => 'أسفل' ,
   'LBL_NONE' => 'غير مجدول' ,
   'LBL_SCHEDULE_EMAIL' => 'مجدول' ,
   'LBL_HELLO' => 'مرحبا' ,
   'LBL_SCHEDULED_REPORT_MSG_INTRO' => 'المرفق هو تقرير ينشأ ذاتيا يتم إرساله من تطبيق شوجر. هذا التقرير تم إنشاءه في ' ,
   'LBL_SCHEDULED_REPORT_MSG_BODY1' => ' و حفظ بأسم' ,
   'LBL_SCHEDULED_REPORT_MSG_BODY2' => 'إذا أردت تعديل إعدادات تقريرك، أدخل إلى تطبيق شوجر و أنقر على التيويب تقرير' );

?>
