<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EmailTemplates/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ADD_ANOTHER_FILE' => 'إضافة ملف آخر' ,
   'LBL_ADD_DOCUMENT' => 'أضف مستندا من مستندات شوجار' ,
   'LBL_ADD_FILE' => 'أضف ملفا' ,
   'LBL_ATTACHMENTS' => 'الملحقات' ,
   'LBL_BODY' => 'الموضوع:' ,
   'LBL_CLOSE' => 'إغلاق' ,
   'LBL_COLON' => ':' ,
   'LBL_CONTACT_AND_OTHERS' => 'جهة إتصال/ مدخل بيع/ عميل متوقع' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_EDIT_ALT_TEXT' => 'تحرير نص بسيط' ,
   'LBL_EMAIL_ATTACHMENT' => 'مرفقات البريد' ,
   'LBL_HTML_BODY' => 'الموضوع بصيغة إتش تي إم إل' ,
   'LBL_INSERT_VARIABLE' => 'إضافة متغير:' ,
   'LBL_INSERT_URL_REF' => 'أدرج الرابط المرجعي' ,
   'LBL_INSERT_TRACKER_URL' => 'أدرج متتبع الوصلة:' ,
   'LBL_INSERT' => 'إدرج' ,
   'LBL_LIST_DATE_MODIFIED' => 'آخر مرة تعديل' ,
   'LBL_LIST_DESCRIPTION' => 'وصف' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة قوالب البريد' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_MODULE_NAME' => 'قوالب بريدية' ,
   'LBL_MODULE_TITLE' => 'قوالب البريد: رئيسية' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_NEW_FORM_TITLE' => 'إنشاء قالب بريد إلكتروني' ,
   'LBL_PUBLISH' => 'انشر:' ,
   'LBL_RELATED_TO' => 'متعلق بـ:' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في قوالب البريد' ,
   'LBL_SHOW_ALT_TEXT' => 'اعرض نصا بسيطا' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LBL_TEAM' => 'فريق:' ,
   'LBL_TEAMS_LINK' => 'فريق' ,
   'LBL_TEXT_BODY' => 'موضوع النص' ,
   'LNK_ALL_EMAIL_LIST' => 'كل الرسائل' ,
   'LNK_ARCHIVED_EMAIL_LIST' => 'رسائل محالة إلى الأرشيف' ,
   'LNK_CHECK_EMAIL' => 'تفقد البريد' ,
   'LNK_DRAFTS_EMAIL_LIST' => 'كل المسودات' ,
   'LNK_EMAIL_TEMPLATE_LIST' => 'قوالب بريدية' ,
   'LNK_IMPORT_NOTES' => 'استورد ملاحظات' ,
   'LNK_NEW_ARCHIVE_EMAIL' => 'إنشاء بريدا في الأرشيف' ,
   'LNK_NEW_EMAIL_TEMPLATE' => 'إنشاء قالب بريد إلكتروني' ,
   'LNK_NEW_EMAIL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LNK_NEW_SEND_EMAIL' => 'كتابة رسالة إلكترونية' ,
   'LNK_SENT_EMAIL_LIST' => 'الرسائل التي خرجت' ,
   'LNK_VIEW_CALENDAR' => 'اليوم' ,
   'LBL_NEW' => 'جديد' ,
   'LNK_CHECK_MY_INBOX' => 'تفقد البريد الخاص بي' ,
   'LNK_GROUP_INBOX' => 'صندوق جماعي للبريد الوارد' ,
   'LNK_MY_ARCHIVED_LIST' => 'حافظات الأرشيف' ,
   'LNK_MY_DRAFTS' => 'المسودات الخاصة بي' ,
   'LNK_MY_INBOX' => 'صندوق البريد الوارد' ,
   'LBL_LIST_BASE_MODULE' => 'الوحدة الأساسية:' ,
   'LBL_MODULE_NAME_WORKFLOW' => 'نماذج سير العمل لرسائل البريد الإلكتروني' ,
   'LBL_DEFAULT_LINK_TEXT' => 'نص الوصلة التلقائي' ,
   'LBL_TEXT_ONLY' => 'نص فقط' ,
   'LBL_SEND_AS_TEXT' => 'إرسل نص فقط' ,
   'LBL_ACCOUNT' => 'حساب' );

?>
