<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Project/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'مشروع' ,
   'LBL_MODULE_TITLE' => 'مشاريع: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في المشاريع' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة المشاريع' ,
   'LBL_HISTORY_TITLE' => 'سيرة' ,
   'LBL_ID' => 'هوية:' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل:' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل:' ,
   'LBL_ASSIGNED_USER_ID' => 'كلف بها:' ,
   'LBL_MODIFIED_USER_ID' => 'هوية المستخدم المعدّل:' ,
   'LBL_CREATED_BY' => 'أنشئ بواسطة:' ,
   'LBL_TEAM_ID' => 'فريق:' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_DELETED' => 'تم الحذف:' ,
   'LBL_TOTAL_ESTIMATED_EFFORT' => 'الجهد المقدر الكلي (ساعات):' ,
   'LBL_TOTAL_ACTUAL_EFFORT' => 'الجهد الفعلي الكلي (ساعات):' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_ASSIGNED_USER_ID' => 'كلف بها' ,
   'LBL_LIST_TOTAL_ESTIMATED_EFFORT' => 'الجهد المقدر الكلي (ساعات)' ,
   'LBL_LIST_TOTAL_ACTUAL_EFFORT' => 'الجهد الفعلي الكلي (ساعات)' ,
   'LBL_PROJECT_SUBPANEL_TITLE' => 'مشروعات' ,
   'LBL_PROJECT_TASK_SUBPANEL_TITLE' => 'مهام المشروع' ,
   'LBL_CONTACT_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_ACCOUNT_SUBPANEL_TITLE' => 'حسابات' ,
   'LBL_OPPORTUNITY_SUBPANEL_TITLE' => 'فرص بيع' ,
   'LBL_QUOTE_SUBPANEL_TITLE' => 'إقتباسات' ,
   'CONTACT_REMOVE_PROJECT_CONFIRM' => 'هل أنت متأكد أنك تريد إزالة هذا الاتصال من هذا المشروع؟' ,
   'LNK_NEW_PROJECT' => 'إنشاء مشروعا' ,
   'LNK_PROJECT_LIST' => 'قائمة المشاريع' ,
   'LNK_NEW_PROJECT_TASK' => 'إنشاء مهمة خاصة بمشروع' ,
   'LNK_PROJECT_TASK_LIST' => 'مهام المشروع' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'مشروعات' ,
   'LBL_ACTIVITIES_TITLE' => 'أنشطة' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_QUICK_NEW_PROJECT' => 'مشروع جديد' ,
   'LBL_PROJECT_TASKS_SUBPANEL_TITLE' => 'مهام المشروع' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_ACCOUNTS_SUBPANEL_TITLE' => 'حسابات' ,
   'LBL_OPPORTUNITIES_SUBPANEL_TITLE' => 'فرص بيع' ,
   'LBL_QUOTES_SUBPANEL_TITLE' => 'إقتباسات' );

?>
