<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Contracts/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'العقود' ,
   'LBL_MODULE_TITLE' => 'عقود: الرئيسية' ,
   'LNK_NEW_CONTRACT' => 'إنشئ عقد' ,
   'LNK_CONTRACT_LIST' => 'قائمة العقود' ,
   'LBL_CONTRACT_NAME' => 'اسم العقد:' ,
   'LBL_REFERENCE_CODE' => 'الشفرة المرجعية:' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_OPPORTUNITY' => 'فرصة بيع:' ,
   'LBL_START_DATE' => 'تاريخ البدء:' ,
   'LBL_END_DATE' => 'تاريخ الانتهاء:' ,
   'LBL_TOTAL_CONTRACT_VALUE' => 'قيمة العقد:' ,
   'LBL_TOTAL_CONTRACT_VALUE_USDOLLAR' => 'قيمة العقد (USD):' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_CUSTOMER_SIGNED_DATE' => 'تاريخ توقيع العميل:' ,
   'LBL_COMPANY_SIGNED_DATE' => 'تاريخ توقيع الشركة:' ,
   'LBL_CONTRACT_TERM' => 'مدة العقد:' ,
   'LBL_EXPIRATION_NOTICE' => 'ملاحظة إنتهاء الصلاحية:' ,
   'LBL_TIME_TO_EXPIRY' => 'زمن اللإنتهاء:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_TEAM' => 'فريق:' ,
   'LBL_ASSIGNED_TO' => 'مكلف به:' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة العقد' ,
   'LBL_LIST_CONTRACT_NAME' => 'أسم العقد' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_START_DATE' => 'الأول' ,
   'LBL_LIST_END_DATE' => 'الأخير' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_TEAM_NAME' => 'فريق' ,
   'LBL_LIST_ASSIGNED_TO_USER' => 'مستخدم' ,
   'LBL_DAYS' => 'يوم' ,
   'LBL_UNDEFINED' => 'غير معرف' ,
   'LBL_NONE' => 'لاشئ' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في العقد' ,
   'LBL_SF_CONTRACT_NAME' => 'اسم العقد:' ,
   'LBL_SF_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_SF_STATUS' => 'الحالة:' ,
   'LBL_SF_CONTRACT_TYPE' => 'النوع:' ,
   'LBL_SF_START_DATE' => 'تاريخ البدء:' ,
   'LBL_SF_END_DATE' => 'تاريخ الانتهاء:' ,
   'LBL_SF_ASSIGNED_TO' => 'مكلف به:' ,
   'LBL_DOCUMENTS_SUBPANEL_TITLE' => 'مستندات' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_NOTES_SUBPANEL_TITLE' => 'ملاحظات' ,
   'LBL_PRODUCTS_SUBPANEL_TITLE' => 'منتجات' ,
   'LBL_QUOTES_SUBPANEL_TITLE' => 'إقتباسات' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_CONTRACT_VALUE' => 'القيمة' ,
   'LBL_TYPE' => 'النوع' ,
   'LBL_CONTRACT_TYPE' => 'النوع:' );

?>
