<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Products/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'منتجات' ,
   'LBL_MODULE_TITLE' => 'المنتجات: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في المنتجات' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة المنتجات' ,
   'LBL_NEW_FORM_TITLE' => 'إنشاء منتج' ,
   'LBL_PRODUCT' => 'منتج:' ,
   'LBL_RELATED_PRODUCTS' => 'المنتجات المتعلقة' ,
   'LBL_LIST_NAME' => 'منتج' ,
   'LBL_LIST_MANUFACTURER' => 'المصنع' ,
   'LBL_LIST_LBL_MFT_PART_NUM' => 'الرقم الخاص بالصانع' ,
   'LBL_LIST_QUANTITY' => 'كمية' ,
   'LBL_LIST_COST_PRICE' => 'التكلفة' ,
   'LBL_LIST_DISCOUNT_PRICE' => 'السعر' ,
   'LBL_LIST_LIST_PRICE' => 'قائمة' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_CONTACT_NAME' => 'اسم جهة الإتصال' ,
   'LBL_LIST_QUOTE_NAME' => 'أسم الإقتباس' ,
   'LBL_LIST_DATE_PURCHASED' => 'المشتراه' ,
   'LBL_LIST_SUPPORT_EXPIRES' => 'تنتهي الصلاحية' ,
   'LBL_NAME' => 'منتج:' ,
   'LBL_URL' => 'وصلة المنتج:' ,
   'LBL_QUOTE_NAME' => 'أسم الإقتباس:' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال:' ,
   'LBL_DATE_PURCHASED' => 'المشتراه:' ,
   'LBL_DATE_SUPPORT_EXPIRES' => 'نتهي صلاحية الدعم:' ,
   'LBL_DATE_SUPPORT_STARTS' => 'يبدأ الدعم:' ,
   'LBL_COST_PRICE' => 'التكلفة:' ,
   'LBL_DISCOUNT_PRICE' => 'وحدة السعر:' ,
   'LBL_LIST_PRICE' => 'سعر القائمة:' ,
   'LBL_VENDOR_PART_NUM' => 'رقم موزع القطعة:' ,
   'LBL_MFT_PART_NUM' => 'رقم جزء الخاص بالصانع:' ,
   'LBL_DISCOUNT_PRICE_DATE' => 'تاريخ خصم السعر:' ,
   'LBL_WEIGHT' => 'الوزن:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_CATEGORY' => 'فئة:' ,
   'LBL_QUANTITY' => 'كمية:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_TAX_CLASS' => 'فئة الضريبة:' ,
   'LBL_MANUFACTURER' => 'المصنع:' ,
   'LBL_SUPPORT_DESCRIPTION' => 'وصف الدعم:' ,
   'LBL_SUPPORT_TERM' => 'مدة الدعم:' ,
   'LBL_SUPPORT_NAME' => 'عنوان الدعم:' ,
   'LBL_SUPPORT_CONTACT' => 'جهة إتصال الدعم:' ,
   'LBL_PRICING_FORMULA' => 'صيغة التسعير:' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LNK_PRODUCT_LIST' => 'منتجات' ,
   'LNK_NEW_PRODUCT' => 'إنشاء منتج' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'NTC_REMOVE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء علاقة المنتج؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء المنتج' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LBL_ASSET_NUMBER' => 'الرقم الأصلي:' ,
   'LBL_SERIAL_NUMBER' => 'الرقم التسلسلي:' ,
   'LBL_BOOK_VALUE' => 'قيمة الكتاب:' ,
   'LBL_BOOK_VALUE_DATE' => 'تاريخ قيمة الكتاب:' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'منتجات' ,
   'LBL_RELATED_PRODUCTS_TITLE' => 'المنتجات المتعلقة' ,
   'LBL_WEBSITE' => 'موقع إنترنت' ,
   'LBL_COST_USDOLLAR' => 'التكلفة( دولار أمريكي)' ,
   'LBL_DISCOUNT_USDOLLAR' => 'خصم( دولار أمريكي)' ,
   'LBL_LIST_USDOLLAR' => 'قائمة الأسعار( دولار أمريكي)' ,
   'LBL_PRICING_FACTOR' => 'عامل التسعير' ,
   'LBL_ACCOUNT_ID' => 'هوية الحساب' ,
   'LBL_CONTACT_ID' => 'هوية جهة الإتصال' ,
   'LBL_CATEGORY_NAME' => 'أسم الفئة:' ,
   'LBL_NOTES_SUBPANEL_TITLE' => 'ملاحظات' ,
   'LBL_MEMBER_OF' => 'عضو من:' ,
   'LBL_CONTRACTS_SUBPANEL_TITLE' => 'العقود' ,
   'LBL_CONTRACTS' => 'العقود' ,
   'LBL_PRODUCT_CATEGORIES' => 'فئات النتج' ,
   'LBL_PRODUCT_TYPES' => 'أنواع المنتج' );

?>
