<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/CustomQueries/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'إستعلامات مخصوصة' ,
   'LBL_MODULE_TITLE' => 'إستعلامات مخصوصة' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في نوع المنتج' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة إستعلام مخصوص' ,
   'LBL_CUSTOMQUERY' => 'استعلام مخصوص:' ,
   'LBL_QUERY_TYPE' => 'نوع الإستعلام:' ,
   'LBL_LIST_NAME' => 'أسم الإستعلام' ,
   'LBL_LIST_DESCRIPTION' => 'وصف' ,
   'LBL_NAME' => 'أسم الإستعلام:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_LIST_LIST_ORDER' => 'ترتيب' ,
   'LBL_LIST_ORDER' => 'ترتيب:' ,
   'LBL_QUERY_LOCKED' => 'أغلق الإستعلام:' ,
   'LBL_LIST_VALID' => 'هل الإستعلام صحيح؟' ,
   'LNK_PRODUCT_LIST' => 'كتالوج المنتج' ,
   'LNK_REPORT_MAKER' => 'صانع التقرير' ,
   'LNK_NEW_SHIPPER' => 'مقدم خدمات الشحن' ,
   'LBL_RUN_QUERY' => 'تشغيل الإستعلام' ,
   'LNK_LIST_REPORTMAKER' => 'قائمة تقارير المؤسسة' ,
   'LNK_NEW_REPORTMAKER' => 'إنشئ تقرير' ,
   'LNK_LIST_DATASET' => 'قائمة صيغ البيانات' ,
   'LNK_NEW_DATASET' => 'إنشئ صيغة بيانات' ,
   'LNK_NEW_CUSTOMQUERY' => 'إنشئ إستعلام مخصوص' ,
   'LNK_CUSTOMQUERIES' => 'إستعلامات مخصوصة' ,
   'LNK_NEW_QUERYBUILDER' => 'إنشئ إستعلام' ,
   'LNK_QUERYBUILDER' => 'باني الإستعلام' ,
   'LBL_ALL_REPORTS' => 'كل التقارير' ,
   'LNK_NEW_PRODUCT_TYPE' => 'أنواع المنتج' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء نوع المنتج' ,
   'NTC_LIST_ORDER' => 'أعد ترتيب ظهور هذه الفئة في القوائم المنسدلة لفئة المنتج' ,
   'LNK_IMPORT_PRODUCT_CATEGORIES' => 'إستورد فئات منتج' ,
   'DUPBLANK_ERROR_MSG' => 'لديك أسم عمود فارغ أو أسم عمود مكرر' ,
   'QUERY_ERROR_MSG' => 'الإستعلام صحيح' ,
   'LBL_REPAIR_BUTTON_TITLE' => 'أصلح الإستعلام  [Alt+R]' ,
   'LBL_REPAIR_BUTTON_KEY' => 'R' ,
   'LBL_REPAIR_BUTTON_LABEL' => 'أصلح الإستعلام' ,
   'LBL_JSCRIPT_MULTI_MAP_ERROR' => 'الأعمدة المتعددة تم تعريفها بنفس اسم الحقل' ,
   'LBL_REMOVE_LAYOUT_DATA' => 'أحذف بيانات المخطط العام' ,
   'CHILD_ERROR_MSG' => 'هذا الإستعلام لا يمكن الوصول إليه إلا من خلال صيغة البيانات الأساسية' ,
   'ERROR_RESULT_MSG' => 'الإستعلام صحيح' ,
   'CHILD_RESULT_MSG' => 'لا يمكن تشغيل هذا الإستعلام  بشكل مستقل' );

?>
