<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/DynamicLayout/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ADVANCED' => 'متقدم:' ,
   'LBL_EDIT_IN_PLACE' => 'حرره في مكانه:' ,
   'DESC_USING_LAYOUT_TITLE' => 'باستخدام محرر الشكل الخارجي' ,
   'DESC_USING_LAYOUT_SHORTCUTS' => 'إختصارات:' ,
   'DESC_USING_LAYOUT_TOOLBAR' => 'شريط الأدوات:' ,
   'DESC_USING_LAYOUT_EDIT_ROWS' => 'صفوف التحرير:' ,
   'DESC_USING_LAYOUT_SELECT_FILE' => 'اختر ملفا:' ,
   'DESC_USING_LAYOUT_EDIT_FIELDS' => 'تحرير الشكل الخارجي:' ,
   'DESC_USING_LAYOUT_ADD_FIELD' => 'أضف حقلا:' ,
   'DESC_USING_LAYOUT_REMOVE_ITEM' => 'أزل عنصرا:' ,
   'DESC_USING_LAYOUT_DISPLAY_HTML' => 'اعرض ترميز إتش تي إم إل:' ,
   'DESC_USING_LAYOUT_BLK1' => 'محرر الشكل الخارجي يتيح لك إعادة ترتيب الحقول، عناصر القائمة الرئيسية، اللوحات على عناصر القائمة الرئيسية لتخصيص شاشتك لتناسب احتياجاتك. أولا اختر نمط الرؤية لتخصيص هذه الصفحة  من خلال اختيار ملف ، إختصار' ,
   'DESC_USING_LAYOUT_BLK2' => ' يسمح لك باختيار صفحة مختلفة لتحريرها؛ عمليات التحرير في الصفحة الحالية تفقد إذا لم تحفظ. إذا لم تكن متأكدا أي ملف تحرره يمكنك تفقد صندوق \"حرره في مكانه\"؛ سيضيف هذا صندوق تحرير لكل الأماكن القابلة للتحرير عبر التطبيق. تصفح التطبيق للوصول إلى الصفحة التي تريد تحريرها، اضغط على صندوق التحرير، وسوف تتم إعادتك لعرض التحرير لذلك الملف.
' ,
   'DESC_USING_LAYOUT_BLK3' => 'اسحب و أعد ترتيب الحقول الخاصة بك وعلاماتها. أختر مقبض العنصر ' ,
   'DESC_USING_LAYOUT_BLK4' => ' بجانب الحقل أو العلامة التي تريد تحرّيكها، انقر على مقبض العنصر حيث تريد الحقل أو العلامة أن يتواجد. هذه ستحرّك العنصر من موقعه السابق إلى موقعه الجديد. إذا كان هناك بالفعل حقل أو علامة في المكان الجديد، سوف يتبادل العنصران المواقع. تحريك اللوحات الفرعية تماما مثل تحريك الحقول انقر على مقبض اللوحة الفرعية المراد تحريكها وانقر على مقبض اللوحة الفرعية المراد التحريك إليها سوف يتم تبادل الاماكن. لكي يتم تحريك حقل أو إستمارة من الشاشة. اسحب العنصر إلى مكان صندوق الأدوات في يمين شريط القائمة' ,
   'DESC_USING_LAYOUT_BLK5' => ' يغيّر نمط الرؤية للسماح للإضافة وإزالة الصفوف في لوحة التفاصيل. الضغط على  + يضيف صفّ تحت الصف المختار، و الضغط على ؟ يزيل هذا الصف' ,
   'DESC_USING_LAYOUT_BLK6' => 'صندوق الأدوات يقدم منطقة عمل لإضافة حقول ومسميات جديدة لشكل، ويحتفظ مؤقتا بالعناصر التي تم حذفها من شكل ويتخلص من عناصر.
' ,
   'DESC_USING_LAYOUT_BLK7' => ' يفتح عرضا للاختيار لتحديد نوع الحقل الذي تريد إضافته والمسمى الذي يتفق معه. الضغط على زر \"أضف\" يضع الحقل الجديد ومسماه في منطقة عمل صندوق الأدوات. من هنا يمكن إضافة الحقل باختيار ماسِك العناصر الجديدة وماسِك المكان المنقولة إليه.' ,
   'DESC_USING_LAYOUT_BLK8' => ' كون قد تم بإختيار مقبضه والنقر على النصّ
 تسحب العناصر الغير مرغوبة هنا
هذه ستودع العناصر المختارة في مكان عمل صندوق الأدوات' ,
   'DESC_USING_LAYOUT_BLK9' => ' حقل إختيار يعرض الإتش تي إم إل الذي يشمل كلّ حقل. على الرغم من كونها غنيّة بالمعلومات ولكنها تستهلك وحدة المعالجة المركزية بشكل قوي، ويجب فقط أن تستعمل عند الضرورة فقط' ,
   'DESC_USING_LAYOUT_BLK10' => 'لحفظ التغييرات  أنقر زر احفظ الشكل الخارجي. لكي تهمل التغييرات أنقر لسانا آخر في التطبيق بهذا سوف يتم إهمال كل التغييرات في الصفحة التي كنت تحررها.' ,
   'NO_RECORDS_LISTVIEW' => 'لكي تقوم بتحرير نمط رؤية القائمة لابد من وجود صف واحد من البيانات على الأقل. من فضلك أنشئ سجلا لنمط رؤية القائمة قبل محاولة التحرير' ,
   'LBL_EDIT_LAYOUT' => 'تحرير الشكل الخارجي' ,
   'LBL_EDIT_ROWS' => 'صفوف التحرير' ,
   'LBL_EDIT_COLUMNS' => 'تحرير الأعمدة' ,
   'LBL_EDIT_LABELS' => 'تحرير المسميات' ,
   'LBL_EDIT_FIELDS' => 'تحرير الحقول المخصوصة' ,
   'LBL_ADD_FIELDS' => 'إضافة حقول مخصوصة' ,
   'LBL_DISPLAY_HTML' => 'اعرض ترميز إتش تي إم إل' ,
   'LBL_SELECT_FILE' => 'اختر ملفا' ,
   'LBL_SAVE_LAYOUT' => 'إختيار لوحة فرعية' ,
   'LBL_SELECT_A_SUBPANEL' => 'اختر لوحة' ,
   'LBL_SELECT_SUBPANEL' => 'اختر لوحة فرعية' ,
   'LBL_TOOLBOX' => 'صندوق الأدوات' ,
   'LBL_STAGING_AREA' => 'منطقة التجمع (اسحب وأسقط العناصر هنا)' ,
   'LBL_SUGAR_FIELDS_STAGE' => 'حقول شوجار (اضغط على العناصر لإضافتها لمنطقة التجمع)' ,
   'LBL_SUGAR_BIN_STAGE' => 'سلة شوجار (اضغط على العناصر لإضافتها لمنطقة التجمع)' ,
   'LBL_VIEW_SUGAR_FIELDS' => 'طالع حقول شوجار' ,
   'LBL_VIEW_SUGAR_BIN' => 'طالع سلة شوجار' );

?>
