<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Currencies/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'عملات' ,
   'LBL_LIST_FORM_TITLE' => 'عملات' ,
   'LBL_CURRENCY' => 'العملة' ,
   'LBL_ADD' => 'إضافة' ,
   'LBL_MERGE' => 'دمج' ,
   'LBL_MERGE_TXT' => 'من فضلك أشر على العملات التي تريد تحويلها إلى العملة المختارة. هذا سوف يحذف كل العملات التي لها علامة تأشير و وتحديد أي قيمة مرتبطة بها للعملة المختارة.' ,
   'LBL_US_DOLLAR' => 'دولار أمريكي' ,
   'LBL_DELETE' => 'حذف' ,
   'LBL_LIST_SYMBOL' => 'رمز العملة' ,
   'LBL_LIST_NAME' => 'اسم العملة' ,
   'LBL_LIST_ISO4217' => 'كود نظام الأيزو 4217' ,
   'LBL_UPDATE' => 'تحذيث' ,
   'LBL_LIST_RATE' => 'سعر التحويل' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LNK_NEW_CONTACT' => 'جهة إتصال جديدة' ,
   'LNK_NEW_ACCOUNT' => 'حساب جديد' ,
   'LNK_NEW_OPPORTUNITY' => 'فرصة جديدة' ,
   'LNK_NEW_CASE' => 'حالة جديدة' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_CALL' => 'مكالمة جديدة' ,
   'LNK_NEW_EMAIL' => 'بريد جديد' ,
   'LNK_NEW_MEETING' => 'اجتماع جديد' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد أنك تريد حذف هذا التسجيل؟ ربما يكون من الأفضل أن تضبط الحالة على عدم النشاط وإلا فإن أي تسجيل آخر يستخدم هذه العملة سيتم تحويله لعملة النظام التلقائية عندما يجري الوصول إليها.' ,
   'currency_status_dom' => array (
      'Active' => 'نشط' ,
      'Inactive' => 'غير نشط'   ));

?>
