<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/MergeRecords/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'ادمج التسجيلات' ,
   'LBL_MODULE_TITLE' => 'دمج التسجيلات: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في عمليات الدمج' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة بعمليات الدمج' ,
   'LBL_LBL_MERGRE_RECORDS_STEP_1' => 'خطوة 1: أعثر على تسجيلات عمليات البحث لتدمج بها' ,
   'LBL_AVAIL_FIELDS' => 'الحقول المتاحة' ,
   'LBL_SELECTED_FIELDS' => 'الحقول المختارة' ,
   'LBL_MERGE_RECORDS_WITH' => 'ادمج التسجيلات مع' ,
   'LBL_MERGE_VALUE_OVER' => 'دمج القيم أعلى من ' ,
   'LBL_NEXT_STEP_TITLE' => 'انتقل للخطوة التالية [Ctrl.N]' ,
   'LBL_NEXT_STEP_BUTTON_KEY' => 'N' ,
   'LBL_NEXT_STEP_BUTTON_LABEL' => 'الخطوة التالية >' ,
   'LBL_PERFORM_MERGE_BUTTON_TITLE' => 'قم بالدمج [Ctrl+P]' ,
   'LBL_PERFORM_MERGE_BUTTON_KEY' => 'P' ,
   'LBL_PERFORM_MERGE_BUTTON_LABEL' => 'قم بالدمج' ,
   'LBL_SAVE_MERGED_RECORD_BUTTON_TITLE' => 'حفظ الدمج [Ctrl+S]' ,
   'LBL_SAVE_MERGED_RECORD_BUTTON_KEY' => 'S' ,
   'LBL_SAVE_MERGED_RECORD_BUTTON_LABEL' => 'حفظ الدمج' ,
   'LBL_STEP2_FORM_TITLE' => 'التسجيلات التي عثر عليها للدمج:' ,
   'LBL_SELECT_ERROR' => 'لابد أن تختار قبل أن يمكنك متابعة الإجراء.' ,
   'LBL_SELECT_PRIMARY' => 'اختر التسجيل الرئيسي للدمج.' ,
   'LBL_CHANGE_PARENT' => 'اضبطه باعتباره رئيسيا' ,
   'LBL_REMOVE_FROM_MERGE' => 'إزاِلة' ,
   'LBL_DIFF_COL_VALUES' => 'الأعمدة التي قيمتها في الصف الرئيسي تختلف عن القيمة في صفوف الدمج:' ,
   'LBL_SAME_COL_VALUES' => 'الأعمدة التي قيمتها متشابهة عبر كل الصفوف:' ,
   'ERR_EXCEEDS_MAX' => 'مسموح لك فقط بدمج حد أقصى 5 تسجيلات. التسجيلات التي تتجاوز الحد تم تجاهلها.' ,
   'LBL_DELETE_MESSAGE' => 'هذا الإجراء سيلغي التسجيلات الآتية:' ,
   'LBL_PROCEED' => 'تابع؟' );

?>
