<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/TeamNotices/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'ملاحظات الفريق' ,
   'LBL_MODULE_TITLE' => 'ملاحظات الفريق: الرئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في ملاحظات الفريق' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة ملاحظات الفريق' ,
   'LBL_PRODUCTTYPE' => 'ملاحظة الفريق' ,
   'LBL_NOTICES' => 'ملاحظات الفريق' ,
   'LBL_LIST_NAME' => 'اللقب' ,
   'LBL_URL' => 'وصلة' ,
   'LBL_URL_TITLE' => 'عنوان الوصلة' ,
   'LBL_LIST_DESCRIPTION' => 'وصف' ,
   'LBL_NAME' => 'اللقب' ,
   'LBL_DESCRIPTION' => 'وصف' ,
   'LBL_LIST_LIST_ORDER' => 'ترتيب' ,
   'LBL_LIST_ORDER' => 'ترتيب' ,
   'LBL_DATE_START' => 'بدأ التاريخ' ,
   'LBL_DATE_END' => 'نهاية التاريخ' ,
   'LBL_STATUS' => 'الحالة' ,
   'LNK_NEW_TEAM' => 'إنشئ فريق' ,
   'LNK_NEW_TEAM_NOTICE' => 'إنشئ ملاحظة فريق' ,
   'LNK_LIST_TEAM' => 'فرق' ,
   'LNK_LIST_TEAMNOTICE' => 'ملاحظات الفريق' ,
   'LNK_PRODUCT_LIST' => 'قائمة أسعار المنتجات' ,
   'LNK_NEW_PRODUCT' => 'إنشاء منتج' ,
   'LNK_NEW_MANUFACTURER' => 'المصنعين' ,
   'LNK_NEW_SHIPPER' => 'مقدم خدمات الشحن' ,
   'LNK_NEW_PRODUCT_CATEGORY' => 'فئات النتج' ,
   'LNK_NEW_PRODUCT_TYPE' => 'قائمة أنواع المنتج' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء نوع المنتج' ,
   'NTC_LIST_ORDER' => 'أعد ترتيب هذا النوع في القوائم المنسدلة لقائمة المنتجات' ,
   'dom_status' => array (
      'Visible' => 'مرئي' ,
      'Hidden' => 'مخفي'   ));

?>
