<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ProductTemplates/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء المنتج' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_ASSIGNED_TO' => 'كلف بها:' ,
   'LBL_ASSIGNED_TO_ID' => 'مكلف لرقم الهوية:' ,
   'LBL_CATEGORY_NAME' => 'أسم الفئة:' ,
   'LBL_CATEGORY' => 'فئة:' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال:' ,
   'LBL_COST_PRICE' => 'التكلفة:' ,
   'LBL_COST_USDOLLAR' => 'تكلفة  USD:' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LBL_CURRENCY_SYMBOL_NAME' => 'رمز العملة:' ,
   'LBL_DATE_AVAILABLE' => 'التاريخ المتاح:' ,
   'LBL_DATE_COST_PRICE' => 'التاريخ - التكلفة - السعر:' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_DISCOUNT_PRICE_DATE' => 'تاريخ خصم السعر:' ,
   'LBL_DISCOUNT_PRICE' => 'سعر الخصم:' ,
   'LBL_DISCOUNT_USDOLLAR' => 'سعر خصم USD:' ,
   'LBL_LIST_CATEGORY' => 'فئة:' ,
   'LBL_LIST_CATEGORY_ID' => 'هوية الفئة:' ,
   'LBL_LIST_COST_PRICE' => 'التكلفة:' ,
   'LBL_LIST_DISCOUNT_PRICE' => 'السعر:' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة دليل المنتج' ,
   'LBL_LIST_LBL_MFT_PART_NUM' => 'الرقم الخاص بالصانع' ,
   'LBL_LIST_LIST_PRICE' => 'قائمة' ,
   'LBL_LIST_MANUFACTURER' => 'المصنع' ,
   'LBL_LIST_MANUFACTURER_ID' => 'هوية المصنع:' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_PRICE' => 'سعر القائمة:' ,
   'LBL_LIST_QTY_IN_STOCK' => 'Qty' ,
   'LBL_LIST_STATUS' => 'التوفر' ,
   'LBL_LIST_TYPE' => 'النوع:' ,
   'LBL_LIST_TYPE_ID' => 'هوية النوع:' ,
   'LBL_LIST_USDOLLAR' => 'قائمة USD:' ,
   'LBL_MANUFACTURER_NAME' => 'أسم المصنع:' ,
   'LBL_MANUFACTURER' => 'المصنع:' ,
   'LBL_MFT_PART_NUM' => 'رقم جزء الخاص بالصانع:' ,
   'LBL_MODULE_NAME' => 'كتالوج المنتج' ,
   'LBL_MODULE_ID' => 'نماذج المنتج' ,
   'LBL_MODULE_TITLE' => 'دليل النتج: الرئيسية' ,
   'LBL_NAME' => 'أسم المنتج:' ,
   'LBL_NEW_FORM_TITLE' => 'إنشئ عنصر' ,
   'LBL_PERCENTAGE' => 'نسبة مئوية(%)' ,
   'LBL_POINTS' => 'نقاط' ,
   'LBL_PRICING_FORMULA' => 'صيغة التسعير التلقائية:' ,
   'LBL_PRICING_FACTOR' => 'عامل التسعير:' ,
   'LBL_PRODUCT' => 'منتج:' ,
   'LBL_PRODUCT_ID' => 'هوية المنتج:' ,
   'LBL_QUANTITY' => 'الكمية في المخزن:' ,
   'LBL_RELATED_PRODUCTS' => 'المنتج المتعلقة' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في دليل المنتج' ,
   'LBL_STATUS' => 'التوفر:' ,
   'LBL_SUPPORT_CONTACT' => 'جهة إتصال الدعم:' ,
   'LBL_SUPPORT_DESCRIPTION' => 'وصف الدعم:' ,
   'LBL_SUPPORT_NAME' => 'أسم الدعم:' ,
   'LBL_SUPPORT_TERM' => 'مدة الدعم:' ,
   'LBL_TAX_CLASS' => 'فئة الضريبة:' ,
   'LBL_TYPE_NAME' => 'أسم النوع' ,
   'LBL_TYPE' => 'النوع:' ,
   'LBL_URL' => 'وصلة المنتج:' ,
   'LBL_VENDOR_PART_NUM' => 'رقم موزع القطعة:' ,
   'LBL_WEIGHT' => 'الوزن:' ,
   'LNK_IMPORT_PRODUCTS' => 'إستورد منتجات' ,
   'LNK_NEW_MANUFACTURER' => 'المصنعين' ,
   'LNK_NEW_PRODUCT_CATEGORY' => 'فئات النتج' ,
   'LNK_NEW_PRODUCT_TYPE' => 'أنواع المنتج' ,
   'LNK_NEW_PRODUCT' => 'إنشاء منتج' ,
   'LNK_NEW_SHIPPER' => 'مقدم خدمات الشحن' ,
   'LNK_PRODUCT_LIST' => 'كتالوج المنتج' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' );

?>
