<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Employees/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'موظفون' ,
   'LBL_MODULE_TITLE' => 'موظفون: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في الموظفين' ,
   'LBL_LIST_FORM_TITLE' => 'موظفون' ,
   'LBL_NEW_FORM_TITLE' => 'موظف جديد' ,
   'LBL_EMPLOYEE' => 'موظفون:' ,
   'LBL_LOGIN' => 'تسجيل دخول' ,
   'LBL_RESET_PREFERENCES' => 'أعد الضبط للتفضيلات التلقائية' ,
   'LBL_TIME_FORMAT' => 'صيغة الوقت:' ,
   'LBL_DATE_FORMAT' => 'صيغة التاريخ:' ,
   'LBL_TIMEZONE' => 'الوقت الحالي:' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_LAST_NAME' => 'اسم أخير' ,
   'LBL_LIST_EMPLOYEE_NAME' => 'اسم الموظف' ,
   'LBL_LIST_DEPARTMENT' => 'قسم' ,
   'LBL_LIST_REPORTS_TO_NAME' => 'تقارير لـ' ,
   'LBL_LIST_EMAIL' => 'بريد الكتروني' ,
   'LBL_LIST_PRIMARY_PHONE' => 'التليفون الرئيسي' ,
   'LBL_LIST_USER_NAME' => 'اسم المستخدم' ,
   'LBL_LIST_ADMIN' => 'إدارة' ,
   'LBL_NEW_EMPLOYEE_BUTTON_TITLE' => 'موظف جديد [Alt+N]' ,
   'LBL_NEW_EMPLOYEE_BUTTON_LABEL' => 'موظف جديد' ,
   'LBL_NEW_EMPLOYEE_BUTTON_KEY' => 'N' ,
   'LBL_ERROR' => 'خطأ:' ,
   'LBL_PASSWORD' => 'كمة سر:' ,
   'LBL_EMPLOYEE_NAME' => 'اسم الموظف:' ,
   'LBL_USER_NAME' => 'اسم المستخدم:' ,
   'LBL_FIRST_NAME' => 'اسم أول:' ,
   'LBL_LAST_NAME' => 'اسم أخير:' ,
   'LBL_EMPLOYEE_SETTINGS' => 'إعدادات الموظف' ,
   'LBL_THEME' => 'شكل البيئة:' ,
   'LBL_LANGUAGE' => 'لغة:' ,
   'LBL_ADMIN' => 'مدير:' ,
   'LBL_EMPLOYEE_INFORMATION' => 'معلومات الموظف' ,
   'LBL_OFFICE_PHONE' => 'تليفون المكتب:' ,
   'LBL_REPORTS_TO' => 'تقارير إلى:' ,
   'LBL_OTHER_PHONE' => 'غيره:' ,
   'LBL_OTHER_EMAIL' => 'بريد إلكتروني آخر:' ,
   'LBL_NOTES' => 'ملاحظات:' ,
   'LBL_DEPARTMENT' => 'قسم:' ,
   'LBL_TITLE' => 'اللقب:' ,
   'LBL_ANY_PHONE' => 'أي تليفون:' ,
   'LBL_ANY_EMAIL' => 'أي بريد إلكتروني:' ,
   'LBL_ADDRESS' => 'عنوان:' ,
   'LBL_CITY' => 'مدينة:' ,
   'LBL_STATE' => 'محافظة:' ,
   'LBL_POSTAL_CODE' => 'الرمز البريدي:' ,
   'LBL_COUNTRY' => 'بلد:' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_MOBILE_PHONE' => 'محمول:' ,
   'LBL_OTHER' => 'غيره:' ,
   'LBL_FAX' => 'فاكس:' ,
   'LBL_EMAIL' => 'بريد الكتروني:' ,
   'LBL_HOME_PHONE' => 'تليفون البريد:' ,
   'LBL_ADDRESS_INFORMATION' => 'بيانات العنوان' ,
   'LBL_EMPLOYEE_STATUS' => 'حالة الموظف:' ,
   'LBL_PRIMARY_ADDRESS' => 'العنوان الأساسي:' ,
   'LBL_CREATE_USER_BUTTON_TITLE' => 'إنشاء مستخدما [Alt+N]' ,
   'LBL_CREATE_USER_BUTTON_LABEL' => 'إنشاء مستخدم' ,
   'LBL_CREATE_USER_BUTTON_KEY' => 'N' ,
   'LBL_FAVORITE_COLOR' => 'اللون المفضل:' ,
   'LBL_MESSENGER_ID' => 'الاسم الخاص بالمراسل الفوري:' ,
   'LBL_MESSENGER_TYPE' => 'نوع المراسل الفوري:' ,
   'ERR_EMPLOYEE_NAME_EXISTS_1' => 'اسم الموظف ' ,
   'ERR_EMPLOYEE_NAME_EXISTS_2' => ' موجود بالفعل. الأسماء المتكررة للموظفين غير مسموح بها. غير اسم الموظف ليكون مختلفا.' ,
   'ERR_LAST_ADMIN_1' => 'اسم الموظف' ,
   'ERR_LAST_ADMIN_2' => 'هو/هي آخر موظف له صلاحية إدارية. لابد أن يكون موظف واحد على الأقل إداريا.' ,
   'LNK_NEW_EMPLOYEE' => 'إنشاء موظفا' ,
   'LNK_EMPLOYEE_LIST' => 'موظفون' ,
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم السجل للتمكن من حذف الحساب' ,
   'LBL_DEFAULT_TEAM' => 'الفريق التلقائي:' ,
   'LBL_DEFAULT_TEAM_TEXT' => 'أختر الفريق التلقائي للسجلات الجديدة' ,
   'LBL_MY_TEAMS' => 'الفرق الخاصة بي' ,
   'LBL_LIST_DESCRIPTION' => 'وصف' ,
   'LNK_EDIT_TABS' => 'تحرير عناصر القائمة الرئيسية' ,
   'NTC_REMOVE_TEAM_MEMBER_CONFIRMATION' => 'هل أنت متأكد أنك تريد إلغاء هذا الموظف أو عضويته؟' ,
   'LBL_LIST_EMPLOYEE_STATUS' => 'الحالة' );

?>
