<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Tasks/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'مهام' ,
   'LBL_TASK' => 'مهام: ' ,
   'LBL_MODULE_TITLE' => 'مهام: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => ' بحث في المهام' ,
   'LBL_LIST_FORM_TITLE' => ' قائمة المهام' ,
   'LBL_NEW_FORM_TITLE' => ' إنشاء مهمة' ,
   'LBL_NEW_FORM_SUBJECT' => 'الموضوع:' ,
   'LBL_NEW_FORM_DUE_DATE' => 'مطلوب بتاريخ:' ,
   'LBL_NEW_FORM_DUE_TIME' => 'الوقت المطلوب فيه:' ,
   'LBL_NEW_TIME_FORMAT' => '(24:00)' ,
   'LBL_LIST_CLOSE' => 'إغلاق' ,
   'LBL_LIST_SUBJECT' => 'الموضوع' ,
   'LBL_LIST_CONTACT' => 'جهة إتصال' ,
   'LBL_LIST_PRIORITY' => 'أولوية' ,
   'LBL_LIST_RELATED_TO' => 'متعلق ب' ,
   'LBL_LIST_DUE_DATE' => 'مطلوب بتاريخ' ,
   'LBL_LIST_DUE_TIME' => 'الوقت المطلوب فيه' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_DUE_DATE' => 'مطلوب بتاريخ:' ,
   'LBL_DUE_TIME' => 'الوقت المطلوب فيه:' ,
   'LBL_PRIORITY' => 'أولوية:' ,
   'LBL_COLON' => ':' ,
   'LBL_DUE_DATE_AND_TIME' => 'مطلوب بتاريخ وفي وقت:' ,
   'LBL_START_DATE_AND_TIME' => 'تاريخ وزمن البدء:' ,
   'LBL_START_DATE' => 'تاريخ البدء:' ,
   'LBL_LIST_START_DATE' => 'تاريخ البدء' ,
   'LBL_START_TIME' => 'زمن البدء:' ,
   'LBL_LIST_START_TIME' => 'زمن البدء' ,
   'DATE_FORMAT' => '(yyyy-mm-dd)' ,
   'LBL_NONE' => 'لاشئ' ,
   'LBL_CONTACT' => 'جهة إتصال:' ,
   'LBL_PHONE' => 'تليفون:' ,
   'LBL_EMAIL' => 'بريد الكتروني:' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال: ' ,
   'LBL_LIST_COMPLETE' => 'إكتمل:' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_DATE_DUE_FLAG' => 'لا يوجد تاريخ مطلوب فيه' ,
   'LBL_DATE_START_FLAG' => 'لا يوجد تاريخ بدء' ,
   'ERR_DELETE_RECORD' => 'من الضروري تحديد رقم سجل لإلغاء اتصال ' ,
   'ERR_INVALID_HOUR' => 'الرجاءإدخال ساعة من 0 إلى 24' ,
   'LBL_DEFAULT_STATUS' => 'لم يبدأ' ,
   'LBL_DEFAULT_PRIORITY' => 'متوسط' ,
   'LBL_LIST_MY_TASKS' => 'المهام المفتوحة' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_EMAIL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LNK_CALL_LIST' => 'مكالمات' ,
   'LNK_MEETING_LIST' => 'اجتماعات' ,
   'LNK_TASK_LIST' => 'مهام' ,
   'LNK_NOTE_LIST' => 'ملاحظات' ,
   'LNK_EMAIL_LIST' => 'رسائل إلكترونية' ,
   'LNK_VIEW_CALENDAR' => 'اليوم' ,
   'LBL_CONTACT_FIRST_NAME' => 'الإسم الأول لجهة الإتصال' ,
   'LBL_CONTACT_LAST_NAME' => 'الإسم الأخير لجهة الإتصال' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' );

?>
