<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Meetings/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم سجل لحذف الاجتماع' ,
   'LBL_ACCEPT_THIS' => 'قبول؟' ,
   'LBL_ADD_BUTTON' => 'إضافة' ,
   'LBL_ADD_INVITEE' => 'أضف مدعوين' ,
   'LBL_COLON' => ':' ,
   'LBL_CONTACT_NAME' => 'جهة إتصال:' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_CREATED_BY' => 'أنشأه' ,
   'LBL_DATE_END' => 'نهاية التاريخ' ,
   'LBL_DATE_TIME' => 'تاريخ وزمن البدء:' ,
   'LBL_DATE' => 'تاريخ البدء:' ,
   'LBL_DEFAULT_STATUS' => 'مخطط' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'اجتماعات' ,
   'LBL_DEL' => 'إحذف' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_DURATION_HOURS' => 'ساعات المدة الزمنية:' ,
   'LBL_DURATION_MINUTES' => 'دقائق المدة الزمنية:' ,
   'LBL_DURATION' => 'المدة الزمنية:' ,
   'LBL_EMAIL' => 'بريد الكتروني' ,
   'LBL_FIRST_NAME' => 'اسم أول' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'ملاحظات' ,
   'LBL_HOURS_ABBREV' => 'س' ,
   'LBL_HOURS_MINS' => '(دقائق/ساعات)' ,
   'LBL_INVITEE' => 'المدعوون' ,
   'LBL_LAST_NAME' => 'اسم أخير' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'LBL_LIST_CLOSE' => 'إغلاق' ,
   'LBL_LIST_CONTACT' => 'جهة إتصال' ,
   'LBL_LIST_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_LIST_DATE' => 'تاريخ البدء' ,
   'LBL_LIST_DUE_DATE' => 'مطلوب بتاريخ' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الاجتماعات' ,
   'LBL_LIST_MY_MEETINGS' => 'الإجتماعات الخاصة بي' ,
   'LBL_LIST_RELATED_TO' => 'متعلق ب' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_SUBJECT' => 'الموضوع' ,
   'LBL_LIST_TIME' => 'زمن البدء' ,
   'LBL_LOCATION' => 'المكان:' ,
   'LBL_MEETING' => 'اجتماع:' ,
   'LBL_MINSS_ABBREV' => 'د' ,
   'LBL_MODIFIED_BY' => 'عدّله' ,
   'LBL_MODULE_NAME' => 'اجتماعات' ,
   'LBL_MODULE_TITLE' => 'اجتماعات: رئيسية' ,
   'LBL_NAME' => 'اسم' ,
   'LBL_NEW_FORM_TITLE' => 'جدولة الاجتماع' ,
   'LBL_OUTLOOK_ID' => 'هوية أوتلوك' ,
   'LBL_PHONE' => 'تليفون المكتب:' ,
   'LBL_REMINDER_TIME' => 'زمن التذكير' ,
   'LBL_REMINDER' => 'منبه المواعيد:' ,
   'LBL_SCHEDULING_FORM_TITLE' => 'جدولة' ,
   'LBL_SEARCH_BUTTON' => 'بحث' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في الاجتماعات' ,
   'LBL_SEND_BUTTON_KEY' => 'I' ,
   'LBL_SEND_BUTTON_LABEL' => 'إرسال دعوات' ,
   'LBL_SEND_BUTTON_TITLE' => 'إرسال دعوات [Alt+I]' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LBL_TIME' => 'زمن البدء:' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'المستخدمين' ,
   'LNK_CALL_LIST' => 'مكالمات' ,
   'LNK_EMAIL_LIST' => 'رسائل إلكترونية' ,
   'LNK_MEETING_LIST' => 'اجتماعات' ,
   'LNK_NEW_APPOINTMENT' => 'إنشاء موعد' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_EMAIL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_NOTE_LIST' => 'ملاحظات' ,
   'LNK_TASK_LIST' => 'مهام' ,
   'LNK_VIEW_CALENDAR' => 'اليوم' ,
   'NTC_REMOVE_INVITEE' => 'هل أنت متأكد من أنك تريد إلغاء هؤلاء المدعوون من الاجتماع' );

?>
