<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EmailMarketing/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'تسويق بريدي' ,
   'LBL_MODULE_TITLE' => 'تسويق بريدي: رئيسية' ,
   'LBL_LIST_FORM_TITLE' => 'حملات التسويق البريدي' ,
   'LBL_NAME' => 'اسم: ' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_FROM_ADDR' => 'من بريد إلكتروني' ,
   'LBL_LIST_DATE_START' => 'تاريخ البدء' ,
   'LBL_LIST_TEMPLATE_NAME' => 'قالب بريدي' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_STATUS' => 'الحالة' ,
   'LBL_STATUS_TEXT' => 'الحالة:' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_MODIFIED' => 'عدّله: ' ,
   'LBL_CREATED' => 'أنشأه: ' ,
   'LBL_MESSAGE_FOR' => 'إرسال هذه الرسالة إلى:' ,
   'LBL_MESSAGE_FOR_ID' => 'رسالة لكي' ,
   'LBL_FROM_NAME' => 'من إسم: ' ,
   'LBL_FROM_ADDR' => 'من عنوان بريد إلكتروني: ' ,
   'LBL_DATE_START' => 'تاريخ البدء' ,
   'LBL_TIME_START' => 'زمن البدء' ,
   'LBL_START_DATE_TIME' => 'تاريخ وزمن البدء: ' ,
   'LBL_TEMPLATE' => 'قالب بريدي: ' ,
   'LBL_MODIFIED_BY' => 'عدّله: ' ,
   'LBL_CREATED_BY' => 'أنشأه: ' ,
   'LBL_DATE_CREATED' => 'تاريخ الإنشاء: ' ,
   'LBL_DATE_LAST_MODIFIED' => 'تاريخ التعديل: ' ,
   'LNK_NEW_CAMPAIGN' => 'إنشاء حملة' ,
   'LNK_CAMPAIGN_LIST' => 'حملات' ,
   'LNK_NEW_PROSPECT_LIST' => 'إنشاء القائمة المستهدفة' ,
   'LNK_PROSPECT_LIST_LIST' => 'القوائم المستهدفة' ,
   'LNK_NEW_PROSPECT' => 'إنشاء هدفا' ,
   'LNK_PROSPECT_LIST' => 'أهداف' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'تسويق بريدي' ,
   'LBL_CREATE_EMAIL_TEMPLATE' => 'إنشاء' ,
   'LBL_EDIT_EMAIL_TEMPLATE' => 'تحرير' ,
   'LBL_FROM_MAILBOX' => 'من صندوق بريد' ,
   'LBL_FROM_MAILBOX_NAME' => 'استخدم صندوق البريد:' ,
   'LBL_PROSPECT_LIST_SUBPANEL_TITLE' => 'القوائم المستهدفة' ,
   'LBL_ALL_PROSPECT_LISTS' => 'كل القوائم المستهدفة في الحملة' ,
   'LBL_RELATED_PROSPECT_LISTS' => 'كل القوائم المستهدفة المتعلقة بهذه الرسالة' ,
   'LBL_PROSPECT_LIST_NAME' => 'إسم قائمة الأهداف' ,
   'LBL_LIST_PROSPECT_LIST_NAME' => 'القوائم المستهدفة' ,
   'LBL_MODULE_SEND_TEST' => 'حملة: إرسال تجربة' ,
   'LBL_MODULE_SEND_EMAILS' => 'حملة: أرسل رسائل بريد إلكتروني' ,
   'LBL_SCHEDULE_MESSAGE_TEST' => 'من فضلك اختر رسائل الحملة التي ترغب في إرسالها كتجربة:' ,
   'LBL_SCHEDULE_MESSAGE_EMAILS' => 'من فضلك اختر رسائل الحملة التي ترغب في جدولتها للإرسال في تاريخ وزمن بدء معين:' ,
   'LBL_SCHEDULE_BUTTON_TITLE' => 'إرسال' ,
   'LBL_SCHEDULE_BUTTON_LABEL' => 'إرسال' ,
   'LBL_SCHEDULE_BUTTON_KEY' => 'T' );

?>
