<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ACLActions/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ACCESS_ALL' => 'الكل' ,
   'LBL_ACCESS_NONE' => 'لاشئ' ,
   'LBL_ACCESS_OWNER' => 'المالك' ,
   'LBL_ACCESS_NORMAL' => 'معتاد' ,
   'LBL_ACCESS_ADMIN' => 'إدارة' ,
   'LBL_ACCESS_ENABLED' => 'متاح' ,
   'LBL_ACCESS_DISABLED' => 'موقوف' ,
   'LBL_NAME' => 'اسم' ,
   'LBL_DESCRIPTION' => 'وصف' ,
   'LIST_ROLES' => 'اذكر الصلاحيات' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'المستخدمين' ,
   'LIST_ROLES_BY_USER' => 'اذكر الصلاحيات بترتيب المستخدمين' ,
   'LBL_ROLES_SUBPANEL_TITLE' => 'صلاحيات المستحدمين' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث' ,
   'LBL_ACTION_VIEW' => 'إظهار' ,
   'LBL_ACTION_EDIT' => 'تحرير' ,
   'LBL_ACTION_DELETE' => 'حذف' ,
   'LBL_ACTION_IMPORT' => 'إستيراد' ,
   'LBL_ACTION_EXPORT' => 'تصديّر' ,
   'LBL_ACTION_LIST' => 'قائمة' ,
   'LBL_ACTION_ACCESS' => 'وصول' ,
   'LBL_ACTION_ADMIN' => 'تصنيف المستخدم' ,
   'LBL_ACCESS_DEFAULT' => 'الإفتراضي' );

?>
