<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Notes/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم السجل للتمكن من حذف الحساب' ,
   'LBL_ACCOUNT_ID' => 'هوية الحساب:' ,
   'LBL_CASE_ID' => 'هوية الحالة:' ,
   'LBL_CLOSE' => 'إغلاق' ,
   'LBL_COLON' => ':' ,
   'LBL_CONTACT_ID' => 'هوية جهة الإتصال:' ,
   'LBL_CONTACT_NAME' => 'جهة إتصال:' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'ملاحظات' ,
   'LBL_DESCRIPTION' => 'وصف' ,
   'LBL_EMAIL_ADDRESS' => 'عنوان البريد الإلكتروني:' ,
   'LBL_FILE_MIME_TYPE' => 'نوع Mime' ,
   'LBL_FILE_URL' => 'رابط الملف' ,
   'LBL_FILENAME' => 'مرفق:' ,
   'LBL_LEAD_ID' => 'هويه العميل المتوقع:' ,
   'LBL_LIST_CONTACT_NAME' => 'جهة إتصال' ,
   'LBL_LIST_DATE_MODIFIED' => 'آخر مرة تعديل' ,
   'LBL_LIST_FILENAME' => 'مرفق' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة ملاحظات' ,
   'LBL_LIST_RELATED_TO' => 'متعلق بـ' ,
   'LBL_LIST_SUBJECT' => 'الموضوع' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_CONTACT' => 'جهة إتصال' ,
   'LBL_MODULE_NAME' => 'ملاحظات' ,
   'LBL_MODULE_TITLE' => 'ملاحظات: رئيسية' ,
   'LBL_NEW_FORM_TITLE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LBL_NOTE_STATUS' => 'ملاحظة' ,
   'LBL_NOTE_SUBJECT' => 'موضوع الملاحظة:' ,
   'LBL_NOTES_SUBPANEL_TITLE' => 'الملحقات' ,
   'LBL_NOTE' => 'ملاحظة:' ,
   'LBL_OPPORTUNITY_ID' => 'هوية الفرصة:' ,
   'LBL_PARENT_ID' => 'هوية أم:' ,
   'LBL_PARENT_TYPE' => 'نوعية أم' ,
   'LBL_PHONE' => 'تليفون:' ,
   'LBL_PORTAL_FLAG' => 'اعرض في الموقع الإلكترونى؟' ,
   'LBL_EMBED_FLAG' => 'هل تضمن في رسالة البريد الإلكتروني؟' ,
   'LBL_PRODUCT_ID' => 'هوية المنتج:' ,
   'LBL_QUOTE_ID' => 'هوية الإقتباس:' ,
   'LBL_RELATED_TO' => 'متعلق بـ:' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في الملاحظات' ,
   'LBL_STATUS' => 'الحالة' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LNK_CALL_LIST' => 'مكالمات' ,
   'LNK_EMAIL_LIST' => 'رسائل إلكترونية' ,
   'LNK_IMPORT_NOTES' => 'استورد ملاحظات' ,
   'LNK_MEETING_LIST' => 'اجتماعات' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_EMAIL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_NOTE_LIST' => 'ملاحظات' ,
   'LNK_TASK_LIST' => 'مهام' ,
   'LNK_VIEW_CALENDAR' => 'اليوم' ,
   'LBL_MEMBER_OF' => 'عضو من:' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'LBL_OC_FILE_NOTICE' => 'الرجاء الدخول إلى الخادم لأستعراض الملف' ,
   'LBL_REMOVING_ATTACHMENT' => 'إلغاء المرفقات ....' ,
   'ERR_REMOVING_ATTACHMENT' => 'فشل في إلغاء المرفقات.....' );

?>
