<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EditCustomFields/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'تحرير الحقول المخصوصة' ,
   'LBL_ADD_FIELD' => 'أضف حقلا:' ,
   'LBL_MODULE_TITLE' => 'تحرير الحقول المخصوصة' ,
   'LBL_MODULE_SELECT' => 'الوحدة المراد تحريرها' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث عن وحدة' ,
   'COLUMN_TITLE_NAME' => 'اسم الحقل' ,
   'COLUMN_TITLE_LABEL' => 'مسمى الحقل' ,
   'COLUMN_TITLE_DATA_TYPE' => 'نوع التاريخ' ,
   'COLUMN_TITLE_MAX_SIZE' => 'أقصى حجم' ,
   'COLUMN_TITLE_HELP_TEXT' => 'نص المساعدة' ,
   'COLUMN_TITLE_REQUIRED_OPTION' => 'حقل ضروري' ,
   'COLUMN_TITLE_DEFAULT_VALUE' => 'قيمة افتراضية' ,
   'COLUMN_TITLE_DEFAULT_EMAIL' => 'قيمة افتراضية' ,
   'COLUMN_TITLE_EXT1' => 'حقل بيانات الإعداد الزائدة 1' ,
   'COLUMN_TITLE_EXT2' => 'حقل بيانات الإعداد الزائدة 2' ,
   'COLUMN_TITLE_EXT3' => 'حقل بيانات الإعداد الزائدة 3' ,
   'COLUMN_TITLE_HTML_CONTENT' => 'أتش تي أم أل' ,
   'COLUMN_TITLE_URL' => 'الوصلة الإفتراضية' ,
   'COLUMN_TITLE_AUDIT' => 'مراجعة؟' ,
   'COLUMN_TITLE_MIN_VALUE' => 'أدنى قيمة' ,
   'COLUMN_TITLE_MAX_VALUE' => 'أقصى قيمة' ,
   'COLUMN_TITLE_DISPLAYED_ITEM_COUNT' => '# العناصر المعروضة' ,
   'LBL_DROP_DOWN_LIST' => 'قائمة منسدلة' ,
   'LBL_RADIO_FIELDS' => 'حقول الإختيار من متعدد' ,
   'LBL_MULTI_SELECT_LIST' => 'قائمة الاختيار المتعدد' ,
   'COLUMN_TITLE_PRECISION' => 'دقة' ,
   'MSG_DELETE_CONFIRM' => 'هل أنت متأكد أنك تريد حذف هذا العنصر؟' ,
   'POPUP_INSERT_HEADER_TITLE' => 'إضافة حقل مخصوص' ,
   'POPUP_EDIT_HEADER_TITLE' => 'تحرير حقل مخصوص' ,
   'LNK_SELECT_CUSTOM_FIELD' => 'اختر الحقول المخصوصة' ,
   'LNK_REPAIR_CUSTOM_FIELD' => 'إصلاح الحقول المخصوصة' ,
   'LBL_MODULE' => 'وحدة' ,
   'COLUMN_TITLE_MASS_UPDATE' => 'التحديث المجمع' ,
   'COLUMN_TITLE_DUPLICATE_MERGE' => 'دمج المتكرر' ,
   'LBL_LABEL' => 'مسمى' ,
   'LBL_DATA_TYPE' => 'نوع التاريخ' ,
   'LBL_DEFAULT_VALUE' => 'قيمة افتراضية' ,
   'LBL_AUDITED' => 'مراجعة' );

?>
