<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Cases/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم السجل للتمكن من حذف الحساب' ,
   'LBL_ACCOUNT_ID' => 'هوية الحساب' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_BUGS_SUBPANEL_TITLE' => 'مشكلات' ,
   'LBL_CASE_NUMBER' => 'رقم الحالة:' ,
   'LBL_CASE_SUBJECT' => 'موضوع الحالة:' ,
   'LBL_CASE' => 'حالة:' ,
   'LBL_CONTACT_CASE_TITLE' => 'حالة جهة الإتصال:' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال:' ,
   'LBL_CONTACT_ROLE' => 'صلاحية:' ,
   'LBL_CONTACTS_SUBPANEL_TITLE' => 'جهات إتصال' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'حالات' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_INVITEE' => 'جهات إتصال' ,
   'LBL_MEMBER_OF' => 'حساب' ,
   'LBL_MODULE_NAME' => 'حالات' ,
   'LBL_MODULE_TITLE' => 'حالات: الرئيسية' ,
   'LBL_NEW_FORM_TITLE' => 'حالة جديدة' ,
   'LBL_NUMBER' => 'رقم:' ,
   'LBL_PRIORITY' => 'أولوية:' ,
   'LBL_RESOLUTION' => 'حل المشكلة:' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث عن حالة' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LBL_SYSTEM_ID' => 'هوية النظام' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_ASSIGNED' => 'كلف بها' ,
   'LBL_LIST_CLOSE' => 'إغلاق' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الحالات' ,
   'LBL_LIST_LAST_MODIFIED' => 'آخر مرة تعديل' ,
   'LBL_LIST_MY_CASES' => 'الحالات المفتوحة' ,
   'LBL_LIST_NUMBER' => 'رقم' ,
   'LBL_LIST_PRIORITY' => 'أولوية' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_SUBJECT' => 'الموضوع' ,
   'LNK_CASE_LIST' => 'حالات' ,
   'LNK_NEW_CASE' => 'إنشاء حالة' ,
   'NTC_REMOVE_FROM_BUG_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذه الحالة من هذه المشكلة؟' ,
   'NTC_REMOVE_INVITEE' => 'هل أنت متأكد أنك تريد إزالة جهة الإتصال من هذا العيب؟' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'LBL_LIST_DATE_CREATED' => 'التاريخ المنشأ فيه' ,
   'LNK_CASE_REPORTS' => 'تقارير الحالة' );

?>
