<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/InboundEmail/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ASSIGN_TEAM' => 'تخصص إلى فريق' ,
   'ERR_BAD_LOGIN_PASSWORD' => 'تسجيل الدخول أو كلمة السر خطأ' ,
   'ERR_BODY_TOO_LONG' => '\rنص الموضوع طويل جدا لدرجة أنه لا يمكن أخذ صورة كاملة من البريد الإلكتروني. تم تقليمه' ,
   'ERR_INI_ZLIB' => 'لا يمكن |إيقاف ضغط Zlib بشكل مؤقت. إختبار الإعدادات من الممكن أن يفشل' ,
   'ERR_MAILBOX_FAIL' => 'لا يمكن استعادة أي صناديق بريد' ,
   'ERR_NO_IMAP' => 'لا يوجد مكتبات IMAP. من فضلك حل هذا قبل الإسترسال في البريد الإلكتروني الداخلي' ,
   'ERR_NO_OPTS_SAVED' => 'لا توجد نماذج مثالية محفوظة بصندوق بريدك الوارد. من فضلك راجع الإعدادات' ,
   'ERR_TEST_MAILBOX' => 'من فضلك تفقد إعداداتك وحاول مرة أخرى' ,
   'LBL_APPLY_OPTIMUMS' => 'طبق النماذج المثالية' ,
   'LBL_ASSIGN_TO_USER' => 'خصص للمستخدم' ,
   'LBL_AUTOREPLY_OPTIONS' => 'خيارات الرد الآلي' ,
   'LBL_AUTOREPLY' => 'قوالب الرد الآلي' ,
   'LBL_BASIC' => 'تركيب بسيط' ,
   'LBL_CASE_MACRO' => 'ماكرو للحالة' ,
   'LBL_CASE_MACRO_DESC' => 'قم بوضع الماكرو الذي يقوم بربط البريد الإلكتروني المستورد بالحالة' ,
   'LBL_CASE_MACRO_DESC2' => 'اضبط هذا على أي قيمة، ولكن احتفظ بال \"1%\"' ,
   'LBL_CERT_DESC' => 'إرغام التحقق من شهادات الأمان لخوادم البريد الإلكتروني - لا تستخدم في حالة التوقيع الذاتي' ,
   'LBL_CERT' => 'صدق على الشهادة' ,
   'LBL_CLOSE_POPUP' => 'إغلاق النافذة' ,
   'LBL_CREATE_NEW_GROUP' => '-- إنشاء مجموعة صناديق بريدية في الحفظ--' ,
   'LBL_CREATE_TEMPLATE' => 'إنشاء' ,
   'LBL_DEFAULT_FROM_ADDR' => 'الإفتراضي: ' ,
   'LBL_DEFAULT_FROM_NAME' => 'الإفتراضي: ' ,
   'LBL_EDIT_TEMPLATE' => 'تحرير' ,
   'LBL_EMAIL_OPTIONS' => 'خيارات تناول البريد' ,
   'LBL_FILTER_DOMAIN_DESC' => 'لا ترسل ردودا آلية لهذا النطاق' ,
   'LBL_FILTER_DOMAIN' => 'لا ردود آلية إلى النطاق' ,
   'LBL_FIND_OPTIMUM_KEY' => 'f' ,
   'LBL_FIND_OPTIMUM_MSG' => 'جاري العثور على متغيرات اتصال مثالية' ,
   'LBL_FIND_OPTIMUM_TITLE' => 'اعثر على التعريف المثالي' ,
   'LBL_FIND_SSL_WARN' => 'اختبار \"SSL\"  ربما يأخذ وقتا طويلا. من فضلك كن صبورا.' ,
   'LBL_FORCE_DESC' => 'بعض خوادم IMAP/POP3 تحتاج ضوابط خاصة. تحقق لإغام سلبي لضابط أثناء الإتصال.' ,
   'LBL_FORCE' => 'إرغام سلبي' ,
   'LBL_FOUND_MAILBOXES' => 'عثر على المجلدات القابلة للاستخدام التالية. اعثر على واحد لاختياره:' ,
   'LBL_FOUND_OPTIMUM_MSG' => 'عثر على الإعدادات المثالية. اضغط على الزر أدناه لتطبيقها على صندوق بريدك' ,
   'LBL_FROM_ADDR' => 'من عنوان' ,
   'LBL_FROM_NAME_ADDR' => 'الرد على إسم\بريد إلكتروني' ,
   'LBL_FROM_NAME' => 'من إسم' ,
   'LBL_GROUP_QUEUE' => 'خصص لمجموعة' ,
   'LBL_HOME' => 'الرئيسية' ,
   'LBL_LIST_MAILBOX_TYPE' => 'استخدام صندوق البريد' ,
   'LBL_LIST_NAME' => 'اسم:' ,
   'LBL_LIST_SERVER_URL' => 'خادم البريد:' ,
   'LBL_LIST_STATUS' => 'الحالة:' ,
   'LBL_LOGIN' => 'اسم المستخدم' ,
   'LBL_MAILBOX_DEFAULT' => 'INBOX' ,
   'LBL_MAILBOX_SSL_DESC' => 'إستخدم SSL  أثناء الإتصال. لو لم ينجح هذا، تحقق من نسختك المثبتة من بي إتش بي في الإعدادات  \"--with-imap-ssl\"' ,
   'LBL_MAILBOX_SSL' => 'إستخدم SSL' ,
   'LBL_MAILBOX_TYPE' => 'إجراءات محتملة' ,
   'LBL_MAILBOX' => 'مجلد مراقَب' ,
   'LBL_MARK_READ_DESC' => 'التي قرأت من خادم البريد أثناء الإستيراد؛ لا تحذف.' ,
   'LBL_MARK_READ_NO' => 'البريد عليه علامة محذوف بعد الاستيراد' ,
   'LBL_MARK_READ_YES' => 'البريد متروك على الخادم بعد الاستيراد' ,
   'LBL_MARK_READ' => 'اترك الرسائل على الخادم' ,
   'LBL_MODULE_NAME' => 'تركيب البريد الوارد' ,
   'LBL_MODULE_TITLE' => 'البريد الوارد' ,
   'LBL_NAME' => 'اسم' ,
   'LBL_NO_OPTIMUMS' => 'لا يمكن العثور على نماذج مثالية. من فضلك تفقد إعداداتك وحاول مرة أخرى.' ,
   'LBL_ONLY_SINCE_DESC' => 'عند إستخدام POP3, PHP  لا يمكن فصل الرسائل الجديدة والغير مقروءة.هذا العلم يسمح لك بطلب تفقد الرسائل منذ آخر مرة تم فيها تفقد صندوق البريد. هذا خاصة سوف يقوم بتحسن أداء خادم البريد الإلكتروني خاصتك لو أنه لا يدعم IMAP' ,
   'LBL_ONLY_SINCE_NO' => 'كلا. تفقد مقابل كل رسائل البريد الإلكتروني على خادم البريد.' ,
   'LBL_ONLY_SINCE_YES' => 'نعم.' ,
   'LBL_ONLY_SINCE' => 'استورد فقط منذ آخر تفقد:' ,
   'LBL_PASSWORD_CHECK' => 'تفقد كلمة السر' ,
   'LBL_PASSWORD' => 'كمة سر' ,
   'LBL_POP3_SUCCESS' => 'نجحت تجربتك للتوصيل بمستفيد \"POP3\"' ,
   'LBL_POPUP_FAILURE' => 'فشل التوصيل التجريبي. الخطأ معروض أدناه.' ,
   'LBL_POPUP_SUCCESS' => 'نجحت تجربة للتوصيل. إعداداتك تعمل.' ,
   'LBL_POPUP_TITLE' => 'اختبر الإعدادات/إعدادات تجريبية' ,
   'LBL_PORT' => 'منفذ خادم البريد' ,
   'LBL_QUEUE' => 'قائمة انتظار البريد' ,
   'LBL_SAVE_RAW' => 'أحفظ الأصل الأول' ,
   'LBL_SAVE_RAW_DESC_1' => 'أختر نعم إذا كنت تريد أن تبقي الأصل الأول لكل رسالة البريد الإلكتروني تم إستيرادها' ,
   'LBL_SAVE_RAW_DESC_2' => 'المرفقات الكبيرة قد تحدث فشل في حالة قواعد البيانات التي إعداداتها غير صحيحة' ,
   'LBL_SERVER_OPTIONS' => 'تركيب متقدم' ,
   'LBL_SERVER_TYPE' => 'بروتوكول خادم البريد' ,
   'LBL_SERVER_URL' => 'عنوان خادم البريد' ,
   'LBL_SSL_DESC' => 'لو أن خادم البريد الإلكتروني خاصتك يدعم SSL، إتاحة هذا سوف يجبر وجود إتال باستخدام SSL عند إستيرلد البريد الإلكتروني' ,
   'LBL_SSL' => 'إستخدم SSL' ,
   'LBL_STATUS' => 'الحالة' ,
   'LBL_SYSTEM_DEFAULT' => 'إعداد إفتراضي للنظام' ,
   'LBL_TEST_BUTTON_KEY' => 't' ,
   'LBL_TEST_BUTTON_TITLE' => 'تجربة [Alt+T]' ,
   'LBL_TEST_SETTINGS' => 'اختبر الإعدادات/إعدادات تجريبية' ,
   'LBL_TEST_SUCCESSFUL' => 'تم التوصيل بنجاح' ,
   'LBL_TEST_WAIT_MESSAGE' => 'لحظة واحدة من فضلك...' ,
   'LBL_TLS_DESC' => 'إستخدم TLS عند الإتصال بخادم البريد الإلكتروني - فقط إستخدم هذا خادم بريدك الغلكتروني يدعم هذا البروتوكول' ,
   'LBL_TLS' => 'إستخدم TLS' ,
   'LBL_WARN_IMAP_TITLE' => 'تم تعطيل البريد الوارد' ,
   'LBL_WARN_IMAP' => 'تحذيرات:' ,
   'LBL_WARN_NO_IMAP' => 'رسائل البريد الإلكتروني الداخلية لا يمكنها العمل بدون مكتبات كود IMAP c-client المتاحة في وحدة بي إتش بي. من فضلك إتصل بمدير النظام لحل هذا الأمر' ,
   'LNK_CREATE_GROUP' => 'إنشاء مجموعة جديدة' ,
   'LNK_LIST_CREATE_NEW' => 'راقب صندوق البريد الجديد' ,
   'LNK_LIST_MAILBOXES' => 'كل صناديق البريد' ,
   'LNK_LIST_QUEUES' => 'كل قوائم الانتظار' ,
   'LNK_LIST_SCHEDULER' => 'المجدولات' ,
   'LNK_LIST_TEST_IMPORT' => 'جرب استيراد البريد' ,
   'LNK_NEW_QUEUES' => 'إنشاء قائمة انتظار جديدة' ,
   'LNK_SEED_QUEUES' => 'لقم قوائم الإنتظار من المجموعات' );

?>
