<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Leads/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'db_last_name' => 'LBL_LIST_LAST_NAME' ,
   'db_first_name' => 'LBL_LIST_FIRST_NAME' ,
   'db_title' => 'LBL_LIST_TITLE' ,
   'db_email1' => 'LBL_LIST_EMAIL_ADDRESS' ,
   'db_account_name' => 'LBL_LIST_ACCOUNT_NAME' ,
   'db_email2' => 'LBL_LIST_EMAIL_ADDRESS' ,
   'ERR_DELETE_RECORD' => 'en_us لابد من تحديد رقم السجل لكي تم حذف العميل المتوقع' ,
   'LBL_ACCOUNT_DESCRIPTION' => 'وصف الحساب' ,
   'LBL_ACCOUNT_ID' => 'هوية الحساب' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_ADD_BUSINESSCARD' => 'أضف بطاقة عمل' ,
   'LBL_ADDRESS_INFORMATION' => 'بيانات العنوان' ,
   'LBL_ALT_ADDRESS_CITY' => 'مدينة العنوان البديل' ,
   'LBL_ALT_ADDRESS_COUNTRY' => 'بلد العنوان البديل' ,
   'LBL_ALT_ADDRESS_POSTALCODE' => 'الرمز البريدي للعنوان البديل' ,
   'LBL_ALT_ADDRESS_STATE' => 'المحافظة للعنوان البديل' ,
   'LBL_ALT_ADDRESS_STREET_2' => 'الشارع للعنوان البديل 2' ,
   'LBL_ALT_ADDRESS_STREET_3' => 'الشارع للعنوان البديل 3' ,
   'LBL_ALT_ADDRESS_STREET' => 'شارع العنوان البديل' ,
   'LBL_ALTERNATE_ADDRESS' => 'عنوان آخر:' ,
   'LBL_ANY_ADDRESS' => 'أي عنوان:' ,
   'LBL_ANY_EMAIL' => 'أي بريد إلكتروني:' ,
   'LBL_ANY_PHONE' => 'أي تليفون:' ,
   'LBL_ASSIGNED_TO_NAME' => 'مخصصة لإسم' ,
   'LBL_BACKTOLEADS' => 'الرجوع للعملاء المتوقعين' ,
   'LBL_BUSINESSCARD' => 'حول العميل المتوقع' ,
   'LBL_CITY' => 'مدينة:' ,
   'LBL_CONTACT_ID' => 'هوية جهة الإتصال' ,
   'LBL_CONTACT_INFORMATION' => 'معلومات العميل المتوقع' ,
   'LBL_CONTACT_NAME' => 'إسم العميل المتوقع:' ,
   'LBL_CONTACT_OPP_FORM_TITLE' => 'فرصة العميل المتوقع:' ,
   'LBL_CONTACT_ROLE' => 'صلاحية:' ,
   'LBL_CONTACT' => 'عميل متوقع:' ,
   'LBL_CONVERTED_ACCOUNT' => 'حساب محوَّل:' ,
   'LBL_CONVERTED_CONTACT' => 'اتصال محوَّل:' ,
   'LBL_CONVERTED_OPP' => 'فرصة محولة:' ,
   'LBL_CONVERTED' => 'محول' ,
   'LBL_CONVERTLEAD_BUTTON_KEY' => 'V' ,
   'LBL_CONVERTLEAD_TITLE' => 'عميل متوقع محول [Alt+V]' ,
   'LBL_CONVERTLEAD' => 'حول العميل المتوقع' ,
   'LBL_COUNTRY' => 'بلد:' ,
   'LBL_CREATED_ACCOUNT' => 'تم إنشاء حساب جديد' ,
   'LBL_CREATED_CALL' => 'أنشأ مكالمة جديدة' ,
   'LBL_CREATED_CONTACT' => 'تم إنشاء اتصال جديد' ,
   'LBL_CREATED_MEETING' => 'أنشأ اجتماعا جديدا' ,
   'LBL_CREATED_OPPORTUNITY' => 'أنشأ فرصة جديدة' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'عملاء متوقعين' ,
   'LBL_DEPARTMENT' => 'قسم:' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_DO_NOT_CALL' => 'لا تتصل:' ,
   'LBL_DUPLICATE' => 'عملاء متوقعون متشابهون' ,
   'LBL_EMAIL_ADDRESS' => 'بريد الكتروني:' ,
   'LBL_EMAIL_OPT_OUT' => 'البريد المختار:' ,
   'LBL_EXISTING_ACCOUNT' => 'استخدَم حسابا قائما' ,
   'LBL_EXISTING_CONTACT' => 'إستخدم جهة إتصال قائمة' ,
   'LBL_EXISTING_OPPORTUNITY' => 'استخدَم فرصة قائمة' ,
   'LBL_FAX_PHONE' => 'فاكس:' ,
   'LBL_FIRST_NAME' => 'اسم أول:' ,
   'LBL_FULL_NAME' => 'اسم بالكامل:' ,
   'LBL_HISTORY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_HOME_PHONE' => 'تليفون البريد:' ,
   'LBL_IMPORT_VCARD' => 'إستيراد vCard' ,
   'LBL_IMPORT_VCARDTEXT' => 'إنشاء تلقائى لعميل متوقع جديد عن طريق إستيراد الvCard من ملف النظام' ,
   'LBL_INVALID_EMAIL' => 'بريد إلكتروني غير صحيح:' ,
   'LBL_INVITEE' => 'تقارير مباشرة' ,
   'LBL_LAST_NAME' => 'اسم أخير:' ,
   'LBL_LEAD_SOURCE_DESCRIPTION' => 'وصف مصدر عميل متوقع:' ,
   'LBL_LEAD_SOURCE' => 'مصدر عميل متوقع:' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_CONTACT_NAME' => 'إسم العميل المتوقع' ,
   'LBL_LIST_CONTACT_ROLE' => 'صلاحية' ,
   'LBL_LIST_DATE_ENTERED' => 'التاريخ المنشأ فيه' ,
   'LBL_LIST_EMAIL_ADDRESS' => 'بريد الكتروني' ,
   'LBL_LIST_FIRST_NAME' => 'اسم أول' ,
   'LBL_VIEW_FORM_TITLE' => 'مطالعة العميل المتوقع' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة العملاء المتوقعين' ,
   'LBL_LIST_LAST_NAME' => 'اسم أخير' ,
   'LBL_LIST_LEAD_SOURCE_DESCRIPTION' => 'وصف مصدر العميل المتوقع' ,
   'LBL_LIST_LEAD_SOURCE' => 'مصدر العميل المتوقع' ,
   'LBL_LIST_MY_LEADS' => 'العملاء المتوقعين الخاصين بي' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_PHONE' => 'تليفون المكتب' ,
   'LBL_LIST_REFERED_BY' => 'مشار إليه من قبل' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_TITLE' => 'اللقب' ,
   'LBL_MOBILE_PHONE' => 'محمول:' ,
   'LBL_MODULE_NAME' => 'عملاء متوقعين' ,
   'LBL_MODULE_TITLE' => 'العملاء المتوقعين: الرئيسية' ,
   'LBL_NAME' => 'اسم:' ,
   'LBL_NEW_FORM_TITLE' => 'عميل متوقع جديد' ,
   'LBL_NEW_PORTAL_PASSWORD' => 'كلمة سر جديدة للبوابة الإلكترونية' ,
   'LBL_OFFICE_PHONE' => 'تليفون المكتب:' ,
   'LBL_OPP_NAME' => 'فرصة بيع:' ,
   'LBL_OPPORTUNITY_AMOUNT' => 'سعر الفرصة:' ,
   'LBL_OPPORTUNITY_ID' => 'هوية الفرصة' ,
   'LBL_OPPORTUNITY_NAME' => 'فرصة بيع:' ,
   'LBL_OTHER_EMAIL_ADDRESS' => 'بريد إلكتروني آخر:' ,
   'LBL_OTHER_PHONE' => 'تليفون آخر:' ,
   'LBL_PHONE' => 'تليفون:' ,
   'LBL_PORTAL_ACTIVE' => 'الموقع الإلكترونى نشط:' ,
   'LBL_PORTAL_APP' => 'تطبيق البوابة' ,
   'LBL_PORTAL_INFORMATION' => 'معلومات البوابة' ,
   'LBL_PORTAL_NAME' => 'اسم البوابة:' ,
   'LBL_PORTAL_PASSWORD_ISSET' => 'تم ضبط كلمة سر البوابة:' ,
   'LBL_POSTAL_CODE' => 'الرمز البريدي:' ,
   'LBL_PRIMARY_ADDRESS_CITY' => 'المدينة الرئيسية للعنوان' ,
   'LBL_PRIMARY_ADDRESS_COUNTRY' => 'البلد الرئيسية للعنوان' ,
   'LBL_PRIMARY_ADDRESS_POSTALCODE' => 'الرمز البريدي للعنوان الرئيسي' ,
   'LBL_PRIMARY_ADDRESS_STATE' => 'محافظة العنوان الرئيسي' ,
   'LBL_PRIMARY_ADDRESS_STREET_2' => 'شارع العنوانِ الأساسيِ 2' ,
   'LBL_PRIMARY_ADDRESS_STREET_3' => 'شارع العنوانِ الأساسيِ 3' ,
   'LBL_PRIMARY_ADDRESS_STREET' => 'شارع العنوانِ الأساسيِ 2' ,
   'LBL_PRIMARY_ADDRESS' => 'العنوان الأساسي:' ,
   'LBL_REFERED_BY' => 'مشار إليه من قبل:' ,
   'LBL_REPORTS_TO_ID' => 'متعلق هوية التقارير' ,
   'LBL_REPORTS_TO' => 'تقارير لـ:' ,
   'LBL_SALUTATION' => 'تحية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث عن عميل متوقع' ,
   'LBL_SELECT_CHECKED_BUTTON_LABEL' => 'إختيار العملاء المتوقعين المؤشر عليهم' ,
   'LBL_SELECT_CHECKED_BUTTON_TITLE' => 'إختيار العملاء المتوقعين المؤشر عليهم' ,
   'LBL_STATE' => 'محافظة:' ,
   'LBL_STATUS_DESCRIPTION' => 'وصف الحالة:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_TITLE' => 'اللقب:' ,
   'LNK_IMPORT_VCARD' => 'إنشاء من vCard' ,
   'LNK_LEAD_LIST' => 'عملاء متوقعين' ,
   'LNK_NEW_ACCOUNT' => 'إنشاء حساب' ,
   'LNK_NEW_APPOINTMENT' => 'إنشاء موعد' ,
   'LNK_NEW_CONTACT' => 'إنشاء جهة إتصال' ,
   'LNK_NEW_LEAD' => 'إدخال عميل متوقع' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_OPPORTUNITY' => 'إنشاء فرصة' ,
   'LNK_SELECT_ACCOUNT' => 'اختر حساب' ,
   'MSG_DUPLICATE' => 'تم إكتشاف عملاء متوقعون متشابهون. من فضلك أشر على أي عميل متوقع تريد إصحابه مع مجموعة السجلات التي سوف تنشأ من هذا التحويل. حينما تفعل ذلك. م فضلك اضغط التالي.' ,
   'NTC_COPY_ALTERNATE_ADDRESS' => 'انسخ العنوان البديل للعنوان الرئيسي' ,
   'NTC_COPY_PRIMARY_ADDRESS' => 'انسخ العنوان الرئيسي للعنوان البديل ' ,
   'NTC_DELETE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إلغاء هذا السجل؟' ,
   'NTC_OPPORTUNITY_REQUIRES_ACCOUNT' => 'إنشاء فرصة يتطلب وجود حساب. من فضلك إما أن تنشئ واحدا أو أن تختار حساب موجودا.' ,
   'NTC_REMOVE_CONFIRMATION' => 'هل أنت متأكد من أنك تريد إزالة هؤلاء العملاء المتوقعين من هذه الحالة؟' ,
   'NTC_REMOVE_DIRECT_REPORT_CONFIRMATION' => 'هل أنت متأكد أنك تريد إزالة هذا التسجيل كتقرير مباشر؟' ,
   'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE' => 'حملات' ,
   'LBL_TARGET_OF_CAMPAIGNS' => 'حملة ناجحة:' ,
   'LBL_TARGET_BUTTON_LABEL' => 'مستهدف' ,
   'LBL_TARGET_BUTTON_TITLE' => 'مستهدف' ,
   'LBL_TARGET_BUTTON_KEY' => 'T' ,
   'LBL_CAMPAIGN_ID' => 'هوية الحملة' ,
   'LBL_CAMPAIGN' => 'حملة:' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'LNK_LEAD_REPORTS' => 'تقارير العميل المتوقع' ,
   'LBL_THANKS_FOR_SUBMITTING_LEAD' => 'شكرا لموافقتك' ,
   'LBL_SERVER_IS_CURRENTLY_UNAVAILABLE' => 'نحن في غاية الأسف، الخادم غير متاح الآن، الرجاء أعادة المحاولة  آجلا' );

?>
