<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Home/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_NEW_FORM_TITLE' => 'جهة إتصال جديدة' ,
   'LBL_FIRST_NAME' => 'اسم أول:' ,
   'LBL_LAST_NAME' => 'اسم أخير:' ,
   'LBL_LIST_LAST_NAME' => 'اسم أخير' ,
   'LBL_PHONE' => 'تليفون:' ,
   'LBL_EMAIL_ADDRESS' => 'بريد الكتروني:' ,
   'LBL_PIPELINE_FORM_TITLE' => 'الرسومات البيانية الخطية ' ,
   'LBL_CAMPAIGN_ROI_FORM_TITLE' => 'حملة ROI' ,
   'LNK_NEW_CONTACT' => 'إنشاء جهة إتصال' ,
   'LNK_NEW_ACCOUNT' => 'إنشاء حساب' ,
   'LNK_NEW_OPPORTUNITY' => 'إنشاء فرصة' ,
   'LNK_NEW_QUOTE' => 'إنشاء اقتباس' ,
   'LNK_NEW_LEAD' => 'إدخال عميل متوقع' ,
   'LNK_NEW_CASE' => 'إنشاء حالة' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_EMAIL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LNK_COMPOSE_EMAIL' => 'كتابة رسالة إلكترونية' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_NEW_BUG' => 'إخطار بالمشكلة' ,
   'LBL_ADD_BUSINESSCARD' => 'إدخال بطاقة عمل' ,
   'ERR_ONE_CHAR' => 'الرجاءإدخال على الأقل حرفا أو رقما واحدا لبحثك' ,
   'LBL_OPEN_TASKS' => 'المهام المفتوحة' ,
   'LBL_SEARCH_RESULTS' => 'نتائج البحث' ,
   'LBL_SEARCH_RESULTS_IN' => 'في' ,
   'LNK_NEW_SEND_EMAIL' => 'كتابة رسالة إلكترونية' ,
   'LBL_NO_RESULTS_IN_MODULE' => '--لا توجد نتائج--' ,
   'LBL_NO_RESULTS' => '<h1>لم يعثر على نتائج. من فضلك ابحث مرة أخرى.</h1>' ,
   'LBL_NO_RESULTS_TIPS' => 'إرشادات البحث: تأكد أنك وسعت معايير بحثك. إذا كنت لا زلت غير قادر إيجاد أي نتائج جرب البحث المتقدم الخاص بتلك الوحدة.' ,
   'LBL_RELOAD_PAGE' => 'من فضلك أعد تحميل هذة النافذة لإستخدام هذا الملصق' ,
   'LBL_ADD_DASHLETS' => 'إضافة مدون ملصق' ,
   'LBL_CLOSE_DASHLETS' => 'إغلاق' ,
   'LBL_OPTIONS' => 'خيارات' ,
   'LBL_TODAY' => 'اليوم' ,
   'LBL_YESTERDAY' => 'أمس' ,
   'LBL_TOMORROW' => 'غدا' ,
   'LBL_LAST_WEEK' => 'الأسبوع الأخير' ,
   'LBL_NEXT_WEEK' => 'الأسبوع التالي' ,
   'LBL_LAST_7_DAYS' => 'آخر 7 أيام' ,
   'LBL_NEXT_7_DAYS' => 'الأيام السبع التالية' ,
   'LBL_LAST_MONTH' => 'الشهر الأخير' ,
   'LBL_NEXT_MONTH' => 'الشهر التالي' ,
   'LBL_LAST_QUARTER' => 'ربع السنة الأخير' ,
   'LBL_THIS_QUARTER' => 'ربع السنة الحالي' ,
   'LBL_LAST_YEAR' => 'السنة الأخيرة' ,
   'LBL_NEXT_YEAR' => 'السنة التالية' ,
   'LBL_THIS_MONTH' => 'الشهر الحالي' ,
   'LBL_THIS_YEAR' => 'السنة الحالية' ,
   'LBL_LAST_30_DAYS' => 'آخر 30 يوما' ,
   'LBL_NEXT_30_DAYS' => 'الثلاثون يوما القادمة' ,
   'LBL_MAX_DASHLETS_REACHED' => 'لقد وصلت إلى الحد الأقصى من المدونات الملصقة التي حددها مديرك. من فضلط إحذف مدنا ملصقا لكي تضيف آخر' ,
   'LBL_ADDING_DASHLET' => 'جاري إضافة مدون ملصق..' ,
   'LBL_ADDED_DASHLET' => 'تم إضافة مدون ملصق' ,
   'LBL_REMOVE_DASHLET_CONFIRM' => 'هل أنت متأكد من أنك تريد إزالة المدون الملصق؟' ,
   'LBL_REMOVING_DASHLET' => 'جارز إزالة المدون الملصق؟' ,
   'LBL_REMOVED_DASHLET' => 'تم حذف المدون الملصق' ,
   'LBL_DASHLET_CONFIGURE_GENERAL' => 'عام' ,
   'LBL_DASHLET_CONFIGURE_FILTERS' => 'منقّيات' ,
   'LBL_DASHLET_CONFIGURE_MY_ITEMS_ONLY' => 'العناصر الخاصة بي فقط' ,
   'LBL_DASHLET_CONFIGURE_TITLE' => 'اللقب' ,
   'LBL_DASHLET_CONFIGURE_DISPLAY_ROWS' => 'عرض الصفوف' ,
   'LBL_TRAINING_TITLE' => 'تدريب' ,
   'dashlet_categories_dom' => array (
      'Module Views' => 'أنماط رؤية الوحدة' ,
      'Portal' => 'بوابة' ,
      'Charts' => 'رسومات بيانية' ,
      'Tools' => 'أدوات' ,
      'Miscellaneous' => 'متنوع'   ));

?>
