<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Quotes/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'db_sales_stage' => 'LBL_LIST_SALES_STAGE' ,
   'db_name' => 'LBL_NAME' ,
   'db_amount' => 'LBL_LIST_AMOUNT' ,
   'db_date_closed' => 'LBL_LIST_DATE_CLOSED' ,
   'LBL_CONTRACTS' => 'العقود' ,
   'LBL_CONTRACTS_SUBPANEL_TITLE' => 'العقود' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلعاء الإقتباس' ,
   'LBL_ACCOUNT_ID' => 'هوية الحساب' ,
   'LBL_ACCOUNT_NAME' => 'اسم الحساب:' ,
   'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'أنشطة' ,
   'LBL_ADD_COMMENT' => 'أضف تعليق' ,
   'LBL_ADD_GROUP' => 'أضف مجموعة' ,
   'LBL_ADD_ROW' => 'أضف صف' ,
   'LBL_ADDRESS_INFORMATION' => 'معلومات الاتصال' ,
   'LBL_AMOUNT' => 'كمية:' ,
   'LBL_ANY_ADDRESS' => 'أي عنوان:' ,
   'LBL_BILL_TO' => 'تقديم فاتورة إلى' ,
   'LBL_BILLING_ACCOUNT_NAME' => 'أسم حساب التحصيل:' ,
   'LBL_BILLING_ACCOUNT' => 'حساب:' ,
   'LBL_BILLING_ADDRESS_CITY' => 'أسم مدينة التحصيل:' ,
   'LBL_BILLING_ADDRESS_COUNTRY' => ' أسم بلد التحصيل' ,
   'LBL_BILLING_ADDRESS_POSTAL_CODE' => 'الرمز البريدي للتحصيل' ,
   'LBL_BILLING_ADDRESS_STATE' => 'أسم محافظة التحصيل' ,
   'LBL_BILLING_ADDRESS_STREET' => 'عنوان التحصيل' ,
   'LBL_BILLING_ADDRESS' => 'عنوان:' ,
   'LBL_BILLING_CONTACT_NAME' => 'أسم جهة إتصال التحصيل:' ,
   'LBL_BILLING_CONTACT' => 'جهة إتصال:' ,
   'LBL_BUNDLE_NAME' => 'اسم المجموعة :' ,
   'LBL_BUNDLE_STAGE' => 'حالة المجموعة:' ,
   'LBL_CALC_GRAND' => 'أعرض المحموع الكلي:' ,
   'LBL_CHECK_DATA' => 'إدخال البيانات غير صحيح: الرجاء تفقد البيانات الخاصة بك و تأكد من أن الأرقام صحيحة(0-9 أو ".")' ,
   'LBL_CITY' => 'مدينة:' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال:' ,
   'LBL_CONTACT_QUOTE_FORM_TITLE' => 'حصة جهة الإتصال:' ,
   'LBL_CONTACT_ROLE' => 'وظيفة جهة الإتصال:' ,
   'LBL_COUNTRY' => 'بلد:' ,
   'LBL_CREATED_BY' => 'إنشاء بواسطة' ,
   'LBL_CURRENCY' => 'العملة:' ,
   'LBL_DATE_QUOTE_CLOSED' => 'تاريخ الاستحقاق الحقيقي:' ,
   'LBL_DATE_QUOTE_EXPECTED_CLOSED' => 'صالح حتى:' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'إقتباسات' ,
   'LBL_DELETE_GROUP' => 'إلغي المجموعة' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_DUPLICATE' => 'إمكانية تكرار في الإقتباس' ,
   'LBL_EMAIL_QUOTE_FOR' => 'أقتباس لـ: ' ,
   'LBL_EMAIL_DEFAULT_DESCRIPTION' => 'هذا هو الأقتباس الذي طلبته( يمكنك تغيير النص) ' ,
   'LBL_EMAIL_ATTACHMENT' => 'مرفق رسالة البريد الإلكتروني' ,
   'LBL_HISOTRY_SUBPANEL_TITLE' => 'سيرة' ,
   'LBL_INVITEE' => 'جهات إتصال' ,
   'LBL_INVOICE' => 'فاتورة' ,
   'LBL_LEAD_SOURCE' => 'مصدر عميل متوقع:' ,
   'LBL_LINE_ITEM_INFORMATION' => 'عناصر الخط' ,
   'LBL_LIST_ACCOUNT_NAME' => 'اسم الحساب' ,
   'LBL_LIST_AMOUNT' => 'كمية' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'LBL_LIST_COST_PRICE' => 'التكلفة' ,
   'LBL_LIST_DATE_QUOTE_CLOSED' => 'الإغلاق الحقيقي' ,
   'LBL_LIST_DATE_QUOTE_EXPECTED_CLOSED' => 'صالح حتى' ,
   'LBL_LIST_DISCOUNT_PRICE' => 'وحدة السعر' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الأقتباس' ,
   'LBL_LIST_GRAND_TOTAL' => 'المجموع الكلي' ,
   'LBL_LIST_LIST_PRICE' => 'قائمة' ,
   'LBL_LIST_MANUFACTURER_PART_NUM' => 'الرقم الخاص بالصانع' ,
   'LBL_LIST_PRICING_FACTOR' => 'معلمل' ,
   'LBL_LIST_PRICING_FORMULA' => 'صيغة التسعير' ,
   'LBL_LIST_PRODUCT_NAME' => 'منتج' ,
   'LBL_LIST_QUANTITY' => 'كمية' ,
   'LBL_LIST_QUOTE_NAME' => 'الموضوع' ,
   'LBL_LIST_QUOTE_NUM' => 'رقم' ,
   'LBL_LIST_QUOTE_STAGE' => 'مرحلة' ,
   'LBL_LIST_TAXCLASS' => 'فئة الضريبة' ,
   'LBL_MODIFIED_BY' => 'تم التعديل بواسطة' ,
   'LBL_MODULE_NAME' => 'إقتباسات' ,
   'LBL_MODULE_TITLE' => 'الإقتباسات: الرئيسية' ,
   'LBL_NAME' => 'أسم الإقتباس' ,
   'LBL_NEW_FORM_TITLE' => 'إنشاء اقتباس' ,
   'LBL_NEXT_STEP' => 'الخطوة التالية:' ,
   'LBL_OPPORTUNITY_NAME' => 'فرصة بيع:' ,
   'LBL_ORDER_STAGE' => 'مرحلة الترتيب' ,
   'LBL_ORIGINAL_PO_DATE' => 'التاريخ الأصلي لأمر الشراء:' ,
   'LBL_PAYMENT_TERMS' => 'شروط الدفع:' ,
   'LBL_PDF_BILLING_ADDRESS' => 'تقديم الفاتورة إلى' ,
   'LBL_PDF_CURRENCY' => 'العملة:' ,
   'LBL_PDF_GRAND_TOTAL' => 'المجموع الكلي' ,
   'LBL_PDF_INVOICE_NUMBER' => 'رقم الفاتورة' ,
   'LBL_PDF_INVOICE_TITLE' => 'فاتورة' ,
   'LBL_PDF_ITEM_EXT_PRICE' => 'سعر الأمتداد' ,
   'LBL_PDF_ITEM_LIST_PRICE' => 'سعر القائمة' ,
   'LBL_PDF_ITEM_PRODUCT' => 'منتج' ,
   'LBL_PDF_ITEM_QUANTITY' => 'كمية' ,
   'LBL_PDF_ITEM_UNIT_PRICE' => 'وحدة السعر' ,
   'LBL_PDF_PART_NUMBER' => 'رقم الجزء:' ,
   'LBL_PDF_QUOTE_CLOSE' => 'صالح حتى:' ,
   'LBL_PDF_QUOTE_DATE' => 'تاريخ:' ,
   'LBL_PDF_QUOTE_NUMBER' => 'رقم الإقتباس:' ,
   'LBL_PDF_QUOTE_TITLE' => 'عرض المقترح' ,
   'LBL_PDF_SALES_PERSON' => 'مندوب مبيعات:' ,
   'LBL_PDF_SHIPPING_ADDRESS' => 'أشحن إلى' ,
   'LBL_PDF_SHIPPING_COMPANY' => 'متعهد شحن:' ,
   'LBL_PDF_SHIPPING' => 'شحن:' ,
   'LBL_PDF_SUBTOTAL' => 'المجموع:' ,
   'LBL_PDF_TAX_RATE' => 'معدل الضريبه:' ,
   'LBL_PDF_TAX' => 'ضريبة:' ,
   'LBL_PDF_TOTAL' => 'مجموع:' ,
   'LBL_POSTAL_CODE' => 'الرمز البريدي:' ,
   'LBL_PROJECTS_SUBPANEL_TITLE' => 'مشروعات' ,
   'LBL_PROPOSAL' => 'عرض المقترح' ,
   'LBL_PURCHASE_ORDER_NUM' => 'رقم طلب الشراء:' ,
   'LBL_QUOTE_NAME' => 'موضوع الإقتباس:' ,
   'LBL_QUOTE_NUM' => 'رقم الإقتباس:' ,
   'LBL_QUOTE_STAGE' => 'مرحلة الإقتباس:' ,
   'LBL_QUOTE_TYPE' => 'نوع الإقتباس' ,
   'LBL_QUOTE' => 'إقتباس:' ,
   'LBL_QUOTE_LAYOUT_DOES_NOT_EXIST_ERROR' => 'ملف المخطط العام للإقتباس غير موجود: $layout' ,
   'LBL_QUOTE_LAYOUT_REGISTERED_ERROR' => 'لم يتم تسجيل المخطط العام في modules/Quotes/Layouts.php' ,
   'LBL_REMOVE_COMMENT' => 'إلغاء التعلبق' ,
   'LBL_REMOVE_ROW' => 'أحذف صف' ,
   'LBL_RENAME_ERROR' => 'خطأ: لا يمكن نقل  _pdf إلى $destination. يجب أن تجعل المسار قابل للكتابة من قبل  خادم الويب' ,
   'LBL_SALES_STAGE' => 'مرحلة الإقتباس:' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في  الإقتباس' ,
   'LBL_SHIP_TO' => 'أشحن إلى' ,
   'LBL_SHIPPING_ACCOUNT_NAME' => 'أسم حساب الشحن:' ,
   'LBL_SHIPPING_ACCOUNT' => 'حساب:' ,
   'LBL_SHIPPING_ADDRESS_CITY' => 'مدينة الشحن' ,
   'LBL_SHIPPING_ADDRESS_COUNTRY' => 'بلد الشحن' ,
   'LBL_SHIPPING_ADDRESS_POSTAL_CODE' => 'المز البريدي للشحن' ,
   'LBL_SHIPPING_ADDRESS_STATE' => 'محافظة الشحن' ,
   'LBL_SHIPPING_ADDRESS_STREET' => 'عنوان الشحن' ,
   'LBL_SHIPPING_ADDRESS' => 'عنوان:' ,
   'LBL_SHIPPING_CONTACT_NAME' => 'أسم جهة إتصال الشحن:' ,
   'LBL_SHIPPING_CONTACT' => 'جهة إتصال:' ,
   'LBL_SHIPPING_PROVIDER' => 'متعهد شحن:' ,
   'LBL_SHIPPING_USDOLLAR' => 'الشحن(دولار أمريكي)' ,
   'LBL_SHIPPING' => 'شحن:' ,
   'LBL_SHOW_LINE_NUMS' => 'أرقام خط العرض:' ,
   'LBL_STATE' => 'محافظة:' ,
   'LBL_SUBTOTAL_USDOLLAR' => 'المجوع الأصلي(دولار أمريكي)' ,
   'LBL_SUBTOTAL' => 'المجموع:' ,
   'LBL_SYSTEM_ID' => 'هوية النظام' ,
   'LBL_TAX_USDOLLAR' => 'الضريبة ( دولار أمريكي)' ,
   'LBL_TAX' => 'ضريبة:' ,
   'LBL_TAXRATE' => 'معدل الضريبه:' ,
   'LBL_TOTAL_USDOLLAR' => 'المجموع( دولار أمريمي)' ,
   'LBL_TOTAL' => 'مجموع:' ,
   'LBL_TYPE' => 'النوع:' ,
   'LNK_NEW_QUOTE' => 'إنشاء اقتباس' ,
   'LNK_QUOTE_LIST' => 'إقتباسات' ,
   'MSG_DUPLICATE' => 'بإنشاء هذا الإقتباس قد يحدث تكرار في الإقتباسات. إما أن تختار أقتباس من القائمة بالأسفل أو أنقر على أحفظ لإستكمال عملية إنشاء الإقتباس الجديد يأستخدام البيانات السابق إدخالها' ,
   'NTC_COPY_BILLING_ADDRESS' => 'نسخ عنوان التحصيل إلى عنوان الشحن' ,
   'NTC_COPY_SHIPPING_ADDRESS' => 'نسخ عنوان الشحن إلى عنوان اتحصيل' ,
   'NTC_REMOVE_COMMENT_CONFIRMATION' => 'هل أنت متأكد أنك تريد حذف هذا التعليق من هذا الإقتباس؟' ,
   'NTC_REMOVE_PRODUCT_CONFIRMATION' => 'هل أنت متأكد أنك تريد حذف هذا العنصر الخطي من هذا الإقتباس؟' ,
   'NTC_REMOVE_QUOTE_CONFIRMATION' => 'هل أنت متأكد أنك تريد حذف جهة الإتصال هذه من هذا الإقتباس؟' ,
   'QUOTE_REMOVE_PROJECT_CONFIRM' => 'هل أنت متأكد أنك تريد حذف هذا الإقتباس من هذا المشروع ؟' ,
   'LNK_QUOTE_REPORTS' => 'تقارير الأقتباس' );

?>
