<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Teams/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_ADD_RECORD' => 'يجب تحديد رقم السجل لإضافة مستخدم لهذا الفريق' ,
   'ERR_DELETE_RECORD' => 'يجب تحديد رقم السجل لإلغاء هذا الفريق' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_GLOBAL_TEAM_DESC' => 'ظاهرة للجميع' ,
   'LBL_INVITEE' => 'أعضاء الفريق' ,
   'LBL_LIST_DEPARTMENT' => 'قسم' ,
   'LBL_LIST_DESCRIPTION' => 'وصف' ,
   'LBL_LIST_FORM_TITLE' => 'قاءمة الفريق' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_REPORTS_TO' => 'تقارير لـ' ,
   'LBL_LIST_TITLE' => 'اللقب' ,
   'LBL_MODULE_NAME' => 'فرق' ,
   'LBL_MODULE_TITLE' => 'الفرق: الرئيسية' ,
   'LBL_NAME' => 'أسم الفريق:' ,
   'LBL_NEW_FORM_TITLE' => 'فريق جديد' ,
   'LBL_PRIVATE' => 'خاص' ,
   'LBL_PRIVATE_TEAM_FOR' => 'فريق خاص لـ: ' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في الفريق' ,
   'LBL_TEAM_MEMBERS' => 'أعضاء الفريق' ,
   'LBL_TEAM' => 'فرق:' ,
   'LBL_USERS_SUBPANEL_TITLE' => 'المستخدمين' ,
   'LBL_USERS' => 'المستخدمين' ,
   'LNK_LIST_TEAM' => 'فرق' ,
   'LNK_LIST_TEAMNOTICE' => 'ملاحظات الفريق' ,
   'LNK_NEW_TEAM' => 'إنشئ فريق' ,
   'NTC_REMOVE_TEAM_MEMBER_CONFIRMATION' => 'هل أنت متأكد أنك تريد إلغاء هذا المستخدم أو عضويته؟' );

?>
