<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Studio/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_EDIT_LAYOUT' => 'تحرير الشكل الخارجي' ,
   'LBL_EDIT_ROWS' => 'صفوف التحرير' ,
   'LBL_EDIT_COLUMNS' => 'تحرير الأعمدة' ,
   'LBL_EDIT_LABELS' => 'تحرير المسميات' ,
   'LBL_EDIT_FIELDS' => 'تحرير الحقول المخصوصة' ,
   'LBL_ADD_FIELDS' => 'إضافة حقول مخصوصة' ,
   'LBL_DISPLAY_HTML' => 'اعرض ترميز إتش تي إم إل' ,
   'LBL_SELECT_FILE' => 'اختر ملفا' ,
   'LBL_SAVE_LAYOUT' => 'إختيار لوحة فرعية' ,
   'LBL_SELECT_A_SUBPANEL' => 'اختر لوحة' ,
   'LBL_SELECT_SUBPANEL' => 'اختر لوحة فرعية' ,
   'LBL_MODULE_TITLE' => 'ستديو' ,
   'LBL_TOOLBOX' => 'صندوق الأدوات' ,
   'LBL_STAGING_AREA' => 'منطقة التجمع (اسحب وأسقط العناصر هنا)' ,
   'LBL_SUGAR_FIELDS_STAGE' => 'حقول شوجار (اضغط على العناصر لإضافتها لمنطقة التجمع)' ,
   'LBL_SUGAR_BIN_STAGE' => 'سلة شوجار (اضغط على العناصر لإضافتها لمنطقة التجمع)' ,
   'LBL_VIEW_SUGAR_FIELDS' => 'طالع حقول شوجار' ,
   'LBL_VIEW_SUGAR_BIN' => 'طالع سلة شوجار' ,
   'LBL_FAILED_TO_SAVE' => 'فشل الحفظ' ,
   'LBL_PUBLISHING' => 'جاري النشر...' ,
   'LBL_PUBLISHED' => 'تم النشر' ,
   'LBL_FAILED_PUBLISHED' => 'فشل في النشر' ,
   'LBL_NAME' => 'اسم' ,
   'LBL_LABEL' => 'مسمى' ,
   'LBL_MASS_UPDATE' => 'التحديث المجمع' ,
   'LBL_AUDITED' => 'مراجعة' ,
   'LBL_CUSTOM_MODULE' => 'وحدة' ,
   'LBL_DEFAULT_VALUE' => 'قيمة افتراضية' ,
   'LBL_REQUIRED' => 'ضروري' ,
   'LBL_DATA_TYPE' => 'النوع' ,
   'LBL_HISTORY' => 'سيرة' ,
   'LBL_SW_WELCOME' => '<H1>أهلا في الأستوديو!<H1/><BR>


ماذا تحب أن تفعل اليوم؟<BR>
<H4>من فضلك اختر من الخيارات أدناه.</H4>' ,
   'LBL_SW_EDIT_MODULE' => 'تحرير وحدة' ,
   'LBL_SW_EDIT_DROPDOWNS' => 'تحرير القوائم المنسدلة' ,
   'LBL_SW_EDIT_TABS' => 'عناصر قائمة التعريف' ,
   'LBL_SW_RENAME_TABS' => 'أعد تسمية عناصر القائمة الرئيسية' ,
   'LBL_SW_EDIT_GROUPTABS' => 'عرّف مجموعات عناصر القائمة ' ,
   'LBL_SW_EDIT_PORTAL' => 'تحرير الموقع الإلكترونى' ,
   'LBL_SW_EDIT_WORKFLOW' => 'تحرير سير العمل' ,
   'LBL_SW_REPAIR_CUSTOMFIELDS' => 'إصلاح الحقول المخصوصة' ,
   'LBL_SW_MIGRATE_CUSTOMFIELDS' => 'دمج الحقول المخصوصة' ,
   'LBL_SMW_WELCOME' => '<H1>أهلا في الأستوديو!<H1/><BR> <H4>من فضلك اختر وحدة من الخيارات أدناه.</H4>' ,
   'LBL_SMA_WELCOME' => '<H1>تحرير وحدة<H1/><BR>ماذا تريد أن تفعل في تلك الوحدة<BR><H4>الرجاء إختيار أي الاجراء تريد أخذه.</H4>' ,
   'LBL_SMA_EDIT_CUSTOMFIELDS' => 'تحرير الحقول المخصوصة' ,
   'LBL_SMA_EDIT_LAYOUT' => 'تحرير الشكل الخارجي' ,
   'LBL_SMA_EDIT_LABELS' => 'تحرير المسميات' ,
   'LBL_MB_PREVIEW' => 'عاين' ,
   'LBL_MB_RESTORE' => 'إسترجاع' ,
   'LBL_MB_DELETE' => 'حذف' ,
   'LBL_MB_COMPARE' => 'قارن' ,
   'LBL_MB_WELCOME' => '<H1>سيرة الإستخدام<H1/><
<BR><BR>
سيرة الاستخدام يسمح لك بمطالعة النسخ المنشورة سابقا من الملف الذي تعمل به حاليا. يمكنك مقارنة واستعادة النسخ السابقة. إذا استعدت ملفا سيكون ملفك المعمول به. لابد أن تنشره قبل أن يكون مرئيا للآخرين كلهم.
<BR>
ماذا تحب أن تفعل اليوم؟
<H4>من فضلك اختر من الخيارات أدناه.</H4>' ,
   'LBL_ED_CREATE_DROPDOWN' => 'إنشاء قائمة منسدلة' ,
   'LBL_ED_WELCOME' => '<H1>محرر القائمة المنسدلة.</H1><BR>
<H4>يمكنك إما أن تحرر قائمة ساقطة حالية أو أن تنشئ قائمة ساقطة جديدة.
.</H4>
' ,
   'LBL_EC_WELCOME' => '<H1>سيرة الإستخدام<H1/>
<BR>
<H4>يمكنك إما أن تحرر حقل مخصوص موجود أو أن تنشئ حقل مخصوص جديد، أو مسح الذاكرة الوسيطة للحقول المخصوصة.
.</H4>' ,
   'LBL_EC_VIEW_CUSTOMFIELDS' => 'اظهر الحقول المخصوصة' ,
   'LBL_EC_CREATE_CUSTOMFIELD' => 'إنشاء الحقول المخصوصة' ,
   'LBL_EC_CLEAR_CACHE' => 'أمسح الذاكرة الوسيطة' ,
   'LBL_SM_WELCOME' => '<H1>سيرة الإستخدام<H1/>
<BR>
<H4>من فضلك إختر الملف الذي تريد عرضه</H4>' ,
   'LBL_DD_DISPALYVALUE' => 'القيمة الخاصة بالعرض' ,
   'LBL_DD_DATABASEVALUE' => 'القيمة الخاصة بقاعدة البيانات' ,
   'LBL_DD_ALL' => 'الكل' ,
   'LBL_BTN_SAVE' => 'حفظ' ,
   'LBL_BTN_SAVEPUBLISH' => 'حفظ و نشر' ,
   'LBL_BTN_HISTORY' => 'سيرة' ,
   'LBL_BTN_NEXT' => 'التالي' ,
   'LBL_BTN_BACK' => 'رجوع' ,
   'LBL_BTN_ADDCOLS' => 'أضف أعمدة' ,
   'LBL_BTN_ADDROWS' => 'أضف صفوفا' ,
   'LBL_BTN_UNDO' => 'تراجع' ,
   'LBL_BTN_REDO' => 'أعد الفعل' ,
   'LBL_BTN_ADDCUSTOMFIELD' => 'إضافة حقل مخصوص' ,
   'LBL_BTN_TABINDEX' => 'تحرير ترتيب عناصر القائمة الرئيسية' ,
   'LBL_TAB_SUBTABS' => 'عناصر القائمة الفرعية' ,
   'LBL_MODULES' => 'وحدات' ,
   'LBL_DEFAULT' => 'الإفتراضي' ,
   'LBL_ADDITIONAL' => 'إضافية' ,
   'LBL_AVAILABLE' => 'متاحة' ,
   'LBL_LISTVIEW_DESCRIPTION' => 'هناك ثلاثة أعمدة عرضت بأسفل. يحتوي العمود الأصلي الحقول المعروضة بشكل القائمة إفتراضيا، يحتوي العمود الإضافي الحقول التي يمكن للمستخدم إختيارها لإنشاء نمط رؤية مخصوص، والأعمدة المتوفرة متوفرة لك بإعتبارك مديرا  أمّا الإضافة إلى الأعمدة الأصلية أو الإضافية من قبل المستخدمين ليست متاحة حاليا' ,
   'LBL_LISTVIEW_EDIT' => 'محرر مطالعة القائمة' ,
   'ERROR_ALREADY_EXISTS' => 'الحقل موجود مسبقا' );

?>
