<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EmailMan/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'ERR_INT_ONLY_EMAIL_PER_RUN' => 'القيم الصحيحة وحدها هي المتاحة لتحديد أعداد رسائل البريد الإلكتروني المرسلة في كل دفعة' ,
   'LBL_ATTACHMENT_AUDIT' => ' تم إرسالها. لم يتم تكرارها محليا لتوفير مساحة التخزين' ,
   'LBL_CONFIGURE_SETTINGS' => 'إعداد' ,
   'LBL_CUSTOM_LOCATION' => 'معرف بواسطة المستخدم' ,
   'LBL_DEFAULT_LOCATION' => 'الإفتراضي' ,
   'LBL_EMAIL_DEFAULT_CHARSET' => 'ألّف رسائل بريد إلكتروني باستخدام هذا الترميز' ,
   'LBL_EMAIL_DEFAULT_CLIENT' => 'ألّف رسائل بريد إلكتروني بهذه الصيغة' ,
   'LBL_EMAIL_DEFAULT_EDITOR' => 'ألّف رسائل بريد إلكتروني باستخدام هذا المستفيد' ,
   'LBL_EMAIL_DEFAULT_DELETE_ATTACHMENTS' => 'إلغاء ملفات الملاحظات و المرفقات المتعلقة ب رسائل البريد الإلكتروني الملغاه' ,
   'LBL_EMAIL_PER_RUN_REQ' => 'عدد رسائل البريد الإلكتروني المرسلة كل دفعة:' ,
   'LBL_EMAIL_USER_TITLE' => 'إعدادات البريد الإفتراضية الخاصة بالمستخدم' ,
   'LBL_EMAILS_PER_RUN' => 'عدد رسائل البريد الإلكتروني المرسلة كل دفعة:' ,
   'LBL_ID' => 'هوية' ,
   'LBL_LIST_CAMPAIGN' => 'حملة' ,
   'LBL_LIST_FORM_PROCESSED_TITLE' => 'تمت معالجته' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة انتظار' ,
   'LBL_LIST_FROM_EMAIL' => 'من بريد إلكتروني' ,
   'LBL_LIST_FROM_NAME' => 'من إسم' ,
   'LBL_LIST_IN_QUEUE' => 'جاري التنفيذ' ,
   'LBL_LIST_MESSAGE_NAME' => 'رسالة تسويق' ,
   'LBL_LIST_RECIPIENT_EMAIL' => 'البريد المرسل إليه' ,
   'LBL_LIST_RECIPIENT_NAME' => 'الإسم المرسل إليه' ,
   'LBL_LIST_SEND_ATTEMPTS' => 'إرسال محاولات' ,
   'LBL_LIST_SEND_DATE_TIME' => 'إرسال' ,
   'LBL_LIST_USER_NAME' => 'اسم المستخدم' ,
   'LBL_LOCATION_ONLY' => 'المكان' ,
   'LBL_LOCATION_TRACK' => 'محل ملفات تتبع الحملة (مثل campaign_tracker.php)' ,
   'LBL_CAMP_MESSAGE_COPY' => 'أحتفظ بنسخ لرسائل الحملات:' ,
   'LBL_MAIL_SENDTYPE' => 'عميل نقل البريد:' ,
   'LBL_MAIL_SMTPAUTH_REQ' => 'استخدم تحقيق صلاحية  \"SMTP\"؟' ,
   'LBL_MAIL_SMTPPASS' => 'كلمة سر  \"SMTP\":' ,
   'LBL_MAIL_SMTPPORT' => 'منفذ  \"SMTP\":' ,
   'LBL_MAIL_SMTPSERVER' => 'خادم \"SMTP\":' ,
   'LBL_MAIL_SMTPUSER' => 'إسم مستخدم \"SMTP\":' ,
   'LBL_MARKETING_ID' => 'هوية التسويق' ,
   'LBL_MODULE_ID' => 'ساعي البريد الإلكتروني' ,
   'LBL_MODULE_NAME' => 'إعدادات البريد الإلكتروني' ,
   'LBL_MODULE_TITLE' => 'إدارة قائمة انتظار البريد الصادر' ,
   'LBL_NOTIFICATION_ON_DESC' => 'يرسل رسائل إخطار عند تخصيص التسجيلات' ,
   'LBL_NOTIFY_FROMADDRESS' => 'من عنوان:' ,
   'LBL_NOTIFY_FROMNAME' => 'من إسم:' ,
   'LBL_NOTIFY_ON' => 'الإبلاغات تعمل؟' ,
   'LBL_NOTIFY_SEND_BY_DEFAULT' => 'إرسال تلقائي للإخطارات للمستخدمين الجدد؟' ,
   'LBL_NOTIFY_TITLE' => 'خيارات الإخطار بالبريد الإلكتروني' ,
   'LBL_OLD_ID' => 'هوية قديمة' ,
   'LBL_OUTBOUND_EMAIL_TITLE' => 'خيارات البريد الصادر' ,
   'LBL_RELATED_ID' => 'الهوية المتعلقة' ,
   'LBL_RELATED_TYPE' => 'النوع المتعلق' ,
   'LBL_SAVE_OUTBOUND_RAW' => 'أحفظ رسائل البريد الإلكترونية الخارجة الأساسية' ,
   'LBL_SEARCH_FORM_PROCESSED_TITLE' => 'بحث تمت معالجته' ,
   'LBL_SEARCH_FORM_TITLE' => 'بحث في قائمة الانتظار' ,
   'LBL_VIEW_PROCESSED_EMAILS' => 'طالع رسائل البريد المعُالجة' ,
   'LBL_VIEW_QUEUED_EMAILS' => 'طالع رسائل البريد الموضوعة في قائمة الانتظار' ,
   'TRACKING_ENTRIES_LOCATION_DEFAULT_VALUE' => 'قيمة ملف Config.php التي تحدد رابط الموقع' ,
   'TXT_REMOVE_ME_ALT' => 'لتزيل نفسك من هذه القائمة البريدية اذهب إلى' ,
   'TXT_REMOVE_ME_CLICK' => 'اضغط هنا' ,
   'TXT_REMOVE_ME' => 'لتزيل نفسك من هذه القائمة البريدية ' ,
   'LBL_NOTIFY_SEND_FROM_ASSIGNING_USER' => 'أرسل إخطارا من تخصيص عنوان البريد إلكتروني للمستخدم ؟' ,
   'LBL_SECURITY_TITLE' => 'إعدادات تأمين البريد الإلكتروني' ,
   'LBL_SECURITY_DESC' => 'تفقد التالي الذي يجب ألا يسمح به في البريد الإلكتروني الوارد أو يعرض في وحدة البريد الإلكتروني' ,
   'LBL_SECURITY_APPLET' => 'وسم Applet' ,
   'LBL_SECURITY_BASE' => 'وسم Base' ,
   'LBL_SECURITY_EMBED' => 'وسم Embed' ,
   'LBL_SECURITY_FORM' => 'وسم Form' ,
   'LBL_SECURITY_FRAME' => 'وسم Frame' ,
   'LBL_SECURITY_FRAMESET' => 'وسم Frameset' ,
   'LBL_SECURITY_IFRAME' => 'وسم iFrame' ,
   'LBL_SECURITY_IMPORT' => 'وسم Import' ,
   'LBL_SECURITY_LAYER' => 'وسم Layer' ,
   'LBL_SECURITY_LINK' => 'وسم Link' ,
   'LBL_SECURITY_OBJECT' => 'وسم Object' ,
   'LBL_SECURITY_OUTLOOK_DEFAULTS' => 'أختر الأحتياطات الأمنية الأساسية التلقائية للـ Outlook ( الأخطاء على جانب العرض الصحيح)' ,
   'LBL_SECURITY_PRESERVE_RAW' => 'أحتفظ بالرسالة الإلكترونية الأصلية، بما فيها من محتويات قد تكون ضارة. هذا الإختيار سيحتفظ فقط الرسائل الأساسية في قاعدة البيانات؛ فهي لن تسمح بظهور محتويات غير منقاه من خلال واجهة مستخدم شوجر سي أر أم' ,
   'LBL_SECURITY_SCRIPT' => 'وسم Script' ,
   'LBL_SECURITY_STYLE' => 'وسم Style' ,
   'LBL_SECURITY_TOGGLE_ALL' => 'تثبيت كل الإختيارات' ,
   'LBL_SECURITY_XMP' => 'وسم Xmp' ,
   'LBL_YES' => 'نعم' ,
   'LBL_NO' => 'لا' ,
   'LBL_PREPEND_TEST' => ']أختبار[: ' );

?>
