<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Activities/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_NAME' => 'أنشطة' ,
   'LBL_MODULE_TITLE' => 'الأنشطة: رئيسية' ,
   'LBL_SEARCH_FORM_TITLE' => 'البحث في الأنشطة' ,
   'LBL_LIST_FORM_TITLE' => 'قائمة الأنشطة' ,
   'LBL_LIST_SUBJECT' => 'الموضوع' ,
   'LBL_LIST_CONTACT' => 'جهة إتصال' ,
   'LBL_LIST_RELATED_TO' => 'متعلق ب' ,
   'LBL_LIST_DATE' => 'تاريخ' ,
   'LBL_LIST_TIME' => 'زمن البدء' ,
   'LBL_LIST_CLOSE' => 'إغلاق' ,
   'LBL_SUBJECT' => 'الموضوع:' ,
   'LBL_STATUS' => 'الحالة:' ,
   'LBL_LOCATION' => 'المكان:' ,
   'LBL_DATE_TIME' => 'تاريخ وزمن البدء:' ,
   'LBL_DATE' => 'تاريخ البدء:' ,
   'LBL_TIME' => 'زمن البدء:' ,
   'LBL_DURATION' => 'المدة الزمنية:' ,
   'LBL_HOURS_MINS' => '(دقائق/ساعات)' ,
   'LBL_CONTACT_NAME' => 'اسم جهة الإتصال: ' ,
   'LBL_MEETING' => 'اجتماع:' ,
   'LBL_DESCRIPTION_INFORMATION' => 'معلومات الوصف' ,
   'LBL_DESCRIPTION' => 'وصف:' ,
   'LBL_COLON' => ':' ,
   'LBL_DEFAULT_STATUS' => 'مخطط' ,
   'LNK_NEW_CALL' => 'جدولة المكالمة' ,
   'LNK_NEW_MEETING' => 'جدولة الاجتماع' ,
   'LNK_NEW_TASK' => 'إنشاء مهمة' ,
   'LNK_NEW_NOTE' => 'إنشاء ملاحظة أو مرفقا' ,
   'LNK_NEW_EMAIL' => 'إنشاء بريدا في الأرشيف' ,
   'LNK_CALL_LIST' => 'مكالمات' ,
   'LNK_MEETING_LIST' => 'اجتماعات' ,
   'LNK_TASK_LIST' => 'مهام' ,
   'LNK_NOTE_LIST' => 'ملاحظات' ,
   'LNK_EMAIL_LIST' => 'رسائل إلكترونية' ,
   'ERR_DELETE_RECORD' => 'لابد من تحديد رقم السجل للتمكن من حذف الحساب' ,
   'NTC_REMOVE_INVITEE' => 'هل أنت متأكد من أنك تريد إلغاء هؤلاء المدعوون من الاجتماع' ,
   'LBL_INVITEE' => 'المدعوون' ,
   'LBL_LIST_DIRECTION' => 'توجيه' ,
   'LBL_DIRECTION' => 'توجيه' ,
   'LNK_NEW_APPOINTMENT' => 'ميعاد جديد' ,
   'LNK_VIEW_CALENDAR' => 'اليوم' ,
   'LBL_OPEN_ACTIVITIES' => 'أنشطة مفتوحة' ,
   'LBL_HISTORY' => 'سيرة' ,
   'LBL_UPCOMING' => 'المواعيد القادمة' ,
   'LBL_TODAY' => 'من خلال ' ,
   'LBL_NEW_TASK_BUTTON_TITLE' => 'إنشاء مهمة [Alt+N]' ,
   'LBL_NEW_TASK_BUTTON_KEY' => 'N' ,
   'LBL_NEW_TASK_BUTTON_LABEL' => 'إنشاء مهمة' ,
   'LBL_SCHEDULE_MEETING_BUTTON_TITLE' => 'جدولة الاجتماع [Alt+M]' ,
   'LBL_SCHEDULE_MEETING_BUTTON_KEY' => 'M' ,
   'LBL_SCHEDULE_MEETING_BUTTON_LABEL' => 'جدولة الاجتماع' ,
   'LBL_SCHEDULE_CALL_BUTTON_TITLE' => 'جدولة المكالمة [Alt+C]' ,
   'LBL_SCHEDULE_CALL_BUTTON_KEY' => 'C' ,
   'LBL_SCHEDULE_CALL_BUTTON_LABEL' => 'جدولة المكالمة' ,
   'LBL_NEW_NOTE_BUTTON_TITLE' => 'إنشاء ملاحظة أو مرفقا [Alt+T]' ,
   'LBL_NEW_NOTE_BUTTON_KEY' => 'T' ,
   'LBL_NEW_NOTE_BUTTON_LABEL' => 'إنشاء ملاحظة أو مرفقا' ,
   'LBL_TRACK_EMAIL_BUTTON_TITLE' => 'إحالة البريد الإلكتروني للأرشيف [Alt+K]' ,
   'LBL_TRACK_EMAIL_BUTTON_KEY' => 'K' ,
   'LBL_TRACK_EMAIL_BUTTON_LABEL' => 'إحالة البريد الإلكتروني للأرشيف' ,
   'LBL_LIST_STATUS' => 'الحالة' ,
   'LBL_LIST_DUE_DATE' => 'مطلوب بتاريخ' ,
   'LBL_LIST_LAST_MODIFIED' => 'آخر مرة تعديل' ,
   'NTC_NONE_SCHEDULED' => 'غير مجدول' ,
   'LNK_IMPORT_NOTES' => 'استورد ملاحظات' ,
   'NTC_NONE' => 'لاشئ' ,
   'LBL_ACCEPT_THIS' => 'قبول؟' ,
   'LBL_DEFAULT_SUBPANEL_TITLE' => 'أنشطة مفتوحة' ,
   'LBL_LIST_ASSIGNED_TO_NAME' => 'المستخدم المكلف' ,
   'appointment_filter_dom' => array (
      'today' => 'اليوم' ,
      'tomorrow' => 'غدا' ,
      'this Saturday' => 'هذا الأسبوع' ,
      'next Saturday' => 'الأسبوع التالي' ,
      'last this_month' => 'هذا الشهر' ,
      'last next_month' => 'الشهر التالي'   ));

?>
