<?php

 /*********************************************************************************
  * The contents of this file are subject to the SugarCRM Professional End User
  * License Agreement ('License') which can be viewed at
  * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
  * By installing or using this file, You have unconditionally agreed to the
  * terms and conditions of the License, and You may not use this file except in
  * compliance with the License.  Under the terms of the license, You shall not,
  * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
  * or otherwise transfer Your rights to the Software, and 2) use the Software
  * for timesharing or service bureau purposes such as hosting the Software for
  * commercial gain and/or for the benefit of a third party.  Use of the Software
  * may be subject to applicable fees and any use of the Software without first
  * paying applicable fees is strictly prohibited.  You do not have the right to
  * remove SugarCRM copyrights from the source code or user interface.
  * All copies of the Covered Code must include on each user interface screen:
  * (i) the 'Powered by SugarCRM' logo and
  * (ii) the SugarCRM copyright notice
  * in the same form as they appear in the distribution.  See full license for
  * requirements.
  * Your Warranty, Limitations of liability and Indemnity are expressly stated
  * in the License.  Please refer to the License for the specific language
  * governing these rights and limitations under the License.  Portions created
  * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
  ********************************************************************************/
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/ContractTypes/language/ar_eg.lang.php,  Fri 13/04/07 19:21:39 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): IT Synergy
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ID' => 'هوية' ,
   'LBL_DATE_ENTERED' => 'التاريخ المُدخل' ,
   'LBL_DATE_MODIFIED' => 'التاريخ المعدّل' ,
   'LBL_MODIFIED_USER_ID' => 'هوية المستخدم المعدّل' ,
   'LBL_CREATED_BY' => 'أنشئ بواسطة' ,
   'LBL_DELETED' => 'تم الحذف' ,
   'LBL_DOCUMENTS' => 'مستندات' ,
   'LBL_TYPE_NAME' => 'أسم النوع' ,
   'LBL_MODULE_NAME' => 'نوع العقد' ,
   'LBL_MODULE_TITLE' => 'أنواع العقود' ,
   'LBL_LIST_FORM_TITLE' => 'أنواع العقود' ,
   'LBL_CONTRACT_TYPE' => 'نوع العقد' ,
   'LBL_LIST_ORDER' => 'ترتيب القائمة:' ,
   'LNK_CONTRACTTYPE_LIST' => 'أنواع العقود' ,
   'LBL_LIST_NAME' => 'اسم' ,
   'LBL_LIST_LIST_ORDER' => 'ترتيب القائمة' ,
   'LBL_NAME' => 'اسم:' ,
   'NTC_DELETE_CONFIRMATION' => 'هل تريد مسح نوع العقد' ,
   'LBL_DOCUMENTS_SUBPANEL_TITLE' => 'مستندات' );

?>
